WexGit/Wex_DX/force-app/main/default/objects/CTI_POP_Settings__c/CTI_POP_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>CTI POP Settings</description>
    <label>CTI POP Settings</label>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/CTI_POP_Settings__c/fields/Gadget_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Gadget_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Gadget Enabled</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Customer_Dashboard_Services__c.object
<CustomObject>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/Customer_Dashboard_Services__c/fields/API_Timeout_ms__c.field-meta.xml
<CustomField>
    <fullName>API_Timeout_ms__c</fullName>
    <label>API Timeout ms</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Customer_Dashboard_Services__c/fields/Customer_Details_EndPoint__c.field-meta.xml
<CustomField>
    <fullName>Customer_Details_EndPoint__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Customer Details EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>ACD_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The ACD Id is the same as the Windows login Id</inlineHelpText>
        <label>ACD Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/WEXCTIAdapterControllerTest.cls
@isTest
public with sharing class WEXCTIAdapterControllerTest {

    @testSetup
    static void setupTest() {

        UtilityTestLoader.setAutomation(false);
        
        Profile profile = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator'];

        insert new User(
                isActive = true,
                profileId = profile.Id,
                alias = 'ctite',
                firstName = 'CTI',
                lastName = 'Tester',
                email = 'ctitest@wexinc.com',
                username = 'ctitest@wexinc.com',
                emailEncodingKey = 'UTF-8',
                languageLocaleKey = 'en_US',
                localeSidKey = 'en_US',
                timeZoneSidKey = 'America/Los_Angeles',
                country = 'United States',
                ACD_Id__c = 'test2'
        );
     
        insert new Customer_Dashboard_Services__c(Customer_Details_EndPoint__c = 'http://test.wexlocal.com', API_Timeout_ms__c = 20000);

        if (profile != null && profile.Id != null) {
            
            insert new CTI_POP_Settings__c(SetupOwnerId = profile.Id, Gadget_Enabled__c = false);

        }

    }

    static testMethod void testWEXCTIAdapterController() {

        Test.startTest();

        TestUtils.enable_isRunningTest = true;

        Test.setMock(WebServiceMock.class, new CustomerDetailsWSUtilv2_Mock());

        User runAsUser = [SELECT Id, ACD_Id__c FROM User WHERE Alias = 'ctite'];

        System.runAs(runAsUser) {

            WEXCTIAdapterController.CustomerSearchResult customerDetails = WEXCTIAdapterController.accountAndContactSearch('9100000000000', null, '1234567890');

            System.assertEquals('9100000000000', customerDetails.wexAccountNumber);
            
            customerDetails = WEXCTIAdapterController.accountAndContactSearch(null, null, '1234567890');
            
            System.assertEquals(customerDetails.companyName, 'Test');

            User ctiUser = WEXCTIAdapterController.getUserInformation();

            System.assert(ctiUser.ACD_Id__c == runAsUser.ACD_Id__c);
            
            CTI_POP_Settings__c ctiPopSettings = WEXCTIAdapterController.getCTIPOPSettings();
            
            System.assertEquals(ctiPopSettings.Gadget_Enabled__c, false);

        }

        Test.stopTest();

    }

}