src/objects/Account_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Assets</relationshipLabel>
        <relationshipName>Account_Assets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Close_Date__c</fullName>
        <formula>Opportunity__r.CloseDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Account Assets</relationshipLabel>
        <relationshipName>Account_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Asset</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Commission__c.object
<CustomObject>
</CustomObject>

src/objects/Gallons_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Asset</label>
        <referenceTo>Account_Asset__c</referenceTo>
        <relationshipLabel>Gallons Data</relationshipLabel>
        <relationshipName>Gallons_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gallon_Month__c</fullName>
        <description>The first of the month for the monthly gallons total.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The first of the month for the monthly gallons total.</inlineHelpText>
        <label>Gallons Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gallons_Amount__c</fullName>
        <label>Gallons Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Gallons Data</label>
    <nameField>
        <displayFormat>G-{00000000}</displayFormat>
        <label>Gallons Data Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gallons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OppRecordTypeForComm__c.object
<CustomObject>
</CustomObject>

src/classes/Test_totalCommissionsBatch.cls
/**
 * Created By: Phillip Southern (GearsCRM)
 */
@isTest
private class Test_totalCommissionsBatch {

//    @testSetup
//    static void setup(){
//        UtilityTestLoader.setAutomation(false);
//    }
//
//    static testMethod void myUnitTest() {
//
//
//        date oppclosedate = date.newInstance(system.now().year(),2,1);
//        Account a = new Account(name='test');
//        insert a;
//
//        RecordType rt = [Select Id, Name from RecordType Where sobjectType='Opportunity' and IsActive = true LIMIT 1];
//        OppRecordTypeForComm__c opprtc = new OppRecordTypeForComm__c(name=rt.name);
//        opprtc.RecordTypeId__c = rt.id;
//
//        insert opprtc;
//
//        Opportunity o = new Opportunity(name='test',amount=100,accountid=a.Id,stagename='5) Signed',closedate=system.now().date(), recordtypeid=rt.id);
//        insert o;
//        Account_Asset__c aac = new Account_Asset__c(account__c=a.Id,opportunity__c=o.Id);
//        insert aac;
//
//        //o.Account_Asset__c = aac.Id;
//        //update o;
//
//        Date dateToSet = date.newinstance(system.now().date().addDays(90).year(), system.now().date().addDays(90).month(),1);
//
//        Gallons_Data__c gd = new Gallons_Data__c(account_Asset__c=aac.Id,Gallons_Amount__c=100,Gallon_Month__c=datetoSet); //system.now().date());
//        insert gd;
//
//        test.startTest();
//        //do batch here
//        SchedulableContext sc;
//        totalCommissionsBatch tcb = new totalCommissionsBatch();
//        tcb.execute(sc);
//        test.stopTest();
//        Opportunity ocheck = [select id, name, closedate, stagename, accountid, account_asset__c from Opportunity];
//        system.debug('-- ' + ocheck);
//
//        //asserts
//        //Date datecheck = date.newinstance(system.now().date().addDays(90).year(), system.now().date().addDays(90).month(),1);
//        Commission__c c = [Select Commission_Report_Date__c, Total_Commissionable_Gallons__c, Opportunity__c, Opportunity__r.Account_Asset__c, Opportunity_Close_Date__c
//                        from Commission__c LIMIT 1];
//        system.debug('-- ' + c);
//
//        //system.assert(c.Total_Commissionable_Gallons__c == gd.Gallons_Amount__c);
//    }
}