src/objects/Account_Status_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Status Histories</relationshipLabel>
        <relationshipName>Account_Status_Histories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Auto_Limit_Increased__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Limit Increased</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Status History</label>
    <nameField>
        <displayFormat>Ash-{00000}</displayFormat>
        <label>Account Status History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Status Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Credit_Assessment__c.object
<CustomObject>
</CustomObject>

src/objects/Credit_Insurance__c.object
<CustomObject>
</CustomObject>

src/objects/Credit_Utilization_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Credit_Utilizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Utilization__c</fullName>
        <formula>( Overall_balance__c  / Overall_Credit_limit__c )</formula>
        <label>Credit Utilisation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Overall_Credit_limit__c</fullName>
        <label>Overall Credit Limit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Overall_balance__c</fullName>
        <label>Overall Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Credit Utilisation History</label>
    <nameField>
        <displayFormat>CredutilHist{00000}</displayFormat>
        <label>Credit Utilisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Utilisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Currency_Conversion__c.object
<CustomObject>
</CustomObject>

src/objects/Wes_Accounts_Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Account Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Wes Accounts Receivables</relationshipLabel>
        <relationshipName>Wes_Accounts_Receivables</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Client_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Client Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Wex_UK_Configurable__c.object
<CustomObject>
    <fields>
        <fullName>Account_Dates__c</fullName>
        <description>In days First Trans Date  Invoice Date Account Creation</description>
        <label>Account Dates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confidence_Threshold_DNB__c</fullName>
        <label>Confidence Threshold DNB</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confidence_Threshold_EFX__c</fullName>
        <label>Confidence Threshold EFX</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Limit_Threshold__c</fullName>
        <label>Credit Limit Threshold (Euros)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Util_threshold__c</fullName>
        <label>Credit Utilisation Threshold (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_Date_upper__c</fullName>
        <description>creditAssRiskGrade &gt; 3</description>
        <label>Expiry Date Upper (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_date_lower__c</fullName>
        <description>creditAssRiskGrade &lt;= 3</description>
        <label>Expiry Date Lower (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HLA_Threshold__c</fullName>
        <label>HLA Threshold (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>High_Cred_Util_limit__c</fullName>
        <label>High Cred Utilisation Limit (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nird_Review__c</fullName>
        <description>The number of days until expiration.</description>
        <label>Nird Review (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Cred_Lmt_threshold__c</fullName>
        <label>Overall Credit Limit Threshold (Euros)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pre_HLA_Lower__c</fullName>
        <label>Pre HLA Lower (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pre_HLA_Upper__c</fullName>
        <label>Pre HLA Upper (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/WexUK_Reassessment_Handler_Test.cls
@isTest
Private class WexUK_Reassessment_Handler_Test {
@testSetup
static void setup(){
   UtilityTestLoader.setAutomation(false);
}

    static  testmethod void mytestClassMethod() {

        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        Credit_Assessment__c creditAss = new Credit_Assessment__c();
        creditAss.Account__c = acc.id;
        creditAss.Review_Type__c = 'HLA';

        insert creditAss;

        map<id, id> accutidAssmtidMap = new   map<id, id>();
        accutidAssmtidMap.put(acc.id, creditAss.id);

        list<Account> acctlist = new list<account>();
        acctlist.add(acc);

        WexUK_DnBCalloutProcess DnBCall = new WexUK_DnBCalloutProcess();
        //DnBCall.DnBScenarioForTest = 'HIT';

        DnBCall.preformDnB_WF(acctlist, accutidAssmtidMap);

        // DnBCall.DnBScenarioForTest = 'HIT';


    }

    static  testmethod void createCreditAsmtTest() {

        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        list<Account> acctlist = new list<account>();
        acctlist.add(acc);

        WexUK_Reassessment_Handler.createCreditAsmt(acctlist);

        acc.Credit_Utilization__c = 85;
        WexUK_Reassessment_Handler.createCreditAsmt(acctlist);

        acc.Credit_Utilization__c = 20;
        acc.Nird__c = system.today() - 100;

        WexUK_Reassessment_Handler.createCreditAsmt(acctlist);

    }

    static  testmethod void calculateExpiryDateTest() {


        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Risk_Grade_UK__c = '3 - Medium', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        Credit_Assessment__c creditAss = new Credit_Assessment__c();
        creditAss.Account__c = acc.id;
        creditAss.Review_Type__c = 'HLA';

        insert creditAss;

        map<id, id> accutidAssmtidMap = new   map<id, id>();
        accutidAssmtidMap.put(acc.id, creditAss.id);

        list<Account> acctlist = new list<account>();
        acctlist.add(acc);

        WexUK_Reassessment_Handler.calculateExpiryDate(acc, creditAss);

        acc.Risk_Grade_UK__c = '4 - High';
        update acc;
        WexUK_Reassessment_Handler.calculateExpiryDate(acc, creditAss);




    }

    static  testmethod void  calculateCreditUtilizationTest() {

        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        Credit_Assessment__c creditAss = new Credit_Assessment__c();
        creditAss.Account__c = acc.id;
        creditAss.Review_Type__c = 'HLA';

        insert creditAss;

        map<id, id> accutidAssmtidMap = new   map<id, id>();
        accutidAssmtidMap.put(acc.id, creditAss.id);

        list<Account> acctlist = new list<account>();
        acctlist.add(acc);


        WexUK_Reassessment_Handler.calculateCreditUtilization(acc, creditAss);


        Credit_Utilization_History__c cuh = new Credit_Utilization_History__c(Overall_balance__c = 20, Overall_Credit_limit__c = 2,  account__c = acc.id);
        insert cuh;

        WexUK_Reassessment_Handler.calculateCreditUtilization(acc, creditAss);

        creditAss.Review_Type__c = 'NIRD';

        WexUK_Reassessment_Handler.calculateCreditUtilization(acc, creditAss);

    }

    static  testmethod void  calculateAutolimitIncreaseTest() {

        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        Account_Status_History__c history = new Account_Status_History__c(Account__c = acc.Id, Auto_Limit_Increased__c = true);

        insert history ;

        WexUK_Reassessment_Handler.calculateAutolimitIncrease(acc);

    }

    static  testmethod void performCurrencyConversionTest() {

        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect', billingcountry = 'GB',   Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        Currency_Conversion__c cc = new Currency_Conversion__c(Currency_Value_Euro__c = 100, Client_Id__c = '100');
        insert cc;



        WexUK_Reassessment_Handler.performCurrencyConversion(acc.Account_Id__c , 1000);

        delete cc;

        WexUK_Reassessment_Handler.performCurrencyConversion(acc.Account_Id__c , 1000);

    }

    static  testmethod void WexUK_EquifaxCalloutProcessTest() {

        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        Credit_Assessment__c creditAss = new Credit_Assessment__c();
        creditAss.Account__c = acc.id;
        creditAss.Review_Type__c = 'HLA';

        insert creditAss;

        map<id, id> accutidAssmtidMap = new   map<id, id>();
        accutidAssmtidMap.put(acc.id, creditAss.id);

        list<Account> acctlist = new list<account>();
        acctlist.add(acc);

        WexUK_EquifaxCalloutProcess EfxCall = new WexUK_EquifaxCalloutProcess();
        //DnBCall.DnBScenarioForTest = 'HIT';

        EfxCall.preformEfx_WF(acctlist, accutidAssmtidMap);

        // DnBCall.DnBScenarioForTest = 'HIT';


    }

    static  testmethod void ValidateAccountsTest() {
        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');

        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c = -90 , Confidence_Threshold_DNB__c = -1 , Confidence_Threshold_EFX__c = -1 , Credit_Limit_Threshold__c = 12500    , Credit_Util_threshold__c = 75    , CurrencyIsoCode = 'USD'   , Expiry_date_lower__c = 24    , Expiry_Date_upper__c = 12    , High_Cred_Util_limit__c = 50 , HLA_Threshold__c = 80        , Name = 'Wex UK'    , Nird_Review__c = 30  , Overall_Cred_Lmt_threshold__c = 10000    , Pre_HLA_Lower__c = 75    , Pre_HLA_Upper__c = 80);
        insert configVals ;

        Credit_Assessment__c creditAss = new Credit_Assessment__c();
        creditAss.Account__c = acc.id;
        creditAss.Review_Type__c = 'HLA';

        insert creditAss;

        WexUK_Reassessment_Handler.ValidateAccounts(new Account[] {acc}, new Map<Id, Credit_Assessment__c> {acc.id => creditAss} );

        Credit_Insurance__c insurance = new Credit_Insurance__c(Expiration_Date__c = Date.Today() + 10 , Insured_limit__c = 20, Account__c = acc.Id);
        insert insurance;

        WexUK_Reassessment_Handler.ValidateAccounts(new Account[] {acc}, new Map<Id, Credit_Assessment__c> {acc.id => creditAss} );


    }

    static  testmethod void updateIsParentOverdueTest() {
        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');
        Account acc = new Account(Account_Id__c = '100034nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc;

        Account acc1 = new Account(parentId = acc.Id, Account_Id__c = '100035nnhyhg', RecordTypeId = accRecordType.getRecordTypeId(), Name = 'Test account', Account_Type__c = 'Prospect',  Credit_Utilization__c = 76, Nird__c = System.Today());
        insert acc1;

        Wes_Accounts_Receivable__c rec = new Wes_Accounts_Receivable__c(Account__c = acc1.Id );

        insert rec;

        WexUK_Reassessment_Handler.updateIsParentOverdue(new Wes_Accounts_Receivable__c [] {rec});


    }


}