src/objects/Account_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Activated_Not_Pumped__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Activated Not Pumped</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activated__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Activated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Core_Card_Created__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Core Card Created</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Last_Activity__c</fullName>
        <description>updated from IT for marketing automation</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>updated from IT for marketing automation</inlineHelpText>
        <label>Last Activity</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Account Assets</relationshipLabel>
        <relationshipName>Account_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Signed_But_Not_Activated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>used for marketing automation</description>
        <inlineHelpText>used for marketing automation</inlineHelpText>
        <label>Signed But Not Activated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_N__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Under Executive Review - Do Not Contact</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Stopped_Pumping__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Fueled the previous two months but not last month.</description>
        <inlineHelpText>Fueled the previous two months but not last month.</inlineHelpText>
        <label>Stopped Pumping</label>
        <type>Checkbox</type>
    </fields>
    <label>Account Asset</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Gallons_Data__c.object
<CustomObject>
    <fields>
        <fullName>Account_Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Asset</label>
        <referenceTo>Account_Asset__c</referenceTo>
        <relationshipLabel>Gallons Data</relationshipLabel>
        <relationshipName>Gallons_Data</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gallon_Month__c</fullName>
        <description>The first of the month for the monthly gallons total.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The first of the month for the monthly gallons total.</inlineHelpText>
        <label>Gallons Date</label>
        <type>Date</type>
    </fields>
    <label>Gallons Data</label>
    <nameField>
        <displayFormat>G-{00000000}</displayFormat>
        <label>Gallons Data Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gallons Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
</CustomObject>

src/classes/UAccountAsset.cls
/* ************************************************************
 * Created By  : Phillip Southern (GearsCRM)
 * Created Date: 06/17/2013 
 * Description : Class UAccountAsset
 * 
 * Modified By   : Raja Yeccherla(GearsCRM)
 * Modified Date : 02/17/2015
 * Description   :
 * 
 * ************************************************************/

public class UAccountAsset 
{
    public static void opportunityPopulation(List<Account_Asset__c> records, Map<ID,Account_Asset__c> oldMap)
    {
        boolean isInsert = (oldMap == null);
        GlobalSettings__c gc = GlobalSettings__c.getorgdefaults();
        
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        for(Account_Asset__c aac : records)
        {
            if(aac.Opportunity__c!=null 
               && aac.RecordTypeID == gc.AccountAssetRecordTypeID__c
               &&
               (isInsert == true 
                || 
               (isInsert == false 
                 && oldMap.get(aac.Id).Opportunity__c != aac.Opportunity__c 
                 )))
            {
                Opportunity o = new Opportunity(id=aac.Opportunity__c);
                o.Account_Asset__c = aac.Id;
                opportunitiesToUpdate.add(o);
                //system.debug('-- filtered: ' + o);
            }
        }
        
        if(opportunitiesToUpdate.size()>0)
        {
            update opportunitiesToUpdate;
        }
    }
    
    public static void setAccountAssetStoppedPumping(Set<Id> recordIds)
    {   
        List<Account_Asset__c> recordsToUpdate = new List<Account_Asset__c>();
        
        DateTime now = DateTime.now();
        
        Date currentMonth = Date.newInstance(now.year(), now.month(), 1); //Set to the first of the month
        Date currentMonthMinus1 = Date.newInstance(now.year(), now.addMonths(-1).month(), 1);
        Date currentMonthMinus2 = Date.newInstance(now.year(), now.addMonths(-2).month(), 1);
        Date currentMonthMinus3 = Date.newInstance(now.year(), now.addMonths(-3).month(), 1);
        
        for(Account_Asset__c record : [select 
                                            Id,
                                            Stopped_Pumping__c,
                                            (select
                                                    Id,
                                                    Gallon_Month__c
                                                from
                                                    Gallons_Data__r
                                                where
                                                    (Gallon_Month__c <= :currentMonth and
                                                    Gallon_Month__c > :currentMonthMinus3)
                                                order by 
                                                    Gallon_Month__c desc)
                                        from
                                            Account_Asset__c
                                        where 
                                            Id in :recordIds])
        {
            UGears.UDebug.printDebug('GALLONS DATA: ' + record.Gallons_Data__r);
            
            Boolean stoppedPumping = false;
            Boolean hasCurrentMonthData = false;
            Boolean hasCurrentMonthMinus1Data = false;
            Boolean hasCurrentMonthMinus2Data = false;
            
            for(Gallons_Data__c gallonsData : record.Gallons_Data__r)
            {
                if(gallonsData.Gallon_Month__c != null)
                {
                    if(gallonsData.Gallon_Month__c.month() == currentMonth.month())
                    {
                        //We have a record for this month
                        stoppedPumping = false;
                        hasCurrentMonthData = true;
                        
                        break;
                    }
                    else if(gallonsData.Gallon_Month__c.month() == currentMonthMinus1.month())
                    {
                        hasCurrentMonthMinus1Data = true;
                    }
                    else if(gallonsData.Gallon_Month__c.month() == currentMonthMinus2.month())
                    {
                        hasCurrentMonthMinus2Data = true;
                    }       
                }
            }
            
            if(hasCurrentMonthData == false)
            {
                if(hasCurrentMonthMinus1Data == true && hasCurrentMonthMinus2Data == true)
                {
                    stoppedPumping = true;
                }
            }
            
            record.Stopped_Pumping__c = stoppedPumping; 
            
            recordsToUpdate.add(record);                    
        }       
        
        UGears.UDebug.printDebug('RECORDS TO UPDATE: ' + recordsToUpdate);                      
        
        try
        {
            update recordsToUpdate;
        }   
        catch(DmlException e)
        {
            System.debug('EXCEPTION: ' + e);
        }   
    }
    
    public static void setAccountAssetsSignedButNotActivated(Set<Id> recordIds)
    {
        List<Account_Asset__c> recordsToUpdate = new List<Account_Asset__c>();
        
        for(Account_Asset__c record : [select 
                                            Id,
                                            Signed_But_Not_Activated__c,
                                            Core_Card_Created__c                                            
                                        from
                                            Account_Asset__c
                                        where 
                                            Id in :recordIds and
                                            Activated__c = null and 
                                            Core_Card_Created__c != null and 
                                            IsDeleted = false])
        {
            if(record.Core_Card_Created__c < Date.today().addDays(-15))
            {
                record.Signed_But_Not_Activated__c = true;
            }
            else
            {
                record.Signed_But_Not_Activated__c = false;
            }
            
            recordsToUpdate.add(record);
        }
        
        try
        {
            update recordsToUpdate;
        }
        catch(DmlException e)
        {
            System.debug('EXCEPTION: ' + e);
        }
    }
    
    public static void setAccountAssetsActivatedButNotPumped(Set<Id> recordIds)
    {
        List<Account_Asset__c> recordsToUpdate = new List<Account_Asset__c>();
        
        for(Account_Asset__c record : [select 
                                            Id,
                                            Activated__c,
                                            Last_Activity__c                                            
                                        from
                                            Account_Asset__c
                                        where 
                                            Id in :recordIds and                                            
                                            Status_N__c = 'Active' and 
                                            IsDeleted = false])
        {
            if(record.Last_Activity__c == null && record.Activated__c < Date.today().addDays(-30))
            {
                record.Activated_Not_Pumped__c = true;
            }
            else
            {
                record.Activated_Not_Pumped__c = false;
            }
            
            recordsToUpdate.add(record);
        }
        
        UGears.UDebug.printDebug('RECORDS TO UPDATE: ' + recordsToUpdate);
        
        try
        {
            update recordsToUpdate;
        }
        catch(DmlException e)
        {
            System.debug('EXCEPTION: ' + e);
        }
    }
}