src/objects/Account_Asset__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Assets</relationshipLabel>
        <relationshipName>Account_Assets</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Asset</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Assets</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AccountAssetcStatsTriggerTest.cls
@isTest
private class AccountAssetcStatsTriggerTest {
//
//   static testMethod void testTrigger() {
//      //try {
//
//          Account a = new Account();
//          a.name = 'test';
//          insert a;
//
//          Account_Asset__c o = new Account_Asset__c();
//          o.account__c = a.id;
//          insert o;
//
//          System.assertNotEquals(null, o);
//      //}
//      //catch(Exception e) {
//       //   List<Account_Asset__c> l = [SELECT Id from Account_Asset__c LIMIT 1];
//        //  update l;
//         // System.assertNotEquals(null, l);
//      //}
//   }
}