src/objects/Accounts_Receivable__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field to the account object</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Accounts Receivable</relationshipLabel>
        <relationshipName>Accounts_Receivable</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Overdue__c</fullName>
        <label>Total Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Accounts Receivable</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Accounts Receivable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts Receivable</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Created for AU Exxon Mobile Asia Pac (EMAP) project.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Overdue__c</fullName>
        <label>Total Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>AOT_Amount__c</fullName>
        <description>The Amount Over Threshold for the program.</description>
        <label>AOT Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EMAP_Accounts_Receivable_Trigger_Test.cls
@isTest
private class EMAP_Accounts_Receivable_Trigger_Test {

    static testMethod void AccountReceivableTriggerTest() {
    	
    	Program__c prog = TestDatatUtility.getProgram1();
    	prog.AOT_Amount__c = 250;
    	insert prog;
    	
    	Account parentAcc = TestDatatUtility.getAccount();
    	parentAcc.Program__c = prog.id;
    	parentAcc.Hierarchy_Level__c = '03';
    	insert parentAcc;
    	
        Account acc = TestDatatUtility.getAccount();
    	acc.Program__c = prog.id;
    	acc.Hierarchy_Level__c = '03';
        acc.parentId = parentAcc.id;
        insert acc;
        
        Account acc2 = TestDatatUtility.getAccount();
    	acc2.Program__c = prog.id;
    	acc2.Hierarchy_Level__c = '03';
        acc2.parentId = parentAcc.id;
        insert acc2;

    	Invoice__c invoice = TestDatatUtility.getInvoice();
    	invoice.Account__c = acc.id;
    	insert invoice;
		
    	Accounts_Receivable__c testAR = TestDatatUtility.getAccountReceivable();
    	testAR.Account__c = acc.id;
    	testAR.Current_Balance__c = 1000;
        testAR.Total_Overdue__c = 300;
    	
    	Accounts_Receivable__c testAR2 = TestDatatUtility.getAccountReceivable();
    	testAR2.Account__c = acc2.id;
    	testAR2.Current_Balance__c = 1500;
        testAR2.Total_Overdue__c = 350;

		Test.startTest();
		
    	insert testAR;
    	insert testAR2;
    	
    	Test.stopTest();
    }
}