src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved - Conditions</fullName>
                </value>
                <value>
                    <fullName>Approved - Rereview-Conditional</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Declined - Pending Conditions</fullName>
                </value>
                <value>
                    <fullName>Declined Rerevw - Pending Conditions</fullName>
                </value>
                <value>
                    <fullName>Incomplete</fullName>
                </value>
                <value>
                    <fullName>Manager Review</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Re-review Aproved</fullName>
                </value>
                <value>
                    <fullName>Re-review Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Campaign_Program__c</fullName>
        <formula>Opportunity__r.Program_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Coupon_Code__c</fullName>
        <formula>Opportunity__r.Coupon_Code2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coupon Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Opportunity__r.Program_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Pricing__c.object
<CustomObject>
    <description>Object for storing pricing data</description>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <description>Psoft Program Relationship Code</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Psoft Program Relationship Code</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>risk_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Risk Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Pricing</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms and Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>F1_Contact</fullName>
        <active>true</active>
        <description>Standard contact record</description>
        <label>Standard Contact</label>
    </recordTypes>
    <recordTypes>
        <fullName>Revolver</fullName>
        <active>true</active>
        <description>A Contact Type For Revolver Records</description>
        <label>Revolver</label>
    </recordTypes>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Analytics_Body_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analytics - Body Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Analytics_Head_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for google analytics code</inlineHelpText>
        <label>Analytics - Head Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 2</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <description>Branded heading for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Long_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Long Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Brand_Tagline__c</fullName>
        <description>Branded tagline for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Tagline</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Confirmation_Info__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for confirmation page related text, urls, etc.</inlineHelpText>
        <label>Confirmation Info</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Custom_Email_Header_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>URL to wexhosted for this program&apos;s email header</inlineHelpText>
        <label>Custom Email Header URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Inside_Sales_Phone_Number__c</fullName>
        <description>Phone number of inside sales for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Inside Sales Phone Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Person_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for liver person code</inlineHelpText>
        <label>Live Person Code</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Peoplesoft Rel Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_BOCA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish BOCA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SideBar__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SideBar</label>
        <length>80000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Side_Panel_Title__c</fullName>
        <description>Title for left panel on BOCA</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a title to appear above left panel on BOCA layout</inlineHelpText>
        <label>Side Panel Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upload_Pricing_Data_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Upload Pricing Data Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeFormObject__c.object
<CustomObject>
    <fields>
        <fullName>Application_Number__c</fullName>
        <formula>Opportunity__r.Opportunity_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Request</label>
        <referenceTo>Application_Request__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <formula>TEXT(Opportunity__r.Application_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Program_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IPAddress__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>IPAddress</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Location Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotional_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Promotional Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TM_Session_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>TM Session ID</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeFormObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeFormObject</label>
        <referenceTo>WeFormObject__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isPG__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check from BOCA template if the PG fields should be displayed</description>
        <label>isPG</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/classes/CreditApplicationController.cls
public class CreditApplicationController {
    private String BASE_URL{get;set;}
    
    //Document related variables
    public Id logoURL {get;set;}     
    public Id cardURL {get;set;}    
    
    //attachment image for the ui-contact details
    public Id attImage{get;set;}
    
    
    //A param for google to track the page
    public String errors{get{if(errors == null)errors = '';return errors;}set;}
    
    //terms and conditions code
    public String terms {get;set;}
    
    //Branding Colors
    public String brand1{get;set;}
    public String brand2{get;set;}
    
    
    //program name
    public String name{get;set;}
    
    //sidebar 
    public String sidebar{get;set;}
    
    //pricing string
    public Campaign_Pricing__c  pricingObj{get;set;}
    
    //google analytics code
    public String googleAnalyticsHeadBlock{get;set;}
    public String googleAnalyticsBodyBlock{get;set;}
    
    //live person code
    public String livePerson{get;set;}
    
    //inside sales
    public String inSales{get;set;}
    
    //confirmation page content
    public String confirmation{get; set;}
    //confirmation page oppNum
    public String oppNum{get; set;}
    //application status info
    public String statusInfo{get; set;}
    //application status
    public String appStatus{get; set;}
    //error page
    public String errorMsg {get;set;}   
    
    //Brand Determining related variables    
    private Program__c pgm {get;set;}
    private Campaign_Program__c cp {get;set;}
    public String LocationCode{get;set;}
    public List<Campaign_Pricing__c> pricing {get;set;}
    private String couponCode {get;set;}
    
    //Email header URL
    public String emailURL{get;set;}
    
    //Map the fields of the pricing object so we can iterate through them dynamically
    public Map<String, String> fieldList{get; set;}  
    
    
    //For the email component
    public Program__c prog{get; set;}
    
    public String BrandLongName  {get;set;}
    
    //branded title and tagline
    public String PanelTitle{get;set;}
    public String BrandTitle {get;set;}
    public String BrandTagline{get;set;}
    
    public WeFormObject__c creditApp 
    {get{
        if(creditApp == null)
            creditApp = new WeFormObject__c();
        return creditApp;
    }
     set;
    }
    //Terms And Conditions
    public String termAndCond {
        get{
            StaticResource sr = [
                select Body
                from StaticResource
                where Name = 'BOCA_TC'
            ];
            return sr.Body.toString();
        }
    }
    //Disclosure
    //Terms And Conditions
    public String disclosure {
        get{
            StaticResource sr = [
                select Body
                from StaticResource
                where Name = 'Disclosure'
            ];
            return sr.Body.toString();
        }
    }
    
    //This initBrandCheck() method is used to redirect the form to the error page if there
    //is insufficient information to put together a branded BOCA (pgm/campaign_program)
    public PageReference initBrandCheck(){
        system.debug('inside initBrandCheck');
        
        //check to see if this is a preview
        String isPreview = ApexPages.CurrentPage().getParameters().get('preview');  
        SYSTEM.debug('preview is: '+ isPreview);
        
        //Get the Name of the page 
        String strurl = ApexPages.currentPage().getUrl();
        strurl = strurl.replaceFirst('/apex/',''); 
        strurl = EncodingUtil.urlEncode(strurl, 'UTF-8');  
        string[] strurlExtra = strurl.split('%3F',0);   
        strurl = strurlExtra[0]; 
        SYSTEM.debug('conf= '+strurl);
        pagereference redirect = null;
        String errorCode = '';
        
        if(isPreview != 'true' && strurl != 'CreditApplicationConfirmation' && strurl != 'CreditApplicationStatus' ){
            //If the program is null - meaning we dont have a program branded for what was in the url/urlparam, then error out.
            if (pgm == null){
                errorCode = WEXErrorUtility.INVALID_PROGRAM;
                redirect = new PageReference('/apex/NoProgramBOCAerror?errorCode=' + errorCode);          
                redirect.setRedirect(true);
                return redirect;
            }
            
            WEXBrandUtility util = new WEXBrandUtility();
            if (pgm.Publish_BOCA__c == false){
                errorCode = WEXErrorUtility.UNPUBLISHED;
                redirect = new PageReference('/apex/CreditApplicationError?errorCode=' + errorCode);       
                redirect.getParameters().put('pgm', pgm.Brand_Short_Name__c);
                redirect.setRedirect(true);
                return redirect;
            }           
            
            if (!util.isValidTemplateForProgram(ApexPages.CurrentPage().getUrl(), pgm)){
                errorCode = WEXErrorUtility.INVALID_TEMPLATE;
                redirect = new PageReference('/apex/CreditApplicationError?errorCode=' + errorCode);            
                redirect.setRedirect(true);
                return redirect;
            }
        }
        //If the page is the confirmation page, get the oppnum param
        if(strurl == 'CreditApplicationConfirmation'){
            //get the oppNum
            oppNum = ApexPages.CurrentPage().getParameters().get('oppNum');  
            SYSTEM.debug('oppNum on Confirmation' + oppNum);
            return null;
        }
        //if we come in on a check status with no pgm
        if(strurl ==  'CreditApplicationStatus' ){
            String prog = ApexPages.CurrentPage().getParameters().get('pgm'); 
            if(prog == NULL){	
                errorCode = WEXErrorUtility.INVALID_PROGRAM;
                redirect = new PageReference('/apex/NoProgramBOCAerror?errorCode=' + errorCode);          
                redirect.setRedirect(true);
                return redirect;
            }
        }
        
        return redirect;
    } 
    
    public PageReference CreditApplicationError(){
        String errorCode = ApexPages.CurrentPage().getParameters().get('errorCode');    
        
        if (errorCode != null){
            errorMsg = WEXErrorUtility.getErrorMessage(errorCode);
        }
        if(pgm != null){
            //for the branded error pages
            setupBranding();
            
        }
        
        
        return null;
    }
    
    public void setupBranding(){
        
        WEXBrandUtility util = new WEXBrandUtility();
        
        //**************************************************************
        //Initial Setup of program and campaign program  ***************
        
        //Variables used to determine brand
        String couponCodeUrlParam = ApexPages.CurrentPage().getParameters().get('cc');
        String brandUrlParam = ApexPages.CurrentPage().getParameters().get('pgm');  
        //the WE_ID is for the app status page when returning via the email link
        String weId = ApexPages.currentPage().getParameters().get('weId');
        String locCode = ApexPages.currentPage().getParameters().get('lc');
        String url = ApexPages.CurrentPage().getUrl();
        
        if(locCode != null){ LocationCode = locCode; }
        
        if(weId != null){
            //get the opp off of the weform
            WeFormObject__c stat = [SELECT  Opportunity__c, Id FROM WeFormObject__c WHERE Id =: weId];
            //query the opp for the app request
            Opportunity weOpp = [SELECT ID, Application_Request__c, Application_Status__c FROM Opportunity WHERE ID =: stat.Opportunity__c];
            //query the app request for the status
            Application_Request__c wef = [SELECT Application_Status__c, ID, Opportunity__c FROM Application_Request__c WHERE Opportunity__c =: weOpp.Id];
            //give that status back to the page
            appStatus = wef.Application_Status__c;
            
            SYSTEM.debug('status '+appStatus);
        }
        //Need to get the program
        pgm = util.setProgramFromURL(brandUrlParam, url);
        //Then need to get the campaign program for the t&c's
        if (pgm != null){
            //Now get the campaign based on the coupon code
            List<Campaign> campaigns = [select id from campaign where coupon_code__c = :couponCodeUrlParam];
            if (campaigns.size() == 0){                
                //Need to get the default campaign program for the program
                cp = util.getDefaultCampaignProgram(pgm);
            }else{
                cp = util.getCampaignProgram(pgm, campaigns[0]);
            }
            
        }
        if (pgm != null && cp != null){
            
            //**************************************************************
            //**************************************************************
            
            BrandLongName = pgm.Brand_Long_Name__c;
            //branded title and tagline
            BrandTitle = pgm.Brand_Heading__c;
            BrandTagline = pgm.Brand_Tagline__c;
            PanelTitle = pgm.Side_Panel_Title__c;
            //sidebar html
            sidebar = pgm.SideBar__c;
            //google
            googleAnalyticsBodyBlock = pgm.Analytics_Body_Block__c;
            googleAnalyticsHeadBlock = pgm.Analytics_Head_Block__c;
            
            //confirmation page 
            confirmation = pgm.Confirmation_Info__c;
            
            //livePerson code
            livePerson = pgm.Live_Person_Code__c;
            
            //inside sales
            inSales = ' '+ pgm.Inside_Sales_Phone_Number__c;
            
            //Email header
            emailURL = pgm.Custom_Email_Header_URL__c;
            
            //header name
            name = pgm.Name;
            
            //branded colors
            brand1 = pgm.Brand_Color_1__c;
            brand2 = pgm.Brand_Color_2__c;
            
            //retrieve attachment images
            Attachment card = [SELECT Id, Name, Body FROM Attachment where ParentId = : pgm.Id AND Name=:'ui-credit-card.png'];
            cardURL = card.id;
            
            Attachment logo = [SELECT Id, Name, Body FROM Attachment where ParentId = : pgm.Id AND Name=:'ui-logo.png'];
            logoURL = logo.id;
            
            //this sets the coupon code (for the pricing) to the appropriate one set on the program
            
            //coupon code
            couponCode = util.getCouponCode(cp);   
            creditApp.Promotional_Code__c = couponCode;
            
            //terms and conditions text
            terms= cp.Terms_and_Conditions__c;
            
            //set the campaign program
            creditApp.Campaign_Program_ID__c = cp.Id;
            creditApp.TM_Session_ID__c = UserInfo.getSessionId();
            //get the pricing information if the program's setup says it should be so..
            if (pgm.Upload_Pricing_Data_Flag__c == true){
                pricing = util.getPricing(pgm.Peoplesoft_rel_code__c,couponCode);
                
                WEXPricingHelper wexP = new WEXPricingHelper();
                //check to see if the pricing contains two rows of data
                //send the campaign pricing to the helper class and get the format map
                if(pricing.size() == 2){
                    SYSTEM.debug('pricing: '+pricing);
                    //if there are two rows only return the format map for the risk based pricing
                    Campaign_Pricing__c p1 = pricing.get(0);
                    Campaign_Pricing__c p2 = pricing.get(1);
                    SYSTEM.debug('pric 1: ' + p1.risk_code__c + 'pric 2: ' + p2.risk_code__c);
                    if(p1.risk_Code__c == '7'){
                        
                        fieldList = wexP.getPricing(pricing.get(0));
                        SYSTEM.debug('list: ' + fieldList );
                    }
                    if(p2.risk_code__c == '7'){
                        fieldList = wexP.getPricing(pricing.get(1));
                        SYSTEM.debug('list: ' + fieldList );
                    }
                }
                if(pricing.size() == 1){
                    fieldList = wexP.getPricing(pricing.get(0));
                }
                else if(pricing.size() == 0){ fieldList = null;}
                
                
            }
            
        }
        
    }
    public CreditApplicationController(){
        SYSTEM.debug('inside the controller');
        // SYSTEM.debug('fieldList'+ fieldMap);
        //**************************************************************
        //Initial Setup of program and campaign program  ***************
        setupBranding();
        
        
    }   
    //Turn the below on to deploy to Prod and comment out the dev method below
 
public void SendEmail(){
SYSTEM.debug('inside emailer');
List<RecordType> ctRecordTypes = [select Id from RecordType where sObjectType = 'Contact' and DeveloperName IN ('F1_Contact')];
Messaging.reserveSingleEmailCapacity(1);
Messaging.SingleEmailMessage confirm = new Messaging.SingleEmailMessage();
Contact c = new Contact();
c.FirstName = creditApp.First_Name__c;
c.LastName = creditApp.Last_Name__c;
c.Email = creditApp.Email__c;
c.RecordTypeId = ctRecordTypes[0].Id;
insert c;
confirm.setTemplateId('00X70000001EfPG');
confirm.setWhatId(creditApp.Id);
confirm.setTargetObjectId(c.id);
confirm.setSaveAsActivity(false);
confirm.setReplyTo('noreply@wexinc.com');
for(OrgWideEmailAddress owa : [select id, Address, DisplayName from OrgWideEmailAddress]) 
{
if(owa.Address.contains('noreply@wexinc.com')) 
confirm.setOrgWideEmailAddressId(owa.id); 
}
SYSTEM.debug('email header'+ emailURL);
Messaging.sendEmail(new Messaging.SingleEmailMessage[] {confirm});
//clean up
delete c;

} 

   /*    
    public void SendEmail(){
        SYSTEM.debug('inside emailer');
        List<RecordType> ctRecordTypes = [select Id from RecordType where sObjectType = 'Contact' and DeveloperName IN ('F1_Contact')];
        Messaging.reserveSingleEmailCapacity(1);
        Messaging.SingleEmailMessage confirm = new Messaging.SingleEmailMessage();
        Contact c = new Contact();
        c.FirstName = creditApp.First_Name__c;
        c.LastName = creditApp.Last_Name__c;
        c.Email = creditApp.Email__c;
        c.RecordTypeId = ctRecordTypes[0].Id;
        insert c;
        confirm.setTemplateId('00Xn0000000DdDf');
        confirm.setWhatId(creditApp.Id);
        confirm.setTargetObjectId(c.id);
        confirm.setSaveAsActivity(false);
        confirm.setReplyTo('noreply@wexinc.com.sit');
        for(OrgWideEmailAddress owa : [select id, Address, DisplayName from OrgWideEmailAddress]) 
        {
            if(owa.Address.contains('noreply@wexinc.com.sit')) 
                confirm.setOrgWideEmailAddressId(owa.id); 
        }
        SYSTEM.debug('email header'+ emailURL);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {confirm});
        //clean up
        delete c;
        
    }
    
*/    
    public Program__c getProg(String pId){
        //query the form for the emailer
        
        prog = [select id,  Custom_Email_Header_URL__c FROM Program__c WHERE id =:pId];
        return prog;
        
    }
    
    public PageReference SubmitCreditApplication(){
        
        system.debug('WITHIN THE SUBMIT.');
        PageReference page = null;
        
        //validate the fields and submit if !errors
        if(!CreditAppValidator.validateFields(CreditApp)){
            //get the 'Revolver' record type
            recordType type = [SELECT Name, Id FROM recordType WHERE sobjecttype = 'weFormObject__c' and name ='Revolver'];
            //set the recordtype to 'Revolver' 
            creditApp.RecordType = type;
            //check for the location code
            if(LocationCode != null){creditApp.Location_Code__c = LocationCode;}
            creditApp.IPAddress__c =  ApexPages.currentPage().getHeaders().get('X-Salesforce-SIP');
            creditApp.Program_Id__c = pgm.Id;
            
            //this one is a lookup for the email
            creditApp.Program__c = pgm.Id;
            creditApp.isPG__c = true;
            Database.SaveResult result = Database.insert(creditApp, false);
            if(result.isSuccess()){
                
                
                Id weId = result.getId();
                SYSTEM.debug('weForm'+ weId);
                WeFormObject__c we = [SELECT ID, Application_Number__c FROM WeFormObject__c WHERE ID =: weId];
                
                oppNum = we.Application_Number__c;
                SYSTEM.debug('opp'+ oppNum);
                sendEmail();
                
                page = new PageReference('/apex/CreditApplicationConfirmation?pgm='+pgm.Brand_Short_Name__c);
                page.getParameters().put('oppNum',oppNum);
                page.setRedirect(true);
                
                return page;
            }
            else{
                SYSTEM.debug('insert errors' + result.getErrors());
                
            }
            
        } 
        errors = 'formErrors';
        PageReference currPage = apexPages.currentPage();
        
        currPage.setRedirect(false);
        
        return currPage;
        
    }
    
    
}