src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Personal_Guarantor_SSN__c</fullName>
        <formula>Personal_Guarantor__r.SSN__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Personal Guarantor SSN</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Payer_ID_number__c</fullName>
        <formula>Account_Name__r.Tax_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Payer ID number</label>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CP_Application_Request__c.object
<CustomObject>
    <description>Corporate Payments BOCA application request</description>
    <fields>
        <fullName>Guarantor_Social_Security_Number__c</fullName>
        <label>Social Security Number</label>
        <length>11</length>
        <maskChar>asterisk</maskChar>
        <maskType>ssn</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Taxpayer_ID__c</fullName>
        <label>Taxpayer ID</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>CorporatePayments Application Request</label>
    <nameField>
        <displayFormat>Application-{YYYY}{MM}{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CorporatePayments Application Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>AO_Social_Security_Number__c</fullName>
        <label>Social Security #</label>
        <length>9</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Your business&apos; Employer Identification Number (EIN) or business owner&apos;s social security number, if there is no EIN.</inlineHelpText>
        <label>Federal Tax ID #</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreditUtil_AdvancedFraudChecks_SSN.cls
/**
 * Created by dgilbert on 9/18/2018.
 */

/*
 *
 * Credit Decision Engine
 * BREeze Function: Credit Line Calculator
 *
*/
global class CreditUtil_AdvancedFraudChecks_SSN implements BREeze.FunctionCheckerPrePost {

    static final String PASSED_CHECK = 'Passed';
    static final String FAILED_CHECK = 'Failed';
    static final String ERRORED_CHECK = 'Error';

    /*
        ^                                       #Start of expression
        (?!\b(\d)\1+-(\d)\1+-(\d)\1+\b)         #Don't allow all matching digits for every field
        (?!123-45-6789|219-09-9999|078-05-1120) #Don't allow "123-45-6789", "219-09-9999" or "078-05-1120"
        (?!666|000|9\d{2})\d{3}                 #Don't allow the SSN to begin with 666, 000 or
                                                 anything between 900-999
        -                                       #A dash (separating Area and Group numbers)
        (?!00)\d{2}                             #Don't allow the Group Number to be "00"
        -                                       #Another dash (separating Group and Serial numbers)
        (?!0{4})\d{4}                           #Don't allow last four digits to be "0000"
        $                                       #End of expression
        https://www.codeproject.com/articles/651609/validating-social-security-numbers-through-regular
     */
    static final String SSN_PATTERN = '^(?!\\b(\\d)\\1+\\b)(?!123456789|219099999|078051120)(?!666|000|9\\d{2})\\d{3}(?!00)\\d{2}(?!0{4})\\d{4}$';

    global object getFunctionValue(object functionName, sObject so, String fieldType, String functionExtension, String ruleName, Id ruleId) {

        try {
            Pattern ssnValidationPattern = Pattern.compile(SSN_PATTERN); // Matches valid ssn's
            if(so != null && ((so.Id).getSobjectType().getDescribe().getName()).equalsIgnoreCase('OnlineApplication__c')) {

                OnlineApplication__c onlineApplication = (OnlineApplication__c)so.clone();
                String ssn = (onlineApplication.AO_Social_Security_Number__c).replaceAll('[^0-9]','');
                if(!ssnValidationPattern.Matcher(ssn).matches() || JaroWinklerDistance.getScore((ssn), (onlineApplication.Federal_Tax_ID__c).replaceAll('[^0-9]','')) >= 1) {
                    return FAILED_CHECK;
                }

                return PASSED_CHECK;

            }
            else if(so != null && ((so.Id).getSobjectType().getDescribe().getName()).equalsIgnoreCase('CP_Application_Request__c')) {

                CP_Application_Request__c cpApplicationRequest = (CP_Application_Request__c)so.clone();
                String ssn = (cpApplicationRequest.Guarantor_Social_Security_Number__c).replaceAll('[^0-9]','');
                if(!ssnValidationPattern.Matcher(ssn).matches() || JaroWinklerDistance.getScore((ssn), (cpApplicationRequest.Taxpayer_ID__c).replaceAll('[^0-9]','')) >= 1) {
                    return FAILED_CHECK;
                }

                return PASSED_CHECK;

            }
            else if(so != null && ((so.Id).getSobjectType().getDescribe().getName()).equalsIgnoreCase('Application_Request__c')) {

                Application_Request__c applicationRequest = (Application_Request__c)so.clone();
                String ssn = (applicationRequest.Personal_Guarantor_SSN__c).replaceAll('[^0-9]','');
                if(!ssnValidationPattern.Matcher(ssn).matches() || JaroWinklerDistance.getScore((ssn), (applicationRequest.Tax_Payer_ID_number__c).replaceAll('[^0-9]','')) >= 1) {
                    return FAILED_CHECK;
                }

                return PASSED_CHECK;

            }

        }
        catch(Exception e) {

            System.debug('### Error comparing TIN to SSN: ' + e.getMessage() + ' (Line: ' + e.getLineNumber() + ')');

        }

        return ERRORED_CHECK;

    }

    global void postProcess() {

    }

    global void preProcess(List<sObject> records, String RuleName, String objectName) {

    }

}