src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>App_Signer_IP_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>App Signer IP Address</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Phone_Number__c</fullName>
        <formula>Account_Name__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business Phone Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNB_Resolved_DUNS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DUNS Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name_Text__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Name Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Street__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Street</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Physical_Zip_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Payer_ID_number__c</fullName>
        <formula>Account_Name__r.Tax_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Payer ID number</label>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CP_Application_Request__c.object
<CustomObject>
    <description>Corporate Payments BOCA application request</description>
    <fields>
        <fullName>Application_Signer_IP_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Signer IP Address</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Legal_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Legal Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNB_Resolved_DUNS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolved DUNS Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Taxpayer_ID__c</fullName>
        <label>Taxpayer ID</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>CorporatePayments Application Request</label>
    <nameField>
        <displayFormat>Application-{YYYY}{MM}{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CorporatePayments Application Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>AO_Social_Security_Number__c</fullName>
        <label>Social Security #</label>
        <length>9</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Business_Address_Line_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Street Address Line 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Street_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Your business&apos; physical street address.  Not a PO box (Ex: 123 Main Street).</inlineHelpText>
        <label>Street Address</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNB_Resolved_DUNS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolved DUNS Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Your business&apos; Employer Identification Number (EIN) or business owner&apos;s social security number, if there is no EIN.</inlineHelpText>
        <label>Federal Tax ID #</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>IP Address</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The name of your business as listed on your business license or according to the Federal Government.</inlineHelpText>
        <label>Legal Business Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/globalValueSets/US_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/CreditExistingExposureController.cls
/*
*
* Credit Existing Exposure
* Author: Derek Gilbert
* Initial Date: 8/21/2018
*
*/
public with sharing class CreditExistingExposureController {

    public String applicationId {
        get {
            if(ApexPages.currentPage().getParameters().get('id') != null) {
                return ApexPages.currentPage().getParameters().get('id');
            }
            return null;
        }
    }

    // This is for display purposes only..
    public CreditUtil_ExistingExposure.ExistingExposureRequest originalRequest { get; set; }

    public List<CreditUtil_ExistingExposure.ExistingExposureAccounts> duplicateAccounts { get; set; }

    public List<CreditUtil_ExistingExposure.ExistingExposureApplications> duplicateApplications { get; set; }

    public CreditUtil_ExistingExposure.ExistingExposureRequest existingExposureRequest { get; set; }

    public boolean hasNoRecords { get; set; }

    public CreditExistingExposureController(){

    }

    public void init() {

        existingExposureRequest = new CreditUtil_ExistingExposure.ExistingExposureRequest();

        if(((Id.valueOf(applicationId)).getSobjectType().getDescribe().getName()).equalsIgnoreCase('OnlineApplication__c')) {

            List<OnlineApplication__c> onlineApplications = [SELECT Id, Name, Legal_Business_Name__c, Business_Street_Address__c, Business_Address_Line_2__c,
                                                             City__c, State__c, Zip_Code__c, Federal_Tax_ID__c, DNB_Resolved_DUNS__c, Phone_Number__c, IP_Address__c, AO_Social_Security_Number__c
                                                                FROM OnlineApplication__c WHERE Id =: applicationId];

            if(onlineApplications.size() == 1) {

                existingExposureRequest.applicationId = applicationId;
                existingExposureRequest.applicationName = onlineApplications[0].Name;
                existingExposureRequest.legalBusinessName = onlineApplications[0].Legal_Business_Name__c;
                existingExposureRequest.addressLine1 = onlineApplications[0].Business_Street_Address__c;
                existingExposureRequest.city = onlineApplications[0].City__c;
                existingExposureRequest.state = onlineApplications[0].State__c;
                existingExposureRequest.postalCode = onlineApplications[0].Zip_Code__c;
                existingExposureRequest.phone = onlineApplications[0].Phone_Number__c;
                existingExposureRequest.duns = onlineApplications[0].DNB_Resolved_DUNS__c;
                existingExposureRequest.taxID = onlineApplications[0].Federal_Tax_ID__c;
                existingExposureRequest.pgSSN = onlineApplications[0].AO_Social_Security_Number__c;
                existingExposureRequest.ipAddress = onlineApplications[0].IP_Address__c;

                originalRequest = existingExposureRequest.clone();

                duplicateApplications = CreditUtil_ExistingExposure.getApplications(existingExposureRequest);

                duplicateAccounts = CreditUtil_ExistingExposure.getAccounts(existingExposureRequest);

            }
        }
        else if(((Id.valueOf(applicationId)).getSobjectType().getDescribe().getName()).equalsIgnoreCase('CP_Application_Request__c')) {

            List<CP_Application_Request__c> cpApplicationRequests = [SELECT Id, Name, Company_Legal_Name__c, Physical_Address_Line_1__c, Physical_City__c, Physical_State__c, Physical_Postal_Code__c,
                                                                        Business_Phone__c, Application_Signer_IP_Address__c, DNB_Resolved_DUNS__c, Taxpayer_ID__c
                                                                     FROM CP_Application_Request__c WHERE Id =: applicationId];

            if(cpApplicationRequests.size() == 1) {

                existingExposureRequest.applicationId = applicationId;
                existingExposureRequest.applicationName = cpApplicationRequests[0].Name;
                existingExposureRequest.legalBusinessName = cpApplicationRequests[0].Company_Legal_Name__c;
                existingExposureRequest.addressLine1 = cpApplicationRequests[0].Physical_Address_Line_1__c;
                existingExposureRequest.city = cpApplicationRequests[0].Physical_City__c;
                existingExposureRequest.state = cpApplicationRequests[0].Physical_State__c;
                existingExposureRequest.postalCode = cpApplicationRequests[0].Physical_Postal_Code__c;
                existingExposureRequest.ipAddress = cpApplicationRequests[0].Application_Signer_IP_Address__c;
                existingExposureRequest.phone = cpApplicationRequests[0].Business_Phone__c;
                existingExposureRequest.duns = cpApplicationRequests[0].DNB_Resolved_DUNS__c;
                existingExposureRequest.taxID = cpApplicationRequests[0].Taxpayer_ID__c;

                originalRequest = existingExposureRequest.clone();

                duplicateApplications = CreditUtil_ExistingExposure.getApplications(existingExposureRequest);

                duplicateAccounts = CreditUtil_ExistingExposure.getAccounts(existingExposureRequest);
            }
        }
        else if(((Id.valueOf(applicationId)).getSobjectType().getDescribe().getName()).equalsIgnoreCase('Application_Request__c')) {

            List<Application_Request__c> naApplicationRequests = [SELECT Id, Name, Opportunity_Name_Text__c, Physical_Street__c, Physical_City__c, Physical_State__c, Physical_Zip_Postal_Code__c,
                    Business_Phone_Number__c, App_Signer_IP_Address__c, Tax_Payer_ID_number__c, DNB_Resolved_DUNS__c
            FROM Application_Request__c WHERE Id =: applicationId];

            if(naApplicationRequests.size() == 1) {

                existingExposureRequest.applicationId = applicationId;
                existingExposureRequest.applicationName = naApplicationRequests[0].Name;
                existingExposureRequest.legalBusinessName = naApplicationRequests[0].Opportunity_Name_Text__c;
                existingExposureRequest.addressLine1 = naApplicationRequests[0].Physical_Street__c;
                existingExposureRequest.city = naApplicationRequests[0].Physical_City__c;
                existingExposureRequest.state = naApplicationRequests[0].Physical_State__c;
                existingExposureRequest.postalCode = naApplicationRequests[0].Physical_Zip_Postal_Code__c;
                existingExposureRequest.ipAddress = naApplicationRequests[0].App_Signer_IP_Address__c;
                existingExposureRequest.phone = naApplicationRequests[0].Business_Phone_Number__c;
                existingExposureRequest.duns = naApplicationRequests[0].DNB_Resolved_DUNS__c;
                existingExposureRequest.taxID = naApplicationRequests[0].Tax_Payer_ID_number__c;

                originalRequest = existingExposureRequest.clone();

                duplicateApplications = CreditUtil_ExistingExposure.getApplications(existingExposureRequest);

                duplicateAccounts = CreditUtil_ExistingExposure.getAccounts(existingExposureRequest);
            }
        }

    }

}