src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Forward_Application_to_Credit__c</fullName>
        <label>Forward Application to Credit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AppRequestAfterInsertTriggerHandler.cls
/**
 * Created by mfarrell on 2019-09-07.
 */

public class AppRequestAfterInsertTriggerHandler extends TriggerHandlerBase {

    public override void mainEntry(TriggerParameters tp) {

        afterInsertappReqToCreditDecisionEngine((List<Application_Request__c>) tp.newList);

    }

    private static void afterInsertappReqToCreditDecisionEngine(List<Application_Request__c> appRequestList) {

        Set<Id> arids = AppRequestTriggerDispatcher.appsForCreditDecision;

        for (Application_Request__c ar : appRequestList) {
            if (System.IsBatch() == false && System.isFuture() == false && (ar.Forward_Application_to_Credit__c != null && (ar.Forward_Application_to_Credit__c).equals('Yes'))) {
                arids.add(ar.Id);   // pass to a set in the TriggerDispatcher for processing.
                                    // This is to avoid the possibility of an AfterInsert and AfterUpdate entering the credit engine twice in the same execution.
            }
        }

    }

}