src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Fleet_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fleet Enrollment</label>
        <referenceTo>FleetEnrollment__c</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Request</label>
        <referenceTo>Application_Request__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <formula>Application_Request__r.Sales_Person__r.FirstName &amp; &quot; &quot; &amp; Application_Request__r.Sales_Person__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Person</label>
        <type>Text</type>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppRequestBeforeInsertTriggerHandler.cls
/**
 * Created by mfarrell on 2019-09-07.
 */

public class AppRequestBeforeInsertTriggerHandler extends TriggerHandlerBase {

    public override void mainEntry(TriggerParameters tp) {

        appReqBeforeInsert((List<Application_Request__c>) tp.newList);

    }

    private static void appReqBeforeInsert(List<Application_Request__c> appRequestList) {

        Map<Id, Id> arToOpptyMap = new Map<Id, Id>();
        Map<Id, Id> feToOpptyMap = new Map<Id, Id>();

        for (Application_Request__c ar : appRequestList) {
            if(ar.Opportunity__c!=null)arToOpptyMap.put(ar.Opportunity__c, ar.Id);
        }

        for (FleetEnrollment__c fe : [SELECT Id, Opportunity__c FROM FleetEnrollment__c WHERE Opportunity__c IN :arToOpptyMap.keySet()]) {
            feToOpptyMap.put(fe.Opportunity__c, fe.Id);
        }
        
        for (Application_Request__c applicationRequest : appRequestList) {

            if (applicationRequest.Sales_Person__c == null) {
                applicationRequest.Sales_Person__c = UserInfo.getUserId();
            }
            if (applicationRequest.Fleet_Enrollment__c == null && feToOpptyMap.size() > 0) {
                applicationRequest.Fleet_Enrollment__c = feToOpptyMap.get(applicationRequest.Opportunity__c);
            }
        }
    }
    
}