src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>DNB_Resolved_DUNS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DUNS Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doing_Business_As__c</fullName>
        <formula>Opportunity__r.Doing_Business_As__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Doing Business As?</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Structure__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Legal Structure</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Name_Text__c</fullName>
        <formula>Opportunity__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Name Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Physical_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Country__c</fullName>
        <label>Physical Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                    <default>true</default>
                    <label>US</label>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Physical_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Street_Line_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Street Line 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Physical_Street__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Street</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Physical_Zip_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Zip/Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Risk_Grade__c</fullName>
        <label>Risk Grade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>995</fullName>
                    <isActive>false</isActive>
                    <label>995</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIC_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SIC Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_Payer_ID_number__c</fullName>
        <formula>Account_Name__r.Tax_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax Payer ID number</label>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CP_Application_Request__c.object
<CustomObject>
    <description>Corporate Payments BOCA application request</description>
    <fields>
        <fullName>Company_Legal_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Company Legal Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DNB_Resolved_DUNS__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Resolved DUNS Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doing_Business_As__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Doing Business As</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Structure__c</fullName>
        <label>Legal Structure</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bank/Bank Holding Co/Credit Union</fullName>
                </value>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Corporation/Association</fullName>
                </value>
                <value>
                    <fullName>Federal/State/Local Government Agency or Authority</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Investment Company/Adviser</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Non-Statutory Trust</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Public Accounting Firm</fullName>
                </value>
                <value>
                    <fullName>Public Company and Majority Owned Affiliate</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Unincorporated Association</fullName>
                </value>
                <value>
                    <fullName>Natural Person</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>CorporatePayments Application Requests</relationshipLabel>
        <relationshipName>CorporatePayments_Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Physical_Address_Line_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Physical Address Line 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>US</fullName>
                    <default>true</default>
                    <label>US</label>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Physical_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Physical_State_Province__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Physical_Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>NB</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>NU</fullName>
                </value>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>PE</fullName>
                </value>
                <value>
                    <fullName>QC</fullName>
                </value>
                <value>
                    <fullName>SK</fullName>
                </value>
                <value>
                    <fullName>YT</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Physical_State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Risk_Grade__c</fullName>
        <label>Risk Grade</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>995</fullName>
                    <isActive>false</isActive>
                    <label>995</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SIC_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SIC Code</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Taxpayer_ID__c</fullName>
        <label>Taxpayer ID</label>
        <length>10</length>
        <maskChar>asterisk</maskChar>
        <maskType>lastFour</maskType>
        <type>EncryptedText</type>
    </fields>
    <label>CorporatePayments Application Request</label>
    <nameField>
        <displayFormat>Application-{YYYY}{MM}{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CorporatePayments Application Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Credit_Decision_Engine_Endpoints__mdt.object
<CustomObject>
    <label>Credit Decision Engine Endpoints</label>
    <pluralLabel>Credit Decision Engine Endpoints</pluralLabel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/Moodys_CreditLens_Mapping__mdt/Moodys_CreditLens_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Field mapping for Moody&apos;s CreditLens integration</description>
    <label>Moody&apos;s CreditLens Mapping</label>
    <pluralLabel>Moody&apos;s CreditLens Mapping</pluralLabel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/globalValueSets/US_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/CreditWS_CreditLensTest.cls
/**
 * Created by mfarrell on 2019-12-13.
 */
@IsTest
public class CreditWS_CreditLensTest {

    /**
     * Positive authentication test. Method being tested should return a generated token.
     */
    public static void creditLensAuthenticationPositiveTest() {

        Credit_Decision_Engine_Endpoints__mdt CLAuthSettings = CreditWS_CreditLens.CLAuthSettings;
        Credit_Decision_Engine_Endpoints__mdt CLCreateEntitySettings = CreditWS_CreditLens.CLCreateEntitySettings;
        Moodys_CreditLens_Mapping__mdt CLStockExchange = CreditWS_CreditLens.CLStockExchange('NASDAQ');

        //Metadata Asserts
        System.assert(CLStockExchange != null, 'Expected CLStockExchange Metadata, but didn\'t find any');
        System.assert(CLAuthSettings != null, 'Expected CLAuthSettings Metadata, but didn\'t find any');
        System.assert(CLCreateEntitySettings != null, 'Expected CLCreateEntitySettings Metadata, but didn\'t find any');

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new MockCalloutGenerator(new Set<String>{'creditLensAuthGood','creditLensAuthLogin'})); //set mock
        String token = CreditWS_CreditLens.creditLensAuthentication();
        Test.stopTest();

        //Callout Asserts
        System.assert(token != null, 'Expected token to be returned.');
    }

    /**
    * Positive Entity creation for Corporate Payments
    */
    public static void creditLensCreateEntityPostiveCPTest() {

        CP_Application_Request__c cpAppNoEntityId = [
                SELECT  Id, Name, Company_Legal_Name__c, Doing_Business_As__c, Physical_Country__c, Physical_Address_Line_1__c, Physical_City__c, Physical_State_Province__c, Physical_Postal_Code__c, SIC_Code__c,
                        Legal_Structure__c, CurrencyIsoCode, Taxpayer_ID__c, DNB_Resolved_DUNS__c, Stock_Symbol__c, Stock_Exchange__c, CreditLens_EntityID__c, Opportunity__r.OwnerId, Risk_Grade__c
                FROM CP_Application_Request__c
                WHERE Company_Legal_Name__c = 'Amazing Company 2' AND CreditLens_EntityID__c = NULL
                LIMIT 1];

        //sanity checks before we start testing
        System.assert(cpAppNoEntityId.CreditLens_EntityID__c == null, 'Expected Credit Lens Entity ID field to be null.');

        Set<Id> myIds = new Set<Id>{cpAppNoEntityId.Id};

        //to the test mobile!
        Test.startTest();
        TestUtils.enable_isRunningTest = true;

        Test.setMock(HttpCalloutMock.class, new MockCalloutGenerator(new Set<String>{'creditLensCreateGood','creditLensAuthLogin'})); //set mock
        for (Id id : myIds) {
            CreditWS_CreditLens.creditLensCreateEntityButton(id);
        }

        Test.stopTest();

        CP_Application_Request__c cpAppNewEntId = [
                SELECT  Id, CreditLens_EntityID__c
                FROM CP_Application_Request__c
                WHERE Id =: cpAppNoEntityId.Id
                LIMIT 1];

        System.assert(cpAppNewEntId.CreditLens_EntityID__c != null, 'Expected a credit lens entity ID, why don\'t we have one?');

    }

    /**
    * Positive Entity creation for NA Fleet
    */
    public static void creditLensCreateEntityPostiveNATest() {

        Application_Request__c naAppNoEntityId = [
                SELECT  Id, Name, Opportunity_Name_Text__c, Doing_Business_As__c, Physical_Country__c, Physical_Street__c, Physical_Street_Line_2__c, Physical_City__c, Physical_State__c, Physical_Zip_Postal_Code__c, SIC_Code__c,
                        Legal_Structure__c, CurrencyIsoCode, Tax_Payer_ID_number__c, DNB_Resolved_DUNS__c, Stock_Symbol__c, Stock_Exchange__c, Credit_Lens_Entity_ID__c, Opportunity__r.OwnerId, Risk_Grade__c
                FROM Application_Request__c
                WHERE Stock_Symbol__c = 'NYC' AND Credit_Lens_Entity_ID__c = NULL
                LIMIT 1];

        //sanity checks before we start testing
        System.assert(naAppNoEntityId.Credit_Lens_Entity_ID__c == null, 'Expected Credit Lens Entity ID field to be null.');

        Set<Id> myIds = new Set<Id>{naAppNoEntityId.Id};

        //to the test mobile!
        Test.startTest();
        TestUtils.enable_isRunningTest = true;

        Test.setMock(HttpCalloutMock.class, new MockCalloutGenerator(new Set<String>{'creditLensCreateGood','creditLensAuthLogin'})); //set mock
        for (Id id : myIds) {
            CreditWS_CreditLens.creditLensCreateEntityButton(id);
        }

        Test.stopTest();

        Application_Request__c naAppNewEntId = [
                SELECT  Id, Credit_Lens_Entity_ID__c
                FROM Application_Request__c
                WHERE Id =: naAppNoEntityId.Id
                LIMIT 1];

        System.assert(naAppNewEntId.Credit_Lens_Entity_ID__c != null, 'Expected a credit lens entity ID, why don\'t we have one?');

    }

    public static void creditLensUploadDocumentTest() {

        CP_Application_Request__c cpApp = [
                SELECT  Id, Name, Company_Legal_Name__c, Doing_Business_As__c, Physical_Country__c, Physical_Address_Line_1__c, Physical_City__c, Physical_State_Province__c, Physical_Postal_Code__c, SIC_Code__c,
                        Legal_Structure__c, CurrencyIsoCode, Taxpayer_ID__c, DNB_Resolved_DUNS__c, Stock_Symbol__c, Stock_Exchange__c, CreditLens_EntityID__c, Opportunity__r.OwnerId
                FROM CP_Application_Request__c
                WHERE Company_Legal_Name__c = 'Amazing Company 1' AND CreditLens_EntityID__c != NULL
                LIMIT 1];

        //sanity checks before we start testing
        System.assert(cpApp != null, 'Expected an app with an entity Id, didn\'t find one');

        Attachment selectedFile = [SELECT Id, Name, Body, ParentId, ContentType FROM Attachment WHERE Name =: 'TestFinancials.txt' LIMIT 1];
        selectedFile.ContentType = 'TEXT';

        Test.startTest();

        PageReference uploadDocumetPage = Page.UploadDocToCreditLens;
        uploadDocumetPage.getParameters().put('id', cpApp.Id);
        Test.setCurrentPage(uploadDocumetPage);

        UploadDocToCreditLensController uploadDocController = new UploadDocToCreditLensController();
        uploadDocController.setSelectedFile(selectedFile.Id);
        uploadDocController.init();

        System.assert(uploadDocController.appId.equals(cpApp.Id));

        Test.setMock(HttpCalloutMock.class, new MockCalloutGenerator('creditLensUploadDoc')); //set mock

        //todo assert something from the response

        uploadDocController.uploadDocuments();

        Test.stopTest();

    }

    public static void creditLensLinkDocToEntityTest() {

        CP_Application_Request__c cpApp = [
                SELECT  Id, Name, Company_Legal_Name__c, Doing_Business_As__c, Physical_Country__c, Physical_Address_Line_1__c, Physical_City__c, Physical_State_Province__c, Physical_Postal_Code__c, SIC_Code__c,
                        Legal_Structure__c, CurrencyIsoCode, Taxpayer_ID__c, DNB_Resolved_DUNS__c, Stock_Symbol__c, Stock_Exchange__c, CreditLens_EntityID__c, Opportunity__r.OwnerId
                FROM CP_Application_Request__c
                WHERE Company_Legal_Name__c = 'Amazing Company 1' AND CreditLens_EntityID__c != NULL
                LIMIT 1];


        //sanity checks before we start testing
        System.assert(cpApp != null, 'Expected an app with an entity Id, didn\'t find one');

        List<String> docIds = new List<String>();
        String docId = '7c81409d-e093-4bfc-9e87-b2aec8d0d2bc';
        docIds.add(docId);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, new MockCalloutGenerator('creditLensLinkDocToEntity')); //set mock

        //todo assert something from the response

        CreditWS_CreditLens.linkDocToEntity(cpApp.Id, docIds);

        Test.stopTest();

    }


}