src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sales_Stage__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Oppty__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Siebel Oppty #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Request</label>
        <referenceTo>Application_Request__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debug_Application_Parameter__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Debug Application Parameter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppRequestBeforeUpdateTriggerHandler.cls
/**
 * Created by mfarrell on 2019-09-07.
 */

public class AppRequestBeforeUpdateTriggerHandler extends TriggerHandlerBase {

    public override void mainEntry(TriggerParameters tp) {

        updateRelatedFERecords((List<Application_Request__c>) tp.newList, (Map<Id,Application_Request__c>) tp.oldMap);

    }

    private static void updateRelatedFERecords(List<Application_Request__c> appRequestList, Map<Id,Application_Request__c> arOldMap) {

        Map<Id, Application_Request__c> arUpdatedMap = new Map<Id, Application_Request__c>();
        for (Application_Request__c ar : appRequestList) {
            if (ar.Sales_Stage__c != arOldMap.get(ar.Id).Sales_Stage__c) {
                arUpdatedMap.put(ar.Id, ar);
            }
        }

        if (arUpdatedMap.size() > 0) {

            Map<Id, Id> arToOpptyMap = new Map<Id, Id>();
            List<FleetEnrollment__c> feUpdateList = new List<FleetEnrollment__c>();

            for (Application_Request__c ar : arUpdatedMap.values()) {
                arToOpptyMap.put(ar.Opportunity__c, ar.Id);
            }

            for (FleetEnrollment__c fe : [
                    SELECT Id, Opportunity__c, Opportunity_Number__c, Application_Request__c, Debug_Application_Parameter__c
                    FROM FleetEnrollment__c
                    WHERE Opportunity__c IN :arToOpptyMap.keySet()])
            {
                feUpdateList.add(fe);
            }

            if (feUpdateList.size() > 0 ) {
                for (FleetEnrollment__c fe : feUpdateList) {
                    if (fe.Opportunity_Number__c == null) {
                        fe.Opportunity_Number__c = arUpdatedMap.get(arToOpptyMap.get(fe.Opportunity__c)).Siebel_Oppty__c;
                    }
                    if (fe.Application_Request__c == null) {
                        fe.Application_Request__c = arToOpptyMap.get(fe.Opportunity__c);
                    }
                    if (fe.Debug_Application_Parameter__c == null) {
                        fe.Debug_Application_Parameter__c = arToOpptyMap.get(fe.Opportunity__c);
                    }
                }

                try {
                    upsert feUpdateList;
                } catch (DmlException e) {
                    System.debug('Error Inserting FleetEnrollment Records: ' + e.getMessage());
                }
            }
        }
    }

}