src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>App_Submitted_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>App Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>External_Referring_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the referral information from the opportunity</description>
        <label>External Referring Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Requests (External Referring Contact)</relationshipLabel>
        <relationshipName>Application_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fleet_Size__c</fullName>
        <formula>Opportunity__r.Fleet_Size__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Fleet Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sales_Stage__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_MyApplications.cls
@isTest
private class Test_MyApplications {
    
    @isTest static void testMyapplications() {
        
        
        List<Account> a = utestdata.getAccounts(1);
        insert a;
        List<Contact> c = utestdata.getcontacts(a);
        insert c;

        Id profileId = [select Id from Profile where UserType in ('PowerPartner') AND UserLicense.Name = 'Partner Community' LIMIT 1].Id;

        User u = utestdata.getuserrecord(profileId);
        u.ContactId = c[0].Id;
        insert u;

        system.debug('in AR Test: ' + u.Id + ' ' + u.ContactId);

        List<Opportunity> o = UTestData.getOpportunities(a);
        o[0].stagename = '5) Signed';
        o[0].Fleet_Size__c = 10;
        insert o;

        //system.runas(u)
        //{
            Application_Request__c ar = new Application_Request__c();
            ar.Opportunity__c = o[0].Id;
            ar.App_Submitted_Date__c = system.now().date();
            ar.Sales_Stage__c = 'test';
            ar.External_Referring_Contact__c = c[0].Id;
            insert ar;


            ar.External_Referring_Contact__c = c[0].Id;
            update ar;
        //}
        

        
        test.starttest();

        system.runas(u)
        {
            PageReference pageRef = Page.MyApplications;
            Test.setCurrentPage(pageRef);
            MyApplicationsController mac = new MyApplicationsController();
            
        }
        
        test.stoptest();

        system.assertEquals([Select count() from Application_Request__c Where External_Referring_Contact__c = :u.ContactId],1);

    }

    
}