src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Campaign_Program__c</fullName>
        <formula>Opportunity__r.Program_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decline_Letter_Types__c</fullName>
        <label>Decline Letter Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-Standard</fullName>
                </value>
                <value>
                    <fullName>1-Daily</fullName>
                </value>
                <value>
                    <fullName>2-Tri</fullName>
                </value>
                <value>
                    <fullName>3-Weekly</fullName>
                </value>
                <value>
                    <fullName>4-5th</fullName>
                </value>
                <value>
                    <fullName>5-Dep/Loc</fullName>
                </value>
                <value>
                    <fullName>6-Financials Requested</fullName>
                </value>
                <value>
                    <fullName>7-PG Requested</fullName>
                </value>
                <value>
                    <fullName>Declined Application</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fraud_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fraud Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Opportunity__r.Program_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityAssignment.cls
public with sharing class OpportunityAssignment {

    @InvocableMethod(label='Opportunity Assignment Handler')
    public static void applicationRequestDeniedHandler(List<Application_Request__c> deniedApplicationRequests) {

        List<Application_Request__c> criteriaMetApplicationRequests = new List<Application_Request__c>();
        List<String> allRoles = new List<String>();
        List<Id> allOpportunityIds = new List<Id>();

        for (Application_Request__c applicationRequest : [
                SELECT Id,Opportunity__c,Decline_Letter_Types__c, Fraud_Flag__c, Opportunity__r.Campaign_Program__r.Program__r.Opportunity_Role_Assignment__c,Opportunity__r.Opportunity_Number__c, Opportunity__r.Campaign_Program__r.Program__r.Enable_Opportunity_Auto_Assignment__c, Opportunity__r.Owner.Alias, Opportunity__r.StageName
                FROM application_request__c
                WHERE id IN :new Map<Id, SObject>(deniedApplicationRequests).keySet()
        ]) {

            if (applicationRequest.Opportunity__c != null && applicationRequest.Opportunity__r.Campaign_Program__c != null && applicationRequest.Opportunity__r.Campaign_Program__r.Program__c != null) {

                Boolean autoAssignmentEnabled = applicationRequest.Opportunity__r.Campaign_Program__r.Program__r.Enable_Opportunity_Auto_Assignment__c;
                if (autoAssignmentEnabled) {

                    Boolean opportunityOwnerIsIntegrations = applicationRequest.Opportunity__r.owner.alias == 'sinte';
                    Boolean notDeclinedAppLetterType = applicationRequest.Decline_Letter_Types__c != 'Declined Application';
                    Boolean opportunityStageSigned = applicationRequest.Opportunity__r.StageName == '5) Signed';
                    Boolean fraudCheckFalse = applicationRequest.Fraud_Flag__c == false;

                    if (opportunityOwnerIsIntegrations && notDeclinedAppLetterType && opportunityStageSigned && fraudCheckFalse) {
                        criteriaMetApplicationRequests.add(applicationRequest);
                        // TODO Figure out how to handle empty Opportunity_Role_Assignment__c
                        allRoles.add(applicationRequest.Opportunity__r.Campaign_Program__r.Program__r.Opportunity_Role_Assignment__c);
                        allOpportunityIds.add(applicationRequest.Opportunity__c);
                    }
                }
            }
        }
        if (!criteriaMetApplicationRequests.isEmpty()) {
            opportunityAssignments(criteriaMetApplicationRequests, allRoles, allOpportunityIds);
        }
    }

    private static void opportunityAssignments(List<Application_Request__c> applicationRequests, List<String> allRoles, List<Id> allOpportunityIds) {
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        Map<String, List<User>> userRoleMap = new Map<String, List<User>>();

        // Get all needed user roles/users in a map where the key is the role.
        for (User user : [
                SELECT Id, Name, UserRole.Name
                FROM User
                WHERE UserRole.Name IN :allRoles AND IsActive = true
                order by Name ASC
        ]) {

            if (userRoleMap.get(user.UserRole.Name) == null) {
                userRoleMap.put(user.UserRole.Name, new List<User>());
            }

            userRoleMap.get(user.UserRole.Name).add(user);
        }

        // Get all needed opportunities
        Map<Id, Opportunity> opportunityMap = new Map<Id, Opportunity>([ SELECT Id, OwnerId, Opportunity_Number__c, Campaign_Program__r.Program__r.Opportunity_Role_Assignment__c FROM Opportunity WHERE Id IN :allOpportunityIds]);

        for (Application_Request__c applicationRequest : applicationRequests) {

            Opportunity opportunity = opportunityMap.get(applicationRequest.Opportunity__c);
            List<User> roleUsers = userRoleMap.get(opportunity.Campaign_Program__r.Program__r.Opportunity_Role_Assignment__c);

            Integer optNumber = Integer.valueOf(opportunity.Opportunity_Number__c.substringAfter('-'));

            optNumber = Math.mod(optNumber, roleUsers.size());
            opportunity.OwnerId = roleUsers[optNumber].Id;

            opportunitiesToUpdate.add(opportunity);
        }
        update opportunitiesToUpdate;
    }
}