src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Forward_Application_to_Credit__c</fullName>
        <label>Forward Application to Credit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Request</label>
        <referenceTo>Application_Request__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debug_Application_Parameter__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Debug Application Parameter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/AppRequestAfterInsertTriggerHandler.cls
/**
 * Created by mfarrell on 2019-09-07.
 */

public class AppRequestAfterInsertTriggerHandler extends TriggerHandlerBase {

    public override void mainEntry(TriggerParameters tp) {

        afterInsertFleetEnrollmentUpdate((List<Application_Request__c>) tp.newList);

        afterInsertAppReqToCreditDecisionEngine((List<Application_Request__c>) tp.newList);

    }

    private static void afterInsertFleetEnrollmentUpdate (List<Application_Request__c> appRequestList ) {
        Map<Id, Id> arToOpptyMap = new Map<Id, Id>();

        //set app requests to map for opportunity matching
        for (Application_Request__c ar : appRequestList) {
            arToOpptyMap.put(ar.Opportunity__c, ar.Id);
        }

        //check for fleet enrollment record with an opportunity that matches the app request.
        List<FleetEnrollment__c> fleetEnrollments = [SELECT Id, Opportunity__c, Application_Request__c, Debug_Application_Parameter__c FROM FleetEnrollment__c WHERE Opportunity__c IN :arToOpptyMap.keySet()];

        //if we find fleet enrollment records, we want to update them with the app request ID.
        if (fleetEnrollments.size() > 0) {
            List<FleetEnrollment__c> feToUpdate = new List<FleetEnrollment__c>();

            for (FleetEnrollment__c fe : fleetEnrollments) {

                if (fe.Application_Request__c == null) {
                    fe.Application_Request__c = arToOpptyMap.get(fe.Opportunity__c);

                    if (fe.Debug_Application_Parameter__c == null) {
                        fe.Debug_Application_Parameter__c = arToOpptyMap.get(fe.Opportunity__c);
                    }

                    feToUpdate.add(fe);
                }
            }

            if (feToUpdate.size() > 0) {
                try {
                    update feToUpdate;
                } catch (DmlException e) {
                    System.debug('Error Updating FleetEnrollment Records: ' + e.getMessage());
                }
            }
        }

    }

    private static void afterInsertAppReqToCreditDecisionEngine(List<Application_Request__c> appRequestList) {

        Set<Id> arids = AppRequestTriggerDispatcher.appsForCreditDecision;

        for (Application_Request__c ar : appRequestList) {
            if (System.isBatch() == false && System.isFuture() == false && (ar.Forward_Application_to_Credit__c != null && (ar.Forward_Application_to_Credit__c).equals('Yes'))) {
                arids.add(ar.Id);   // pass to a set in the TriggerDispatcher for processing.
                // This is to avoid the possibility of an AfterInsert and AfterUpdate entering the credit engine twice in the same execution.
            }
        }

    }

}