src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Experian_Data__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Experian Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Experian_Premier_Attributes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Experian Premier Attributes</label>
        <length>9000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inquiry_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Inquiry Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_File_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>On File Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PG_High_Credit_Amount__c</fullName>
        <label>PG High Credit Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Running_Credit_Decisioning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Running Credit Decisioning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Security_Statement_on_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Security Statement on Report</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CP_Application_Request__c.object
<CustomObject>
    <description>Corporate Payments BOCA application request</description>
    <fields>
        <fullName>Experian_Data__c</fullName>
        <description>All data from the Experian response, save the FICO score, is not currently being used and thus being stored all together here.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Experian Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Experian_Premier_Attributes__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Experian Premier Attributes</label>
        <length>9000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Guarantor_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Residential Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>US_States</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inquiry_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Inquiry Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_File_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>On File Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PG_High_Credit_Amount__c</fullName>
        <label>PG High Credit Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Running_Credit_Decisioning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Running Credit Decisioning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Security_Statement_on_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Security Statement on Report</label>
        <type>Checkbox</type>
    </fields>
    <label>CorporatePayments Application Request</label>
    <nameField>
        <displayFormat>Application-{YYYY}{MM}{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CorporatePayments Application Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>AO_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Home Address</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_Date_of_Birth__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter date of birth in MM/DD/YYYY format.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AO_Home_Phone_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Home phone will be called in case of emergency.</inlineHelpText>
        <label>Home Phone #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AO_Social_Security_Number__c</fullName>
        <label>Social Security #</label>
        <length>9</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>AO_State__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AO_Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AO_Zip_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Experian_Data__c</fullName>
        <description>All data from the Experian response, save the FICO score, is not currently being used and thus being stored all together here.</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Experian Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Experian_Premier_Attributes__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Experian Premier Attributes</label>
        <length>9000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inquiry_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Inquiry Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_File_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>On File Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PG_High_Credit_Amount__c</fullName>
        <label>PG High Credit Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PG_Score__c</fullName>
        <description>Consumer FICO Score for Personal Guarantor</description>
        <label>PG FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Running_Credit_Decisioning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Running Credit Decisioning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Security_Statement_on_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Security Statement on Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type_of_Business__c</fullName>
        <inlineHelpText>Type of business organization your individual or group is formed as.</inlineHelpText>
        <label>Type of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Bank/Bank Holding Co/Credit Union</fullName>
                </value>
                <value>
                    <fullName>Federal/State/Local Government Agency or Authority</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Investment Company/Adviser</fullName>
                </value>
                <value>
                    <fullName>Non-Statutory Trust</fullName>
                </value>
                <value>
                    <fullName>Public Accounting Firm</fullName>
                </value>
                <value>
                    <fullName>Public Company and Majority Owned Affiliate</fullName>
                </value>
                <value>
                    <fullName>Unincorporated Association</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/globalValueSets/US_States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NC</fullName>
    </customValue>
    <customValue>
        <fullName>ND</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <masterLabel>US States</masterLabel>
</GlobalValueSet>

src/classes/ExperianIntegrationButton.cls
/**
 * Created by lhowland on 7/24/2018.
 */

global with sharing class ExperianIntegrationButton {

    public class CustomException extends Exception {}
    
    webService static void requestExperianScore(Id appId) {

        String objectType = appID.getSobjectType().getDescribe().getName();

        if (objectType.equalsIgnoreCase('OnlineApplication__c')) {

            System.debug('Online App ID: ' + appID);
            List<OnlineApplication__c> appInfo = [
                    SELECT Id, Contact_First_Name__c, Contact_Last_Name__c, Contact_Name__c, AO_Address__c, AO_City__c, AO_State__c, AO_Zip_Code__c, AO_Home_Phone_Number__c,
                            AO_Date_of_Birth__c, AO_Social_Security_Number__c, Type_of_Business__c, PG_Score__c, Experian_Data__c, Experian_Premier_Attributes__c, PG_High_Credit_Amount__c,
                            Inquiry_Address_High_Risk__c, Security_Statement_on_Report__c, On_File_Address_High_Risk__c
                    FROM OnlineApplication__c
                    where Id = :appID
            ];

            CreditWS_Experian.ExperianRequest experianRequest = new CreditWS_Experian.ExperianRequest();
            OnlineApplication__c app = null;

            try {
                if (appInfo.size() == 1) {
                    app = appInfo[0];
                    experianRequest.socialSecurityNumber = app.AO_Social_Security_Number__c;
                    if (null == app.Contact_First_Name__c && null == app.Contact_Last_Name__c && null != app.Contact_Name__c) {
                        experianRequest.contactFirstName = (app.Contact_Name__c).split(' ')[0];
                        experianRequest.contactLastName = (app.Contact_Name__c).split(' ')[1];
                    } else {
                        experianRequest.contactFirstName = app.Contact_First_Name__c;
                        experianRequest.contactLastName = app.Contact_Last_Name__c;
                    }
                    experianRequest.address = app.AO_Address__c;
                    experianRequest.city = app.AO_City__c;
                    experianRequest.state = app.AO_State__c;
                    experianRequest.zipCode = app.AO_Zip_Code__c;
                    experianRequest.phone = app.AO_Home_Phone_Number__c;
                    experianRequest.dateOfBirthMonth = String.valueOf(app.AO_Date_of_Birth__c.month()).leftPad(2).replace(' ', '0');
                    experianRequest.dateOfBirthDay = String.valueOf(app.AO_Date_of_Birth__c.day()).leftPad(2).replace(' ', '0');
                    experianRequest.dateOfBirthYear = String.valueOf(app.AO_Date_of_Birth__c.year());

                    if (null != app.Type_of_Business__c && (app.Type_of_Business__c.equals('Sole Proprietorship') || app.Type_of_Business__c.equals('Partnership'))) {
                        experianRequest.accountPurposeCode = '10';
                    } else {
                        experianRequest.accountPurposeCode = '5J';
                    }
                }

                CreditWS_Experian.ExperianResponse experianResponse = CreditWS_Experian.getCreditScore((experianRequest));
                System.debug('FICO Score ----------' + experianResponse.creditScore);
                appInfo[0].PG_Score__c = experianResponse.creditScore;
                appInfo[0].Experian_Data__c = experianResponse.experianData;
                appInfo[0].Experian_Premier_Attributes__c = experianResponse.premierAtrributes;
                appInfo[0].PG_High_Credit_Amount__c = experianResponse.pgHighCredit;
                appInfo[0].Inquiry_Address_High_Risk__c = experianResponse.inquiryAddressHighRisk;
                appInfo[0].Security_Statement_on_Report__c = experianResponse.securityStatement;
                appInfo[0].On_File_Address_High_Risk__c = experianResponse.onFileAddressHighRisk;

                upsert appInfo[0];

                // Make a safe copy so we don't overwrite any fields
                appInfo = [SELECT Id, Running_Credit_Decisioning__c FROM OnlineApplication__c WHERE Id = :appID];

                if(appInfo.size() > 0) {

                    // Flag the Credit Decision Engine as not running
                    appInfo[0].Running_Credit_Decisioning__c = false;

                    upsert appInfo[0];
                }
            } catch (Exception e) {
                System.debug('No credit info found for application id: ' + appId);
            }
        }

        else if (objectType.equalsIgnoreCase('CP_Application_Request__c')) {

            System.debug('Corporate Payments App ID: ' + appID);
            List<CP_Application_Request__c> appInfo = [
                    SELECT Id, Guarantor_First_Name__c, Guarantor_Last_Name__c, Guarantor_Residential_Address__c, Guarantor_Residential_City__c, Guarantor_Residential_State__c,
                            Guarantor_Residential_Postal_Code__c, Guarantor_Residential_Phone__c, Guarantor_Date_of_Birth__c, Guarantor_Social_Security_Number__c,
                            Legal_Structure__c, PG_FICO_Score__c, Experian_Data__c, Inquiry_Address_High_Risk__c, Security_Statement_on_Report__c, On_File_Address_High_Risk__c
                    FROM CP_Application_Request__c
                    where Id = :appID
            ];

            CreditWS_Experian.ExperianRequest experianRequest = new CreditWS_Experian.ExperianRequest();
            CP_Application_Request__c app = null;

            try {
                if (appInfo.size() == 1) {
                    app = appInfo[0];
                    experianRequest.socialSecurityNumber = app.Guarantor_Social_Security_Number__c;
                    experianRequest.contactFirstName = app.Guarantor_First_Name__c;
                    experianRequest.contactLastName = app.Guarantor_Last_Name__c;
                    experianRequest.address = app.Guarantor_Residential_Address__c;
                    experianRequest.city = app.Guarantor_Residential_City__c;
                    experianRequest.state = app.Guarantor_Residential_State__c;
                    experianRequest.zipCode = app.Guarantor_Residential_Postal_Code__c;
                    experianRequest.phone = app.Guarantor_Residential_Phone__c;
                    experianRequest.dateOfBirthMonth = String.valueOf(app.Guarantor_Date_of_Birth__c.month()).leftPad(2).replace(' ', '0');
                    experianRequest.dateOfBirthDay = String.valueOf(app.Guarantor_Date_of_Birth__c.day()).leftPad(2).replace(' ', '0');
                    experianRequest.dateOfBirthYear = String.valueOf(app.Guarantor_Date_of_Birth__c.year());

                    if (null != app.Legal_Structure__c && (app.Legal_Structure__c.equals('Sole Proprietorship') || app.Legal_Structure__c.equals('Partnership'))) {
                        experianRequest.accountPurposeCode = '10';
                    } else {
                        experianRequest.accountPurposeCode = '5J';
                    }
                }

                CreditWS_Experian.ExperianResponse experianResponse = CreditWS_Experian.getCreditScore((experianRequest));
                System.debug('FICO Score ----------' + experianResponse.creditScore);
                appInfo[0].PG_FICO_Score__c = experianResponse.creditScore;
                appInfo[0].Experian_Data__c = experianResponse.experianData;
                appInfo[0].Experian_Premier_Attributes__c = experianResponse.premierAtrributes;
                appInfo[0].PG_High_Credit_Amount__c = experianResponse.pgHighCredit;
                appInfo[0].Inquiry_Address_High_Risk__c = experianResponse.inquiryAddressHighRisk;
                appInfo[0].Security_Statement_on_Report__c = experianResponse.securityStatement;
                appInfo[0].On_File_Address_High_Risk__c = experianResponse.onFileAddressHighRisk;

                upsert appInfo[0];

                // Make a safe copy so we don't overwrite any fields
                appInfo = [SELECT Id, Running_Credit_Decisioning__c FROM CP_Application_Request__c WHERE Id = :appID];

                if(appInfo.size() > 0) {

                    // Flag the Credit Decision Engine as not running
                    appInfo[0].Running_Credit_Decisioning__c = false;

                    upsert appInfo[0];
                }
            } catch (Exception e) {
                System.debug('No credit info found for application id: ' + appId);
                //   throw new CustomException('No credit info found for application id: ' + appId);
            }
        }
        else if (objectType.equalsIgnoreCase('Application_Request__c')) {

            System.debug('NA Fleet App ID: ' + appID);
            List<Application_Request__c> appInfo = [
                    SELECT Id, Personal_Guarantor_First_Name__c, Personal_Guarantor_Last_Name__c, Personal_Guarantor_Mailing_Street__c, Personal_Guarantor_Mailing_City__c, Personal_Guarantor_Mailing_State__c,
                            Personal_Guarantor_Mailing_Zip__c, Personal_Guarantor_Home_Phone__c, Personal_Guarantor_DOB__c, Personal_Guarantor_SSN__c,
                            Legal_Structure__c, PG_FICO_Score__c, Experian_Data__c, Experian_Premier_Attributes__c, Experian_Premier_Attribute_Codes__c, PG_High_Credit_Amount__c, Inquiry_Address_High_Risk__c, Security_Statement_on_Report__c, On_File_Address_High_Risk__c
                    FROM Application_Request__c
                    where Id = :appID
            ];

            CreditWS_Experian.ExperianRequest experianRequest = new CreditWS_Experian.ExperianRequest();
            Application_Request__c app = null;

            try {
                if (appInfo.size() == 1) {
                    app = appInfo[0];
                    experianRequest.socialSecurityNumber = app.Personal_Guarantor_SSN__c;
                    experianRequest.contactFirstName = app.Personal_Guarantor_First_Name__c;
                    experianRequest.contactLastName = app.Personal_Guarantor_Last_Name__c;
                    experianRequest.address = app.Personal_Guarantor_Mailing_Street__c;
                    experianRequest.city = app.Personal_Guarantor_Mailing_City__c;
                    experianRequest.state = app.Personal_Guarantor_Mailing_State__c;
                    experianRequest.zipCode = app.Personal_Guarantor_Mailing_Zip__c;
                    experianRequest.phone = app.Personal_Guarantor_Home_Phone__c;
                    experianRequest.dateOfBirthMonth = String.valueOf(app.Personal_Guarantor_DOB__c.month()).leftPad(2).replace(' ', '0');
                    experianRequest.dateOfBirthDay = String.valueOf(app.Personal_Guarantor_DOB__c.day()).leftPad(2).replace(' ', '0');
                    experianRequest.dateOfBirthYear = String.valueOf(app.Personal_Guarantor_DOB__c.year());

                    if (app.Legal_Structure__c.equals('Sole Proprietorship') || app.Legal_Structure__c.equals('Partnership')) {
                        experianRequest.accountPurposeCode = '10';
                    } else {
                        experianRequest.accountPurposeCode = '5J';
                    }
                }

                CreditWS_Experian.ExperianResponse experianResponse = CreditWS_Experian.getCreditScore((experianRequest));
                System.debug('FICO Score ----------' + experianResponse.creditScore);
                appInfo[0].PG_FICO_Score__c = experianResponse.creditScore;
                appInfo[0].Experian_Data__c = experianResponse.experianData;
                appInfo[0].Experian_Premier_Attributes__c = experianResponse.premierAtrributes;
                appInfo[0].Experian_Premier_Attribute_Codes__c = experianResponse.premierAttributeCodes;
                appInfo[0].PG_High_Credit_Amount__c = experianResponse.pgHighCredit;
                appInfo[0].Inquiry_Address_High_Risk__c = experianResponse.inquiryAddressHighRisk;
                appInfo[0].Security_Statement_on_Report__c = experianResponse.securityStatement;
                appInfo[0].On_File_Address_High_Risk__c = experianResponse.onFileAddressHighRisk;

                upsert appInfo[0];

                // Make a safe copy so we don't overwrite any fields
                appInfo = [SELECT Id, Running_Credit_Decisioning__c FROM Application_Request__c WHERE Id = :appID];

                if(appInfo.size() > 0) {

                    // Flag the Credit Decision Engine as not running
                    appInfo[0].Running_Credit_Decisioning__c = false;

                    upsert appInfo[0];
                }
            } catch (Exception e) {
                System.debug('No credit info found for application id: ' + appId);
                //   throw new CustomException('No credit info found for application id: ' + appId);
            }
        }
    }

}