src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>PG_Data__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>PG Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PG_High_Credit_Amount__c</fullName>
        <label>PG High Credit Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PG_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Running_Credit_Decisioning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Running Credit Decisioning</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CP_Application_Request__c.object
<CustomObject>
    <description>Corporate Payments BOCA application request</description>
    <fields>
        <fullName>Guarantor_Date_of_Birth__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Guarantor_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Residential Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_Residential_Postal_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Guarantor_State_Province__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Guarantor_Country__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>NB</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>NT</fullName>
                </value>
                <value>
                    <fullName>NS</fullName>
                </value>
                <value>
                    <fullName>NU</fullName>
                </value>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>PE</fullName>
                </value>
                <value>
                    <fullName>QC</fullName>
                </value>
                <value>
                    <fullName>SK</fullName>
                </value>
                <value>
                    <fullName>YT</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PG_Data__c</fullName>
        <description>All data from the Experian response, save the FICO score, is not currently being used and thus being stored all together here.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>PG Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PG_High_Credit_Amount__c</fullName>
        <label>PG High Credit Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PG_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Running_Credit_Decisioning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Running Credit Decisioning</label>
        <type>Checkbox</type>
    </fields>
    <label>CorporatePayments Application Request</label>
    <nameField>
        <displayFormat>Application-{YYYY}{MM}{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CorporatePayments Application Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>AO_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Home Address</label>
        <length>45</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_Date_of_Birth__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter date of birth in MM/DD/YYYY format.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AO_Home_Phone_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Home phone will be called in case of emergency.</inlineHelpText>
        <label>Home Phone #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AO_Social_Security_Number__c</fullName>
        <label>Social Security #</label>
        <length>9</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>AO_State__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>AO_Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AO_Zip_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contact Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PG_Data__c</fullName>
        <description>All data from the PG credit bureau response</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>PG Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PG_High_Credit_Amount__c</fullName>
        <label>PG High Credit Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PG_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PG_Score__c</fullName>
        <description>Consumer FICO Score for Personal Guarantor</description>
        <label>PG FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Running_Credit_Decisioning__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Running Credit Decisioning</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type_of_Business__c</fullName>
        <inlineHelpText>Type of business organization your individual or group is formed as.</inlineHelpText>
        <label>Type of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Bank/Bank Holding Co/Credit Union</fullName>
                </value>
                <value>
                    <fullName>Federal/State/Local Government Agency or Authority</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Investment Company/Adviser</fullName>
                </value>
                <value>
                    <fullName>Non-Statutory Trust</fullName>
                </value>
                <value>
                    <fullName>Public Accounting Firm</fullName>
                </value>
                <value>
                    <fullName>Public Company and Majority Owned Affiliate</fullName>
                </value>
                <value>
                    <fullName>Unincorporated Association</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreditUtilQueueable_EquifaxPG.cls
/*
*
* Credit Decisioning Queueable
* Module: Experian PG Callouts
* Author: Derek Gilbert
* Initial Date: 3/26/2018
*
*/
public class CreditUtilQueueable_EquifaxPG implements Queueable, Database.AllowsCallouts {

    private ID applicationId;

    public CreditUtilQueueable_EquifaxPG(Id applicationId) {

        this.applicationId = applicationId;

    }

    public void execute(QueueableContext context) {

        String objectType = (Id.valueOf(applicationId)).getSobjectType().getDescribe().getName();

        if (objectType != null && (objectType).equalsIgnoreCase('OnlineApplication__c')) {

            List<OnlineApplication__c> onlineApplications = [
                    SELECT Id, Contact_First_Name__c, Contact_Last_Name__c, AO_Address__c, AO_City__c,
                            AO_State__c, AO_Zip_Code__c, AO_Date_of_Birth__c, AO_Social_Security_Number__c, AO_Home_Phone_Number__c,
                            Running_Credit_Decisioning__c, PG_Required__c, Type_of_Business__c, PG_Score__c, PG_High_Credit_Amount__c, PG_Data__c
                    FROM OnlineApplication__c
                    WHERE Id = :applicationId
            ];

            if (onlineApplications.size() == 1) {

                OnlineApplication__c onlineApplication = onlineApplications[0];

                onlineApplication.Running_Credit_Decisioning__c = true;

                if (onlineApplication.PG_Required__c) {

                    CreditWS_Equifax.EquifaxRequest equifaxRequest = new CreditWS_Equifax.EquifaxRequest();

                    equifaxRequest.socialInsuranceNumber = onlineApplication.AO_Social_Security_Number__c;
                    if(null == onlineApplication.Contact_First_Name__c && null == onlineApplication.Contact_Last_Name__c && null != onlineApplication.Contact_Name__c) {
                        equifaxRequest.firstName = (onlineApplication.Contact_Name__c).split(' ')[0];
                        equifaxRequest.lastName = (onlineApplication.Contact_Name__c).split(' ')[1];
                    }
                    else {
                        equifaxRequest.firstName = onlineApplication.Contact_First_Name__c;
                        equifaxRequest.lastName = onlineApplication.Contact_Last_Name__c;
                    }
                    equifaxRequest.address = onlineApplication.AO_Address__c;
                    equifaxRequest.city = onlineApplication.AO_City__c;
                    equifaxRequest.province = onlineApplication.AO_State__c;
                    equifaxRequest.postalCode = onlineApplication.AO_Zip_Code__c;
                    equifaxRequest.phone = onlineApplication.AO_Home_Phone_Number__c;
                    if (onlineApplication.AO_Date_of_Birth__c != null) {
                        equifaxRequest.dateOfBirthMonth = String.valueOf(onlineApplication.AO_Date_of_Birth__c.month()).leftPad(2).replace(' ', '0');
                        equifaxRequest.dateOfBirthDay = String.valueOf(onlineApplication.AO_Date_of_Birth__c.day()).leftPad(2).replace(' ', '0');
                        equifaxRequest.dateOfBirthYear = String.valueOf(onlineApplication.AO_Date_of_Birth__c.year());
                    }

                    CreditWS_Equifax.EquifaxResponse equifaxResponse = CreditWS_Equifax.getCreditScore((equifaxRequest));

                    if (equifaxResponse != null) {
                        onlineApplication.PG_Score__c = equifaxResponse.creditScore;
                        onlineApplication.PG_Data__c = equifaxResponse.equifaxData;
                        onlineApplication.PG_High_Credit_Amount__c = equifaxResponse.pgHighCredit;
                    }
                    else if (equifaxResponse == null || equifaxResponse.calloutFailed){
                        System.debug('Equifax callout failed. Response: ' + equifaxResponse);
                    }
                }

                upsert onlineApplication;

                // Make a safe copy so we don't overwrite any fields
                onlineApplications = [SELECT Id, Running_Credit_Decisioning__c FROM OnlineApplication__c WHERE Id = :applicationId LIMIT 1];

                if(onlineApplications.size() > 0) {

                    // Flag the Credit Decision Engine as not running
                    onlineApplications[0].Running_Credit_Decisioning__c = false;

                    upsert onlineApplications;
                }
            }
        }
        else if (objectType != null && (objectType).equalsIgnoreCase('CP_Application_Request__c')) {

            List<CP_Application_Request__c> cpApplications = [
                    SELECT Id, Guarantor_First_Name__c, Guarantor_Last_Name__c, Guarantor_Residential_Address__c, Guarantor_Residential_City__c,
                            Guarantor_State_Province__c, Guarantor_Residential_Postal_Code__c, Guarantor_Date_of_Birth__c, Guarantor_Social_Security_Number__c, Guarantor_Residential_Phone__c,
                            Running_Credit_Decisioning__c, PG_Required__c, Legal_Structure__c, PG_FICO_Score__c, PG_High_Credit_Amount__c, PG_Data__c
                    FROM CP_Application_Request__c
                    WHERE Id = :applicationId
            ];

            if (cpApplications.size() == 1) {

                CP_Application_Request__c cpApplicant = cpApplications[0];

                cpApplicant.Running_Credit_Decisioning__c = true;

                if (cpApplicant.PG_Required__c) {

                    CreditWS_Equifax.EquifaxRequest equifaxRequest = new CreditWS_Equifax.EquifaxRequest();

                    equifaxRequest.socialInsuranceNumber = cpApplicant.Guarantor_Social_Security_Number__c;
                    equifaxRequest.firstName = cpApplicant.Guarantor_First_Name__c;
                    equifaxRequest.lastName = cpApplicant.Guarantor_Last_Name__c;
                    equifaxRequest.address = cpApplicant.Guarantor_Residential_Address__c;
                    equifaxRequest.city = cpApplicant.Guarantor_Residential_City__c;
                    equifaxRequest.province = cpApplicant.Guarantor_State_Province__c;
                    equifaxRequest.postalCode = cpApplicant.Guarantor_Residential_Postal_Code__c;
                    equifaxRequest.phone = cpApplicant.Guarantor_Residential_Phone__c;
                    if (cpApplicant.Guarantor_Date_of_Birth__c != null) {
                        equifaxRequest.dateOfBirthMonth = String.valueOf(cpApplicant.Guarantor_Date_of_Birth__c.month()).leftPad(2).replace(' ', '0');
                        equifaxRequest.dateOfBirthDay = String.valueOf(cpApplicant.Guarantor_Date_of_Birth__c.day()).leftPad(2).replace(' ', '0');
                        equifaxRequest.dateOfBirthYear = String.valueOf(cpApplicant.Guarantor_Date_of_Birth__c.year());
                    }

                    CreditWS_Equifax.EquifaxResponse equifaxResponse = CreditWS_Equifax.getCreditScore((equifaxRequest));

                    if (equifaxResponse != null) {
                        cpApplicant.PG_FICO_Score__c = equifaxResponse.creditScore;
                        cpApplicant.PG_Data__c = equifaxResponse.equifaxData;
                        cpApplicant.PG_High_Credit_Amount__c = equifaxResponse.pgHighCredit;
                    }
                    else if (equifaxResponse == null || equifaxResponse.calloutFailed) {
                        System.debug('Equifax callout failed. Response: ' + equifaxResponse);
                    }
                }

                upsert cpApplicant;

                // Make a safe copy so we don't overwrite any fields
                cpApplications = [SELECT Id, Running_Credit_Decisioning__c FROM CP_Application_Request__c WHERE Id = :applicationId];

                if(cpApplications.size() > 0) {

                    // Flag the Credit Decision Engine as not running
                    cpApplicant.Running_Credit_Decisioning__c = false;

                    upsert cpApplicant;
                }
            }
        }
        else if (objectType != null && (objectType).equalsIgnoreCase('Application_Request__c')) {

            List<Application_Request__c> naApplications = [
                    SELECT Id, Personal_Guarantor_First_Name__c, Personal_Guarantor_Last_Name__c, Personal_Guarantor_Mailing_Street__c, Personal_Guarantor_Mailing_City__c,
                            Personal_Guarantor_Mailing_State__c, Personal_Guarantor_Mailing_Zip__c, Personal_Guarantor_DOB__c, Personal_Guarantor_SSN__c, Personal_Guarantor_Home_Phone__c,
                            Running_Credit_Decisioning__c, PG_Required__c, Legal_Structure__c, PG_FICO_Score__c, PG_Data__c
                    FROM Application_Request__c
                    WHERE Id = :applicationId
            ];

            if (naApplications.size() == 1) {

                Application_Request__c naApplicant = naApplications[0];

                naApplicant.Running_Credit_Decisioning__c = true;

                CreditWS_Equifax.EquifaxRequest equifaxRequest = new CreditWS_Equifax.EquifaxRequest();
                
                equifaxRequest.socialInsuranceNumber = naApplicant.Personal_Guarantor_SSN__c;
                equifaxRequest.firstName = naApplicant.Personal_Guarantor_First_Name__c;
                equifaxRequest.lastName = naApplicant.Personal_Guarantor_Last_Name__c;
                equifaxRequest.address = naApplicant.Personal_Guarantor_Mailing_Street__c;
                equifaxRequest.city = naApplicant.Personal_Guarantor_Mailing_City__c;
                equifaxRequest.province = naApplicant.Personal_Guarantor_Mailing_State__c;
                equifaxRequest.postalCode = naApplicant.Personal_Guarantor_Mailing_Zip__c;
                equifaxRequest.phone = naApplicant.Personal_Guarantor_Home_Phone__c;
                if (naApplicant.Personal_Guarantor_DOB__c != null) {
                    equifaxRequest.dateOfBirthMonth = String.valueOf(naApplicant.Personal_Guarantor_DOB__c.month()).leftPad(2).replace(' ', '0');
                    equifaxRequest.dateOfBirthDay = String.valueOf(naApplicant.Personal_Guarantor_DOB__c.day()).leftPad(2).replace(' ', '0');
                    equifaxRequest.dateOfBirthYear = String.valueOf(naApplicant.Personal_Guarantor_DOB__c.year());
                }
                
                CreditWS_Equifax.EquifaxResponse equifaxResponse = CreditWS_Equifax.getCreditScore((equifaxRequest));
                
                if (equifaxResponse != null) {
                    naApplicant.PG_FICO_Score__c = equifaxResponse.creditScore;
                    naApplicant.PG_Data__c = equifaxResponse.equifaxData;
                    naApplicant.PG_High_Credit_Amount__c = equifaxResponse.pgHighCredit;
                }
                else if (equifaxResponse == null || equifaxResponse.calloutFailed) {
                    System.debug('Equifax callout failed. Response: ' + equifaxResponse);
                }

                upsert naApplicant;

                // Make a safe copy so we don't overwrite any fields
                naApplications = [SELECT Id, Running_Credit_Decisioning__c FROM Application_Request__c WHERE Id = :applicationId];

                if(naApplications.size() > 0) {

                    // Flag the Credit Decision Engine as not running
                    naApplicant.Running_Credit_Decisioning__c = false;

                    upsert naApplicant;
                }
            }
        }
    }
}