src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Campaign_Program__c</fullName>
        <formula>Opportunity__r.Program_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Campaign Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Decline_Letter_Types__c</fullName>
        <label>Decline Letter Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0-Standard</fullName>
                </value>
                <value>
                    <fullName>1-Daily</fullName>
                </value>
                <value>
                    <fullName>2-Tri</fullName>
                </value>
                <value>
                    <fullName>3-Weekly</fullName>
                </value>
                <value>
                    <fullName>4-5th</fullName>
                </value>
                <value>
                    <fullName>5-Dep/Loc</fullName>
                </value>
                <value>
                    <fullName>6-Financials Requested</fullName>
                </value>
                <value>
                    <fullName>7-PG Requested</fullName>
                </value>
                <value>
                    <fullName>Declined Application</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fraud_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Fraud Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <formula>Opportunity__r.Program_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program</label>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityAssignmentTest.cls
@IsTest
public class OpportunityAssignmentTest {

    public static void test_opportunityAutoAssignment() {

        Application_Request__c applicationRequests = [SELECT Id,Opportunity__c,Opportunity__r.Campaign_Program__r.Program__c, Decline_Letter_Types__c, Fraud_Flag__c, Opportunity__r.Campaign_Program__r.Program__r.Opportunity_Role_Assignment__c,Opportunity__r.Opportunity_Number__c, Opportunity__r.Campaign_Program__r.Program__r.Enable_Opportunity_Auto_Assignment__c, Opportunity__r.Owner.Alias, Opportunity__r.StageName FROM Application_Request__c WHERE Opportunity__r.Name = 'Test Oppty 10'];
        Program__c program = [SELECT Id, Enable_Opportunity_Auto_Assignment__c, Opportunity_Role_Assignment__c FROM Program__c WHERE Id = :applicationRequests.Opportunity__r.Campaign_Program__r.Program__c];

        program.Enable_Opportunity_Auto_Assignment__c = true;
        program.Opportunity_Role_Assignment__c = 'System Admin';
        update program;

        Opportunity opportunity = [SELECT Id, OwnerId FROM Opportunity WHERE Id = :applicationRequests.Opportunity__c];
        opportunity.OwnerId = [ SELECT Id FROM User WHERE alias = 'sinte' ].Id;
        update opportunity;

        List<User> users = [
                SELECT Id, Name, UserRole.Name
                FROM User
                WHERE UserRole.Name = 'System Admin'
                AND IsActive = true
                AND Id NOT IN (SELECT UserId FROM OutOfOffice WHERE StartDate <= :System.Now() AND EndDate >= :System.Now())
                order by Name ASC
        ];

        Test.startTest();
        OpportunityAssignment.applicationRequestDeniedHandler(new List<Application_Request__c>{
                applicationRequests
        });
        Test.stopTest();

        opportunity = [SELECT Id, OwnerId FROM Opportunity WHERE Id = :applicationRequests.Opportunity__c];

        // Assert that the proper user was assigned as owner
        System.assertEquals(users[0].id, opportunity.ownerId);

        for (OpportunitySplit opportunitySplit : [
                SELECT Id, SplitAmount, SplitPercentage, SplitOwnerId, Opportunity.OwnerId
                FROM OpportunitySplit
                WHERE OpportunityId = :opportunity.Id
        ]) {
            // Assert that the assigned owner was also given a 100% split
            if (opportunitySplit.SplitOwnerId == opportunitySplit.Opportunity.OwnerId) {
                System.assertEquals(true, opportunitySplit.SplitPercentage == 100);
            } else {
                System.assertEquals(true, opportunitySplit.SplitPercentage == 0);
            }
        }
    }
}