src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                </value>
                <value>
                    <fullName>Adjudication</fullName>
                </value>
                <value>
                    <fullName>Credit Follow-up</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Compliance_Decision__c</fullName>
        <label>Compliance Decision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>External_Referred_by__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the account of the referring contact</description>
        <label>External Referred by</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Application Requests (External Referred by)</relationshipLabel>
        <relationshipName>Application_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>External_Referring_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Captures the referral information from the opportunity</description>
        <label>External Referring Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Requests (External Referring Contact)</relationshipLabel>
        <relationshipName>Application_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fleet_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fleet Enrollment</label>
        <referenceTo>FleetEnrollment__c</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Forward_Application_to_Credit__c</fullName>
        <label>Forward Application to Credit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fraud_Decision__c</fullName>
        <label>Fraud Decision</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Siebel_Oppty__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Siebel Oppty #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Stage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sent to Prospect</fullName>
                </value>
                <value>
                    <fullName>Application Incomplete</fullName>
                </value>
                <value>
                    <fullName>Application Complete</fullName>
                </value>
                <value>
                    <fullName>Pending BOCDD</fullName>
                </value>
                <value>
                    <fullName>Pending Decision</fullName>
                </value>
                <value>
                    <fullName>Decisioned</fullName>
                </value>
                <value>
                    <fullName>Implementation Complete</fullName>
                </value>
                <value>
                    <fullName>Pending Implementation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Request</label>
        <referenceTo>Application_Request__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Debug_Application_Parameter__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Debug Application Parameter</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <formula>Application_Request__r.Sales_Person__r.FirstName &amp; &quot; &quot; &amp; Application_Request__r.Sales_Person__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Person</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Ready For Siebel</fullName>
                </value>
                <value>
                    <fullName>Pending Ready For Siebel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppRequestHelper.cls
/**
 * Created by mfarrell on 2019-09-07.
 *
 */

public class AppRequestHelper {

    public static void appReqBeforeInsert(List<Application_Request__c> appRequestList) {

        Map<Id, Id> arToOpptyMap = new Map<Id, Id>();
        Map<Id, Id> feToOpptyMap = new Map<Id, Id>();

        for (Application_Request__c ar : appRequestList) {
            arToOpptyMap.put(ar.Opportunity__c, ar.Id);
        }

        for (FleetEnrollment__c fe : [SELECT Id, Opportunity__c FROM FleetEnrollment__c WHERE Opportunity__c IN :arToOpptyMap.keySet()]) {
            feToOpptyMap.put(fe.Opportunity__c, fe.Id);
        }

        for (Application_Request__c applicationRequest : appRequestList) {

            if (applicationRequest.Sales_Person__c == null) {
                applicationRequest.Sales_Person__c = UserInfo.getUserId();
            }
            if (applicationRequest.Fleet_Enrollment__c == null && feToOpptyMap.size() > 0) {
                applicationRequest.Fleet_Enrollment__c = feToOpptyMap.get(applicationRequest.Opportunity__c);
            }
        }
    }

    public static void updateRelatedFERecords(List<Application_Request__c> appRequestList, Map<Id,Application_Request__c> arOldMap) {

        Map<Id, Application_Request__c> arUpdatedMap = new Map<Id, Application_Request__c>();
        for (Application_Request__c ar : appRequestList) {
            if (ar.Siebel_Oppty__c != arOldMap.get(ar.Id).Siebel_Oppty__c) {
                arUpdatedMap.put(ar.Id, ar);
            }
        }

        if (arUpdatedMap.size() > 0) {

            Map<Id, Id> arToOpptyMap = new Map<Id, Id>();
            List<FleetEnrollment__c> feUpdateList = new List<FleetEnrollment__c>();

            for (Application_Request__c ar : arUpdatedMap.values()) {
                arToOpptyMap.put(ar.Opportunity__c, ar.Id);
            }

            for (FleetEnrollment__c fe : [
                    SELECT Id, Opportunity__c, Opportunity_Number__c, Application_Request__c, Debug_Application_Parameter__c
                    FROM FleetEnrollment__c
                    WHERE Opportunity__c IN :arToOpptyMap.keySet()])
            {
                feUpdateList.add(fe);
            }

            if (feUpdateList.size() > 0 ) {
                for (FleetEnrollment__c fe : feUpdateList) {
                    if (fe.Opportunity_Number__c == null) {
                        fe.Opportunity_Number__c = arUpdatedMap.get(arToOpptyMap.get(fe.Opportunity__c)).Siebel_Oppty__c;
                    }
                    if (fe.Application_Request__c == null) {
                        fe.Application_Request__c = arToOpptyMap.get(fe.Opportunity__c);
                    }
                    if (fe.Debug_Application_Parameter__c == null) {
                        fe.Debug_Application_Parameter__c =arToOpptyMap.get(fe.Opportunity__c);
                    }
                }

                try {
                    upsert feUpdateList;
                } catch (DmlException e) {
                    System.debug('Error Inserting FleetEnrollment Records: ' + e.getMessage());
                }
            }
        }
    }

    public static void appReqAfterInsertCreditDecision(List<Application_Request__c> appRequestList) {

        for (Application_Request__c applicationRequest : appRequestList) {
            if (System.IsBatch() == false && System.isFuture() == false && applicationRequest.Forward_Application_to_Credit__c != null && (applicationRequest.Forward_Application_to_Credit__c).equals('Yes')) {
                CreditDecisionEngineNA.runNADecisioningProcessFuture(applicationRequest.Id);
            }
        }

    }

    public static void appReqAfterUpdateCreditDecision(List<Application_Request__c> appRequestList, Map<Id,Application_Request__c> arOldMap) {

        for (Application_Request__c applicationRequest : appRequestList) {
            Application_Request__c old = arOldMap.get(applicationRequest.Id);

            if (System.IsBatch() == false && System.isFuture() == false && (old.Forward_Application_to_Credit__c == null || !(old.Forward_Application_to_Credit__c).equalsIgnoreCase('Yes')) && applicationRequest.Forward_Application_to_Credit__c != null && (applicationRequest.Forward_Application_to_Credit__c).equals('Yes')) {
                CreditDecisionEngineNA.runNADecisioningProcessFuture(applicationRequest.Id);
            }

            // if Compliance of Fraud had to make a decision on the application, then decisioing needs to be re-run
            if (System.IsBatch() == false && System.isFuture() == false && ((old.Compliance_Decision__c != null && !(old.Compliance_Decision__c).equalsIgnoreCase(applicationRequest.Compliance_Decision__c)) || (old.Fraud_Decision__c != null && !(old.Fraud_Decision__c).equalsIgnoreCase(applicationRequest.Fraud_Decision__c)))
                    && (applicationRequest.Application_Stage__c).equalsIgnoreCase('Adjudication')
                    && (applicationRequest.Status__c).equalsIgnoreCase('Pending Decision') && CreditDecisionEngineNA.decisionEngineRunning == false) {

                CreditDecisionEngineNA.runNADecisioningProcessFuture(applicationRequest.Id);
            }
        }

    }

    public static void communityUserStampData(List<Application_Request__c> records) {

        // from existing UApplicationRequest Class
        Set<Id> scopeoppIds = new Set<Id>();
        for(Application_Request__c a : records) {
            if(a.Opportunity__c != null) scopeoppIds.add(a.Opportunity__c);
        }

        if(scopeoppIds.isEmpty()) return;

        Map<Id, Opportunity> opps = new Map<Id, Opportunity>([
                SELECT Id, External_Referred_By_Account_Name__c, External_Referred_By__c
                FROM Opportunity
                WHERE Id IN :scopeoppIds
        ]);

        if(opps.isEmpty()) return;

        for(Application_Request__c ar : records) {
            if(!opps.containsKey(ar.Opportunity__c)) continue;

            Opportunity o = opps.get(ar.Opportunity__c);
            ar.External_Referred_by__c = o.External_Referred_By_Account_Name__c;
            ar.External_Referring_Contact__c = o.External_Referred_By__c;

        }

    }
}