src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>SF_Opp__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>SF Opp #</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Stage__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Online_Application_Status__c.object
<CustomObject>
</CustomObject>

src/objects/WeFormObject__c.object
<CustomObject>
    <fields>
        <fullName>Application_Number__c</fullName>
        <formula>Opportunity__r.Opportunity_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Request</label>
        <referenceTo>Application_Request__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Online_Application_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Online Application Status</label>
        <referenceTo>Online_Application_Status__c</referenceTo>
        <relationshipLabel>Online Applications</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WeFormObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeFormObject</label>
        <referenceTo>WeFormObject__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/updateAppStatusTriggerTest2.cls
@isTest(seealldata=true)
private class updateAppStatusTriggerTest2 {

    static testMethod void updateAppStatusApprovedTest() {
    try{
        Application_Request__c arq = new Application_Request__c();          
        
        test.startTest();
        arq.Sales_Stage__c = '06 - Approved';
        arq.SF_Opp__c='O-00194468';
        insert arq;
        //update arq;
        

        WeFormObject__c bocaOpty = [Select Id, Application_Number__c from WeFormObject__c WHERE Application_Number__c = :arq.SF_Opp__c];
        Online_Application_Status__c status=new Online_Application_Status__c();
        status = [select id from Online_Application_Status__c where id='a1Y700000001FkXEAU'];
        //status = [select id from Online_Application_Status__c where id='a1bS00000002CaBIAU'];
        system.assertEquals('06 - Approved', bocaOpty.Online_Application_Status__c);

        test.stopTest();
        }
        catch(Exception ex){
        
        }        
    }    
}