src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Coupon_Code__c</fullName>
        <formula>Opportunity__r.Coupon_Code2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Coupon Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Sales_Person__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Person</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Siebel_Oppty__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Siebel Oppty #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Solicited_Activity_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Solicited Activity Sent</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>General</fullName>
        <active>true</active>
        <label>General</label>
    </recordTypes>
</CustomObject>

src/classes/BOCATaskTriggerHandler.cls
public class BOCATaskTriggerHandler {
    
    public BOCATaskTriggerHandler() {
        
    }
    
    public void sendSolicitedTask(Application_Request__c[] applicationRequests) {
        
        try {
            
            User sinte = [SELECT Id FROM User WHERE Alias = 'sinte'];
            
            User taskOwner = [SELECT Id FROM User WHERE Alias = 'dcred'];
            
            // Itterate over the trigger map
            for (Application_Request__c applicationRequest : applicationRequests) {
                
                System.debug('### DEBUG - Got Application Request: ' + applicationRequest.Id);
                
                System.debug('### DEBUG: ' + applicationRequest.Opportunity__r.OwnerId + ', ' + sinte.Id);
                
                if(applicationRequest.Sales_Person__c != sinte.Id && applicationRequest.Solicited_Activity_Sent__c == false && !String.isEmpty(applicationRequest.Siebel_Oppty__c)) {
                    
                    System.debug('### DEBUG - Application Request (' + applicationRequest.Id + ') has a solicited coupon code: ' + applicationRequest.Coupon_Code__c);
                    
                    Task creditTask = new Task();
                    
                    creditTask.RecordTypeId = [SELECT Id, SobjectType, Name FROM RecordType WHERE Name = 'General' and SobjectType = 'Task' LIMIT 1].Id;
                    creditTask.Subject = 'Solicited Application';
                    creditTask.WhatId = applicationRequest.Opportunity__c;
                    creditTask.Description = 'Solicited Application';
                    creditTask.Status = 'In Progress';
                    creditTask.Priority = '3-Medium';
                    creditTask.Activity_Type__c = 'Solicited';
                    creditTask.Type = 'Solicited';
                    creditTask.ActivityDate = Date.today();
                    creditTask.OwnerId = taskOwner.Id;
                    
                    insert creditTask;
                    
                    System.debug('### DEBUG - Application Request (' + applicationRequest.Id + ') has created a new solicited activity:' + creditTask.Id);
                    
                    applicationRequest.Solicited_Activity_Sent__c = true;
                    
                    System.debug('### DEBUG - Application Request (' + applicationRequest.Id + ') has sent a solicited activity:' + applicationRequest.Solicited_Activity_Sent__c);
                    
                }
                
            }
            
        } catch (Exception e) {
            
            System.debug('An error occured creating the task.. Failing gracefully..');
            
        }
        
    }

}