src/objects/Application_Request__c.object
<CustomObject>
    <description>Fleet application request</description>
    <fields>
        <fullName>Fleet_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Fleet Enrollment</label>
        <referenceTo>FleetEnrollment__c</referenceTo>
        <relationshipLabel>Application Requests</relationshipLabel>
        <relationshipName>Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Siebel_Oppty__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Siebel Oppty #</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Application Request</label>
    <nameField>
        <displayFormat>AR-{000000}</displayFormat>
        <label>Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Request</label>
        <referenceTo>Application_Request__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FleetEnrollmentTriggerHandler.cls
public class FleetEnrollmentTriggerHandler {

    public FleetEnrollmentTriggerHandler() {
        
    }
    
    public void tieToApplicationRequest(FleetEnrollment__c[] newFleetEnrollments) {
        
        for(FleetEnrollment__c fleetEnrollment : newFleetEnrollments) {
            
            if(!String.isEmpty(fleetEnrollment.Opportunity_Number__c)) {
            	List<Application_Request__c> applicationRequests = [SELECT Id FROM Application_Request__c WHERE Siebel_Oppty__c =: fleetEnrollment.Opportunity_Number__c and CreatedDate = LAST_N_DAYS:90];
                
                if(!applicationRequests.isEmpty()) {
                    fleetEnrollment.Application_Request__c = applicationRequests[0].Id;
                }
            }
            else if(String.isEmpty(fleetEnrollment.Opportunity_Number__c) && !String.isEmpty(fleetEnrollment.Application_Request__c)) { 
				List<Application_Request__c> applicationRequests = [SELECT Id, Siebel_Oppty__c FROM Application_Request__c WHERE Id =: fleetEnrollment.Application_Request__c and Siebel_Oppty__c != null];
                
                if(!applicationRequests.isEmpty()) {
                	fleetEnrollment.Opportunity_Number__c = applicationRequests[0].Siebel_Oppty__c;
                }
            }
            
        }
        
    }
    
    // Sorta misleading.. The case doesn't get created until the application is in
    // stage 6.. so we're really telling the Application Request what the enrollment
    // is and then doing a formula from the case.. 
    public void tieToFleetImplementationCase(FleetEnrollment__c[] newFleetEnrollments) {
        
        for(FleetEnrollment__c fleetEnrollment : newFleetEnrollments) {
            
            List<Application_Request__c> appRequests = [SELECT Id, Fleet_Enrollment__c FROM Application_Request__c WHERE Id =: fleetEnrollment.Application_Request__c LIMIT 1];
            
            if(appRequests.size() > 0) {
                appRequests[0].Fleet_Enrollment__c = fleetEnrollment.Id;
            }
            
            upsert appRequests;
            
        }
        
    }
    
}