src/objects/Approval_Process_Locking_Bypass__mdt.object
<CustomObject>
    <fields>
        <fullName>Approval_Process_ID__c</fullName>
        <label>Approval Process ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Bypass__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Bypass</label>
        <type>Checkbox</type>
    </fields>
    <label>Approval Process Locking Bypass</label>
    <pluralLabel>Approval Process Locking Bypass</pluralLabel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/ApprovalProcessHandler.cls
/*
*
* Custom hooks for the SFDC Approval Process
*
 */
public with sharing class ApprovalProcessHandler {

    // Custom setting with approval process bypass
    public static List<Id> exemptProcessDefinitionIds { get; set; }
    
    @future
    public static void unlockRecord(List<Id> targetObjectIds) {

        exemptProcessDefinitionIds = new List<Id>();
        for(Approval_Process_Locking_Bypass__mdt approvalProcessLockingBypass : [SELECT Id, Approval_Process_ID__c FROM Approval_Process_Locking_Bypass__mdt WHERE Enable_Bypass__c = true]) {
            exemptProcessDefinitionIds.add(Id.valueOf(approvalProcessLockingBypass.Approval_Process_ID__c));
        }
        
        for(ProcessInstance processInstance : [SELECT Id, TargetObjectId, ProcessDefinitionId FROM ProcessInstance WHERE Status = 'Pending' and TargetObjectId in :targetObjectIds]) {
            
            if(exemptProcessDefinitionIds.contains(processInstance.ProcessDefinitionId)) { Approval.unlock(processInstance.TargetObjectId); }

        }

    }

}