src/objects/Automation_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Automation Settings</label>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The API name of the Object who&apos;s data will be inserted</description>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Designates the order in which the static resources are loaded into the database.</description>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Required_Fields_Only__c.field-meta.xml
<CustomField>
    <fullName>Required_Fields_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked this data will be inserted as a blank record  without circular  lookup fields populated</description>
    <label>Required Fields Only</label>
    <type>Checkbox</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Static_Resource__c.field-meta.xml
<CustomField>
    <fullName>Static_Resource__c</fullName>
    <description>The name of the Static Resource file where the object&apos;s data should be pulled from</description>
    <label>Static Resource</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/classes/DataLoaderBatchTest.cls
/*
* Test Setup Framework Data Loader Test Class
* Author: Jason Arbegast
* Initial Date: 5/15/2019
* Description:  tests all the hard work of loading data for test setups and post-sandbox refreshes
* Revision History:
*/

@isTest
public class DataLoaderBatchTest {

    /*
    * description: tests DataLoaderBatch class, which is called for test setups
    *       also tests preexecute method in UtilityTestLoader, which will normally be called in a setup method
    */
    public static void testDataLoaderBatch() {

        UtilityTestLoader.preExecute();
        Automation_Settings__c autoSettings = Automation_Settings__c.getOrgDefaults();
        system.assertNotEquals(null, autoSettings);

        // Get the first object in the load list
        Test_Data_Configuration__mdt tdc = [SELECT Object__c, Required_Fields_Only__c, Static_Resource__c, Order__c
        FROM Test_Data_Configuration__mdt
        ORDER BY Order__c ASC LIMIT 1];
        Integer beforeCount = (Integer)Database.query('SELECT COUNT(Id) FROM ' + tdc.Object__c)[0].get('expr0');

        DataLoaderBatch dlb = new DataLoaderBatch();
        dlb.testRunOnly = true;
        Test.startTest();
        Database.executeBatch(dlb);
        Test.stopTest();

        // Assert the first object count went up
        Integer afterCount = (Integer)Database.query('SELECT COUNT(Id) FROM ' + tdc.Object__c)[0].get('expr0');
        System.assert(beforeCount < afterCount, 'DataLoaderBatch did not insert anything. Before count = ' + beforeCount + ' : After count = ' + afterCount);
    }

}