src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>DID_Length__c</fullName>
        <defaultValue>TEXT(4)</defaultValue>
        <label>DID Length</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>4</fullName>
                    <default>true</default>
                    <label>4</label>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>4 OR 6</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountMaintenanceController.cls
public class AccountMaintenanceController {

    public String languageCode { get; set; }
    
    public Id brandingLogo { get; set; }
    
    public BOCA_res__c brandingUtility { get; set; }

    public Program__c program { get; set; }
    
    public String recordId {
        get {
            return ApexPages.currentPage().getParameters().get('recordId');
        }
    }
    
    public String key {
        get {
            return ApexPages.currentPage().getParameters().get('key');
        }
    }
    
    public Boolean isBroken { get; set; }
    
    public String didLength { get; set; }
    
    public void init() {
        
        isBroken = false;
        
        if(!String.isEmpty(recordId)) {
            
            if(!String.isEmpty(ApexPages.CurrentPage().getParameters().get('lang'))) {
            	languageCode = (ApexPages.CurrentPage().getParameters().get('lang')).toLowerCase();
            }
            if(String.isEmpty(languageCode)) {
                languageCode = 'en_us';
            }
            
            List<Case> cases = [SELECT Id, Account.Program__c FROM Case WHERE Id =: recordId and Secondary_Key__c =: key];
            
            if(cases.size() > 0) {
                
                program = WexBrandingController.getProgram(cases[0].Account.Program__c);
                
                if(program == null) {
                    didLength = '4';
                }
                else {
                    didLength = program.DID_Length__c;
                }
                
                Id brandingUtilityId = WexBrandingController.getBrandingUtilityByProgramId(cases[0].Account.Program__c, languageCode);

                if(brandingUtilityId != null) {

                    brandingUtility = WexBrandingController.getBrandingUtility(brandingUtilityId);

                }
                
                brandingLogo = WexBrandingController.getLogoId(cases[0].Account.Program__c);
                
            }
            else {
                isBroken = true;
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Unable to find record.')); 
            }
            
        }
        
    }
    
}