src/objects/BOCA_IDs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IDs for orgs and email templates related to BOCA</description>
    <fields>
        <fullName>BOCA_Sell_Sheet__c</fullName>
        <description>Email Template IDS</description>
        <encryptionScheme>None</encryptionScheme>
        <label>BOCA Sell Sheet Email</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address_Noreply__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email_Address_Noreply</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Email_Address</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Instance_Prefix__c</fullName>
        <description>The prefix for this SF instance</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The prefix for this SF instance</inlineHelpText>
        <label>Instance Prefix</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>BOCA IDs</label>
</CustomObject>

src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Pricing__c.object
<CustomObject>
    <description>Object for storing pricing data</description>
    <fields>
        <fullName>Coupon_Status__c</fullName>
        <description>Shows if coupon matches a campaign program</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Coupon Status</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <description>Psoft Program Relationship Code</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Psoft Program Relationship Code</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contract_margin__c</fullName>
        <label>Contract Margin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <default>true</default>
                    <label>Y</label>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contract_rate_pct__c</fullName>
        <label>Contract Rate Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>coup_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Coupon Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>days_to_pay__c</fullName>
        <label>Days to Pay</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fixed_late_fee__c</fullName>
        <label>Fixed Late Fee</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>late_fee_type__c</fullName>
        <description>Late fee type (P = percentage, F = fixed)</description>
        <label>Late Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>minimum_payment_percentage__c</fullName>
        <description>Minimum Payment Percentage</description>
        <label>Minimum Payment Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>nbr_billing_cyles__c</fullName>
        <description># of Billing Cycles Promotional Rate is valid for (if one exists for the coupon)</description>
        <encryptionScheme>None</encryptionScheme>
        <label># of Billing Cycles Promo Rate is valid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>over_limit_fee__c</fullName>
        <label>Over Limit Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>paper_delivery_fee__c</fullName>
        <label>Paper Delivery Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pct_late_fee__c</fullName>
        <label>Percent Late Fee</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pen_rate_pct__c</fullName>
        <label>Penalty Percentage Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>penalty_margin__c</fullName>
        <label>Penalty Margin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <default>true</default>
                    <label>Y</label>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>penalty_rate_ceiling__c</fullName>
        <label>Penalty Rate Ceiling</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>prime_rate__c</fullName>
        <description>Most recent Prime Rate</description>
        <label>Prime Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>prime_rate_effective_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Prime Rate Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>promo_periods__c</fullName>
        <label>Promo Periods</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>promotional_rate__c</fullName>
        <label>Promotional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>return_payment_fee__c</fullName>
        <label>Return Payment Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>risk_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Risk Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Pricing</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Send_BOCA_to_Siebel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Send BOCA to Siebel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BOCA_Sell_Sheet__c</fullName>
        <description>Sell sheets for BOCA</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Sell sheets for BOCA</inlineHelpText>
        <label>BOCA Sell Sheet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <description>Branded heading for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Long_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Long Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Custom_Email_Header_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>URL to wexhosted for this program&apos;s email header</inlineHelpText>
        <label>Custom Email Header URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Template__c</fullName>
        <label>Form Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditApp_Revolver</fullName>
                </value>
                <value>
                    <fullName>WexBOCA</fullName>
                </value>
                <value>
                    <fullName>OTRBOCA</fullName>
                </value>
                <value>
                    <fullName>wexU</fullName>
                </value>
                <value>
                    <fullName>WexBOCA2</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Peoplesoft Rel Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Language_Indicator__c</fullName>
        <label>Preferred Language Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENG</fullName>
                </value>
                <value>
                    <fullName>ENU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Section_Titles__c</fullName>
        <description>BOCA Section Headers</description>
        <label>Section Titles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tell Us About Your Business</fullName>
                </value>
                <value>
                    <fullName>Billing Contact Information</fullName>
                </value>
                <value>
                    <fullName>Promotional Information</fullName>
                </value>
                <value>
                    <fullName>Statement &amp; Report Delivery</fullName>
                </value>
                <value>
                    <fullName>Tell Us About Yourself</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Terms &amp; Conditions</fullName>
                </value>
                <value>
                    <fullName>Business Information</fullName>
                </value>
                <value>
                    <fullName>Billing Information</fullName>
                </value>
                <value>
                    <fullName>Additional Information</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_Pricing_Data_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Upload Pricing Data Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/BOCAtestDataUtility.cls
@isTest
public class BOCAtestDataUtility {

//for stagefull
   
   public static Campaign_Program__c testcp{get{
        if(testcp == null)
            testcp = getcp();
        
        return testcp;
    }
     set;
    }
    public static campaign_Pricing__c pric{get{
        if(pric == null)
            pric = getpricing();
        
        return pric;
    }
     set;
    }
    public static  Campaign testCamp{get{
        if(testCamp == null)
            testCamp = getCampaign();
        
        return testCamp;
    }
     set;
    }
   public static  Program__c testProg2{get{
        if(testProg2  == null)
            testProg2  = getProgram();
        
        return testProg2 ;
    }
     set;
    }

    //stagefull
    /*
   public static BOCA_IDS__C getBOCAids(){
        
        BOCA_IDS__c bi = new BOCA_IDS__c();
        bi.Name = 'BOCA IDS';
        bi.BOCA_Sell_Sheet__c = '00XM0000000IjRY';
        bi.Email_Address__c = 'salesforce@wrightexpress.com.stagefull';
        bi.Email_Address_Noreply__c = 'noreply@wexinc.com.stagefull';
        bi.Instance_Prefix__c = 'https:www.cs7.stagefull.salesforce.com';
        
        return bi;
        
        
        
    }

//Prod
*/
       public static BOCA_IDS__C getBOCAids(){
        
        BOCA_IDS__c bi = new BOCA_IDS__c();
        bi.Name = 'BOCA IDS';
        bi.BOCA_Sell_Sheet__c = '00X70000001zGLp';
        bi.Email_Address__c = 'salesforce@wrightexpress.com';
        bi.Email_Address_Noreply__c = 'noreply@wexinc.com';
        bi.Instance_Prefix__c = 'https://onlineservices.secure.force.com/';
        
        return bi;
        
        
        
    }
    
    public static Campaign getCampaign(){
        
        testCamp = new Campaign();
        
        testCamp.Coupon_Code__c = 'A001';
        testCamp.Name = 'testBOCA123';
        testCamp.Type = 'Online Form';
        testCamp.Status = 'In Progress';
        testCamp.Drop_Date__c = date.today();
        testCamp.EndDate = date.today();
        testCamp.CurrencyIsoCode = 'USD';
        testCamp.IsActive = true;
        
        upsert testCamp;
        
        return testCamp;
        
        
    }
    
    public static Campaign_Pricing__c getPricing(){

        pric = new Campaign_Pricing__c();
        
        pric.Name = 'test';
        pric.contract_margin__c = 'Y';
        pric.penalty_margin__c = 'Y';
        pric.days_to_pay__c = 21;
        pric.prime_rate__c = 3.25;
        pric.prime_rate_effective_date__c = date.today();
        pric.late_fee_type__c = 'P';
        pric.return_payment_fee__c = 49.99;
        pric.over_limit_fee__c = 39.99;
        pric.paper_delivery_fee__c = 5.00;
        pric.penalty_rate_ceiling__c = 999.99;
        pric.minimum_payment_percentage__c = 29.99;
        pric.Peoplesoft_rel_code__c = '012011';
        pric.coup_code__c = 'A001';
        pric.is_Active__c = true;
        pric.Coupon_Status__c = 'valid';
        pric.risk_code__c = 'No';
        pric.nbr_billing_cyles__c = '1';
        pric.contract_rate_pct__c = 10.15;
        pric.fixed_late_fee__c = 0.00;
        pric.pct_late_fee__c = 2.49;
        pric.pen_rate_pct__c = 27.34;
        pric.promo_periods__c = 1.0;
        pric.promotional_rate__c = 8.17;
        pric.CurrencyIsoCode = 'USD';
        
        upsert pric;
        return pric;
    }
    
    public static Program__c getProgram(){

        testProg2 = new Program__c();
        
        testProg2.Name = 'testFlex2' ; 
        System.debug('program name ' + testProg2.Name);
        
        testProg2.Form_Template__c = 'WexBOCA';
        testProg2.Brand_Short_Name__c = 'flex2';
        testProg2.Preferred_Language_Indicator__c = 'ENU';
        testProg2.Peoplesoft_rel_code__c = '0001207';
        testProg2.Custom_Email_Header_URL__c = 'http://www.wexhosted.com/email/revolver/header_wexRevolver.jpg';
        testProg2.Brand_Heading__c = 'Time is money. Use WEX and save both.';
        testProg2.Brand_Long_Name__c = 'flex test card';
        testProg2.Section_Titles__c = 'Tell Us About Your Business; Billing Contact Information; Promotional Information; Statement & Report Delivery; Tell Us About Yourself; Authorization; Terms & Conditions';	
        testProg2.Upload_Pricing_Data_Flag__c = false;
        testProg2.Auto_Send_BOCA_to_Siebel__c = true;
        testProg2.T_C__c = 'WEX_BOCA_TNC';
        testProg2.Analytics_Body_Block__c = '';
        testProg2.Analytics_Head_Block__c = '';
        testProg2.Brand_Color_1__c = '#ccc';
        testProg2.Brand_Color_2__c = '#fff';
        
        
        upsert testProg2;
     
        //attachments
        Attachment attach3 = new Attachment();
        attach3.Name = 'ui-credit-card.png';
        Blob bodyBlob3=Blob.valueOf('Unit Test Attachment Body');
        attach3.body=bodyBlob3;
        attach3.parentId=testProg2.id;
        upsert attach3;
        
        Attachment attach4 = new Attachment();
        attach4.Name = 'ui-logo.png';
        Blob bodyBlob4=Blob.valueOf('Unit Test Attachment Body');
        attach4.body=bodyBlob4;
        attach4.parentId=testProg2.id;
        upsert attach4;
        
        SYSTEM.debug('Here is program ' + testProg2.id);
        Boca_Res__c bocaRes = new Boca_Res__c();
        bocaRes.Email_Template_ID__c = '00X70000001EfPG';
        bocaRes.Brand_Heading__c = 'Test Heading';
        bocaRes.Brand_Tagline__c = 'Test Tagline';
        bocaRes.ISO_code__c = 'en_us';
        bocaRes.Program__c = testProg2.id;
        bocaRes.Side_Panel_Title__c = 'Test Sidebar Title';
        bocaRes.SideBar__c = 'Test Sidebar';
        bocaRes.Program_Name__c = testProg2.Name;
        bocaRes.Name = 'test';
        bocaRes.Program_Sell_Sheets__c = 'www.sellsheet.com';
        
        upsert bocaRes;
        SYSTEM.debug('Here is bocaRes ' + bocaRes.id);
      
        Boca_Res__c bocaRes2 = new Boca_Res__c();
        bocaRes2.Email_Template_ID__c = '00X70000001EfPG';
        bocaRes2.Brand_Heading__c = 'Test Heading';
        bocaRes2.Brand_Tagline__c = 'Test Tagline';
        bocaRes2.ISO_code__c = 'fr';
        bocaRes2.Program__c = testProg2.id;
        bocaRes2.Side_Panel_Title__c = 'Test Sidebar Title';
        bocaRes2.SideBar__c = 'Test Sidebar';
        bocaRes2.Program_Name__c = testProg2.Name;
        bocaRes2.Name = 'test2';
        
        upsert bocaRes2;
		Campaign_Program__c cp = new Campaign_Program__c();

        cp = getCP();
        
        
        testProg2.Publish_BOCA__c = true;
        upsert testProg2;
        
        return testProg2;
    }
        
        
        public static Campaign_Program__c getCP(){

            
        testCP = new Campaign_Program__c();
        //create campaign program test data
        testCP.Name = 'Flex Test';
        testCP.Campaign__c = testCamp.Id;
        testCP.Program__c = testProg2.Id;
        testCP.Terms_and_Conditions__c = 'Test T&C';
        testCP.Default__c = true;
        
        upsert testCP;

        testCamp.Coupon_Code__c = pric.coup_code__c;
        upsert testCamp;
        

       return testCP;
        
        
    }

}