src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>BOCA_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BOCA Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISO_code__c</fullName>
        <label>ISO code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>en_ca</fullName>
                </value>
                <value>
                    <fullName>en_us</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>fr_ca</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Primary_Program_Benefits__c</fullName>
        <description>Benefits that are displayed as bullet points when the program is selected as the primary offering in a BOCA to Prospect.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Primary Program Benefits</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Secondary_Program_Benefits__c</fullName>
        <description>Benefits that are displayed as bullet points when the program is selected as the secondary offering in a BOCA to Prospect.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Secondary Program Benefits</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/BOCA_To_Prospect__c.object
<CustomObject>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <description>Object to link partner programs together</description>
    <fields>
        <fullName>Default_DM_Flex_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Default DM Flex Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_DM_Fuel_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Default DM Fuel Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>Partner</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Always_Require_PG__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Always require PG for this Program.</description>
        <label>Always Require PG</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BOCA_Sell_Sheet__c</fullName>
        <description>Sell sheets for BOCA</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Sell sheets for BOCA</inlineHelpText>
        <label>BOCA Sell Sheet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BOCA_Type__c</fullName>
        <label>BOCA Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fuel Card</fullName>
                    <default>true</default>
                    <label>Fuel Card</label>
                </value>
                <value>
                    <fullName>Revolver Card</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>OTR</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Form_Template__c</fullName>
        <label>Form Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditApp_Revolver</fullName>
                </value>
                <value>
                    <fullName>WexBOCA</fullName>
                </value>
                <value>
                    <fullName>OTRBOCA</fullName>
                </value>
                <value>
                    <fullName>wexU</fullName>
                </value>
                <value>
                    <fullName>WexBOCA2</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The partner this Program belongs to, which is used for grouping programs together.</description>
        <inlineHelpText>The partner this Program belongs to, which is used for grouping programs together.</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Program Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GU Fleet Card</fullName>
                </value>
                <value>
                    <fullName>SP Fleet Card</fullName>
                </value>
                <value>
                    <fullName>SG Fleet Card</fullName>
                </value>
                <value>
                    <fullName>HK Fleet Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeFormObject__c.object
<CustomObject>
    <fields>
        <fullName>BOCA_Type__c</fullName>
        <formula>TEXT(Program__r.BOCA_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BOCA Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promotional_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Promotional Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeFormObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeFormObject</label>
        <referenceTo>WeFormObject__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/BOCAToProspectComponentController.cls
public class BOCAToProspectComponentController {
    
    public Boolean initialized { get; set; }
    
    // https://salesforce.stackexchange.com/a/9946
    public String bocaToProspectId { 
        get;
        set {
            bocaToProspectId = value;
            if(!initialized) {
                init();
                initialized = true;
            }
        } 
    }
    
    public BOCA_To_Prospect__c bocaToProspect { get; set; }
    
    public WeFormObject__c weFormObject { get; set; }
    
    public User salesRep { get; set; }
    
    public Id programId { 
        get {
            if(bocaToProspect != null) {
                return bocaToProspect.WeFormObject__r.Program__c;
            }
            return null;
        }
    }
    
    public String primaryBrandingCard { get; set; }
    
    public Integer secondaryProgramSize {
        get {
            return secondaryPrograms.size();
        }
    }
    
    public String pgValue {
        get {
            if(bocaToProspect.Disable_PG__c) {
                return 'n';
            }
            else if(bocaToProspect.Always_Require_PG__c) {
                return 'a';
            }
            else {
                return 'c';
            }
        }
    }
    
    public List<SecondaryProgram> secondaryPrograms { 
        get {
            
            List<SecondaryProgram> secondaryPrograms = new List<SecondaryProgram>();
            
            System.debug('### ' + bocaToProspect.Additional_Programs__c);
            
            if(bocaToProspect != null && bocaToProspect.Additional_Programs__c != null) {
                
                List<String> additionalPrograms = (List<String>)JSON.deserialize(bocaToProspect.Additional_Programs__c, List<String>.class);
                
                for(String additionalProgram : additionalPrograms) {

                    List<BOCA_res__c> brandingUtilities = [SELECT Id, BOCA_Default__c, Program__c, Program__r.BOCA_Type__c, Program__r.Partner__r.Default_DM_Flex_Code__c, Program__r.Partner__r.Default_DM_Fuel_Code__c, Program__r.Brand_Short_Name__c, Program__r.Form_Template__c, Program_Name__c, Primary_Program_Benefits__c, Secondary_Program_Benefits__c, ISO_code__c FROM BOCA_res__c WHERE Program__c =: additionalProgram ];

                    if(brandingUtilities.size() > 0) {
                        BOCA_res__c brandingUtility = getBrandingUtilityFromList(brandingUtilities);
                        SecondaryProgram secondaryProgram = new SecondaryProgram();
                        
                        String couponCode = weFormObject.Promotional_Code__c;

                        if(bocaToProspect.WeFormObject__r.Program__r.BOCA_Type__c != null && !(bocaToProspect.WeFormObject__r.Program__r.BOCA_Type__c).equalsIgnoreCase(brandingUtility.Program__r.BOCA_Type__c)) {
                        	if((brandingUtility.Program__r.BOCA_Type__c).equalsIgnoreCase('Revolver Card') && brandingUtility.Program__r.Partner__r.Default_DM_Flex_Code__c != null) {
	                    		couponCode = brandingUtility.Program__r.Partner__r.Default_DM_Flex_Code__c;
                       		}
                        	else if((brandingUtility.Program__r.BOCA_Type__c).equalsIgnoreCase('Fuel Card') && brandingUtility.Program__r.Partner__r.Default_DM_Fuel_Code__c != null) {
                           		couponCode = brandingUtility.Program__r.Partner__r.Default_DM_Fuel_Code__c;
                        	}
                        }
                        
                        secondaryProgram.name = brandingUtility.Program_Name__c;
                        secondaryProgram.benefits = brandingUtility.Secondary_Program_Benefits__c;
                        secondaryProgram.bocaURL = 'https://' + Label.External_Instance_URL + '/creditapplication/' + brandingUtility.Program__r.Form_Template__c + '?pgm=' + brandingUtility.Program__r.Brand_Short_Name__c + '&priority=true&customer=' + weFormObject.Id + '&salescode=' + weFormObject.Sales_Id__c + '&cc=' + couponCode + '&pg=' + pgValue + '&lang=' + languageCode;
                        
                        transient Attachment secondaryBrandingCard = [SELECT Id, Name, Body FROM Attachment where ParentId = :additionalProgram AND Name = 'ui-credit-card.png'];
                        
                        secondaryProgram.brandingCard = secondaryBrandingCard.Id;
                        
                        secondaryPrograms.add(secondaryProgram);
                        
                    }
                    
                }
                
            }
            
            System.debug(secondaryPrograms);
            
            return secondaryPrograms;
        }
    }
    
    public Boolean displayAssetsLinks {
        get {
            Set<String> profileNames = new Set<String>{'Field Sales', 'Regional Sales Manager (West)', 'Regional Sales Manager (East) '};

            if(salesRep != null && salesRep.UserRole.Name != null && profileNames.contains(salesRep.UserRole.Name)) {
                return false;
            }
            return true;
        }
    }
    
    public BOCA_res__c primaryBrandingUtility { get; set; }
    
    public String primaryURL {
        get {
            return 'https://' + Label.External_Instance_URL + '/creditapplication/' + primaryBrandingUtility.Program__r.Form_Template__c + '?pgm=' + primaryBrandingUtility.Program__r.Brand_Short_Name__c + '&priority=true&customer=' + weFormObject.Id + '&salescode=' + weFormObject.Sales_Id__c + '&cc=' + weFormObject.Promotional_Code__c + '&pg=' + pgValue + '&lang=' + languageCode + '&utm_medium=sales&utm_source=b2p%20link';
        }
    }

    public String languageCode {
        get {
            if (weFormObject.Branding_Utility__c != null) {
                return weFormObject.Branding_Utility__r.ISO_Code__c;
            }
            return null;
        }
    }

    public String primaryLearnMoreURL {
        get {
            if(weFormObject.Program__c != null && weFormObject.Program__r.BOCA_Sell_Sheet__c != null) {
            	return 'https://' + Label.External_Instance_URL + '/creditapplication/BocaToProspectTracking?customer=' + weFormObject.Id + '&action=learnMore';
            }
            return null;
        }
    }
    
    public BOCAToProspectComponentController() {
        initialized = false;
    }

    private BOCA_res__c getBrandingUtilityFromList(List<BOCA_res__c> brandingUtilities) {

        Map<String, BOCA_res__c> brandingUtilityLanguageMap = new Map<String, BOCA_res__c>(); // Language Code, BOCA_res__c
        BOCA_res__c defaultBrandingUtility;

        for (BOCA_res__c brandingUtility : brandingUtilities) {

            if (brandingUtilityLanguageMap.get(brandingUtility.ISO_code__c) == null) brandingUtilityLanguageMap.put(brandingUtility.ISO_code__c, brandingUtility);
            if (brandingUtility.BOCA_Default__c) defaultBrandingUtility = brandingUtility;

        }

        if (languageCode != null && brandingUtilityLanguageMap.get(languageCode) != null) return brandingUtilityLanguageMap.get(languageCode);
        else if (defaultBrandingUtility != null) return defaultBrandingUtility;
        else return brandingUtilities[0];


    }
    
    public void init() {

        List<BOCA_To_Prospect__c> bocaToProspects = [SELECT Id, Always_Require_PG__c, Disable_PG__c, WeFormObject__c, WeFormObject__r.Program__c, WeFormObject__r.Program__r.BOCA_Type__c, WeFormObject__r.Branding_Utility__c, Additional_Programs__c, Custom_Message__c, Contact__r.FirstName, Opportunity__r.Owner.FirstName FROM BOCA_To_Prospect__c WHERE Id = :bocaToProspectId LIMIT 1];
        System.debug('### ' + bocaToProspects);
        
        if(bocaToProspects.size() > 0) {
            bocaToProspect = bocaToProspects[0];
            
        }
        
        if(bocaToProspect != null && programId != null) {
            
            List<WeFormObject__c> weFormObjects = [SELECT Id, Branding_Utility__r.ISO_Code__c, Opportunity__r.Campaign_Response_Methods__c, Program__r.Form_Template__c, Program__r.Brand_Short_Name__c, Program__r.BOCA_Sell_Sheet__c, Sales_Id__c, Promotional_Code__c FROM WeFormObject__c WHERE Id = :bocaToProspect.WeFormObject__c LIMIT 1];
            
            if(weFormObjects.size() > 0) {
                weFormObject = weFormObjects[0];
            }

            List<BOCA_res__c> brandingUtilities = [SELECT Id, BOCA_Default__c, Program_Name__c, Primary_Program_Benefits__c, Secondary_Program_Benefits__c, Program__r.Form_Template__c, Program__r.Brand_Short_Name__c, ISO_Code__c FROM BOCA_res__c WHERE Program__c = :programId ];

            if (brandingUtilities.size() > 0) {
                primaryBrandingUtility = getBrandingUtilityFromList(brandingUtilities);
            }

            transient Attachment card = [SELECT Id, Name, Body FROM Attachment where ParentId = :programId AND Name = 'ui-credit-card.png'];
            
            if(card != null) {
                primaryBrandingCard = card.Id;
            }
            
            salesRep = [SELECT Id, Name, Title, Email, Phone, Fax, UserRole.Name FROM USER WHERE Id =: bocaToProspect.Opportunity__r.OwnerId];
        }
    }
    
    public class SecondaryProgram {
        
        public String name { get; set; }
        public String benefits { get; set; }
        public String brandingCard { get; set; }
        public String bocaURL { get; set; }
        
    }

}