src/objects/BOCA_To_Prospect__c.object
<CustomObject>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>BOCA_Sell_Sheet__c</fullName>
        <description>Sell sheets for BOCA</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Sell sheets for BOCA</inlineHelpText>
        <label>BOCA Sell Sheet</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeFormObject__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WeFormObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeFormObject</label>
        <referenceTo>WeFormObject__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/BOCAtoProspectTrackingController.cls
public class BOCAtoProspectTrackingController {

    public String weFormId { 
        get {
            return ApexPages.currentPage().getParameters().get('customer');
        }
    }
    
    public String action { 
        get {
            return ApexPages.currentPage().getParameters().get('action');
        }
    }
    
    public BOCAtoProspectTrackingController() {
        
    }
    
    public PageReference logVisit() {
     
        PageReference redirect = null;
        
        try {
        	if(weFormId != null) {
            	BOCA_To_Prospect__c bocaToProspect = [SELECT Id, Read_By_Recipient__c FROM BOCA_To_Prospect__c WHERE WeFormObject__c = :weFormId];
            	bocaToProspect.Read_By_Recipient__c = true;
                bocaToProspect.Last_Read_Date__c = Date.Today();
            	upsert bocaToProspect;
        	}
            
            if(weFormId != null && action != null) {
                if(action.equalsIgnoreCase('learnmore')) {
                    WeFormObject__c weForm = [SELECT Id, Program__c FROM WeFormObject__c WHERE Id =: weFormId];
                    
                    System.debug(weForm.Program__c);
                    
                    Program__c program = [SELECT Id, BOCA_Sell_Sheet__c FROM Program__c WHERE Id =: weForm.Program__c];
                    
                    redirect = new PageReference(program.BOCA_Sell_Sheet__c);
                    
                    BOCA_To_Prospect__c bocaToProspect = [SELECT Id, Read_Sell_Sheet__c FROM BOCA_To_Prospect__c WHERE WeFormObject__c = :weFormId];
        	    	bocaToProspect.Read_Sell_Sheet__c = true;
	            	upsert bocaToProspect;
                }
            }
        }
        catch(Exception e) {
            
        }
        
        return redirect;
    }
    
}