src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>External_Application_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>External Application URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Online Applications</relationshipLabel>
        <relationshipName>Online_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Partner_BOCA_To_Prospect__c.object
<CustomObject>
    <fields>
        <fullName>External_Application_URL__c</fullName>
        <description>url generated for BOCA to prospect</description>
        <encryptionScheme>None</encryptionScheme>
        <label>External Application URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Online_Application_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Online Application Offer</label>
        <referenceTo>OnlineApplicationOffer__c</referenceTo>
        <relationshipLabel>Partner BOCA To Prospects</relationshipLabel>
        <relationshipName>Partner_BOCA_To_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Online_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Online Application</label>
        <referenceTo>OnlineApplication__c</referenceTo>
        <relationshipLabel>Partner BOCA To Prospects</relationshipLabel>
        <relationshipName>Partner_BOCA_To_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Partner BOCA To Prospects</relationshipLabel>
        <relationshipName>Partner_BOCA_To_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Rep First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Rep Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Rep Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WeFormObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeFormObject</label>
        <referenceTo>WeFormObject__c</referenceTo>
        <relationshipLabel>Partner BOCA To Prospects</relationshipLabel>
        <relationshipName>Partner_BOCA_To_Prospects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner BOCA To Prospect</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner BOCA To Prospect Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner BOCA To Prospects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WeFormObject__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Online_Application_Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Online Application Offer</label>
        <referenceTo>OnlineApplicationOffer__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Online_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Online Application</label>
        <referenceTo>OnlineApplication__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Rep Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Sales_Rep_Phone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Rep Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>WeFormObject__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WeFormObject</label>
        <referenceTo>WeFormObject__c</referenceTo>
        <relationshipLabel>WeFormsObjects</relationshipLabel>
        <relationshipName>WeFormsObjects</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/PB2PComponentController.cls
public class PB2PComponentController {

    public Boolean initialized { get; set; }

    public String partnerBOCAToProspectId {
        get;
        set {
            partnerBOCAToProspectId = value;
            if(!initialized) {
                init();
                initialized = true;
            }
        }
    }

    public Partner_BOCA_To_Prospect__c partnerBOCAToProspect { get; set; }

    public WeFormObject__c weFormObject { get; set; }

    public Id programId {
        get {
            if(partnerBOCAToProspect != null) {
                return Id.valueOf(partnerBOCAToProspect.Program__c);
            }
            return null;
        }
    }

    public Id brandingCard { get; set; }

    public Program__c program { get; set; }

    public BOCA_res__c brandingUtility { get; set; }

    public PB2PComponentController() {
        initialized = false;
    }

    public void init() {

        List<Partner_BOCA_To_Prospect__c> partnerBOCAToProspects = [SELECT Id, First_Name__c, Sales_Rep_First_Name__c, Sales_Rep_Last_Name__c, Sales_Rep_Phone__c, Sales_Rep_Email__c, Program__c, Online_Application__c, Online_Application_Offer__c, Online_Application__r.External_Application_URL__c, External_Application_URL__c FROM Partner_BOCA_To_Prospect__c WHERE Id =: partnerBOCAToProspectId];

        if(partnerBOCAToProspects.size() > 0) {

            partnerBOCAToProspect = partnerBOCAToProspects[0];

            program = WexBrandingController.getProgram(partnerBOCAToProspect.Program__c);

            Id brandingUtilityId = WexBrandingController.getBrandingUtilityByProgramId(partnerBOCAToProspect.Program__c, 'en_us');

            if(brandingUtilityId != null) {
                brandingUtility = WexBrandingController.getBrandingUtility(brandingUtilityId);
            }

            brandingCard = WexBrandingController.getCreditCardImageId(program.Id);

        }

    }

    public static String buildApplicationParameterString(Map<String, String> parameters) {

        List<String> joinedParameters = new List<String>();

        for(String key : parameters.keySet()) {

            if(parameters.get(key) != null) {

                joinedParameters.add(key + '=' + EncodingUtil.urlEncode(parameters.get(key), 'UTF-8'));

            }

        }

        return String.join(joinedParameters, '&');

    }

}