src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>Email_Template_ID__c</fullName>
        <description>Custom email template id</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the id of the custom email template for this BOCA resource</inlineHelpText>
        <label>Email Template ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_code__c</fullName>
        <label>ISO code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>en_ca</fullName>
                </value>
                <value>
                    <fullName>en_us</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>fr_ca</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates default campaign for this program.</description>
        <label>BOCA Default Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OnlineApplicationOffer__c.object
<CustomObject>
    <description>Forseva Online Application Project</description>
    <fields>
        <fullName>BOCA_Default_Offer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BOCA Default Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Online Application Offers</relationshipLabel>
        <relationshipName>Online_Application_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Online Application Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Online Application Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 2</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Email_Header_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>URL to wexhosted for this program&apos;s email header</inlineHelpText>
        <label>Custom Email Header URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Template__c</fullName>
        <label>Form Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditApp_Revolver</fullName>
                </value>
                <value>
                    <fullName>WexBOCA</fullName>
                </value>
                <value>
                    <fullName>OTRBOCA</fullName>
                </value>
                <value>
                    <fullName>wexU</fullName>
                </value>
                <value>
                    <fullName>WexBOCA2</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Publish_BOCA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish BOCA</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/WEXProgramUtility.cls
public class WEXProgramUtility {
 
    // Called from the before insert/update trigger on Terms and Conditions.  
    // Called when the Terms and Conditions is updated or inserted AND the default flag == true
    // 
    //This method will update the default flag to false for all
    //Terms and Conditions under the program - theoretically there should always only be one set anyway.
    //
    public void resetDefaultFlagForProgram(Campaign_Program__c cp){
        
          
        List<Campaign_Program__c> cpList = [
            select id, Program__c, Campaign__c, Default__c
            from Campaign_Program__c 
            where Program__c = :cp.program__c
            and campaign__c != :cp.Campaign__c
            and id != :cp.Id
            and Default__c = true
        ];
        
        for (Campaign_Program__c newDefaultcp : cpList){
            newDefaultcp.Default__c = false;
        }
        
        update cpList;
    }
   
    public boolean isDefault(Campaign_Program__c cp){

        if (cp.Default__c == true){
            return true;
        }
        
        return false;
    }
    // Called from the program BeforeUpdate/Insert trigger.  Only allow anything to be published if 
    // it has a default Terms and Conditions set.
    //
    // Used to find out if the program has a default Terms and Conditions setup already
    //
    public boolean hasAnotherDefaultTermsAndConditionsSet(Campaign_Program__c cp){
        List<Campaign_Program__c> cpList = [
            select Program__c, id,  Default__c
            from Campaign_Program__c 
            where Program__c = :cp.Program__c 
            and id != :cp.Id
            and Default__c = true];
        
        if (cpList.size() > 0){
            return true;
        }
        
        return false;
    }
    //restructure code to check for all required branding 
    public void hasAllBranding(Program__c prog){
        if(prog.Publish_BOCA__c == true){
        	if(prog.Custom_Email_Header_URL__c == null){
            	prog.addError('Email header url must be present to publish the program');
        	}
            if(prog.Form_Template__c == null){
                prog.addError('Form template must be chosen to publish the program');
            }
            if(prog.Brand_Color_1__c == null){
                prog.addError('Brand color 1 must have a value in order to publish the program');
            }
            if(prog.Brand_Color_2__c == null){
                prog.addError('Brand color 2 must have a value in order to publish the program');
            }
            
            // Check Attachments
        	List<attachment> attachments = [SELECT id, name from Attachment where Parentid =: prog.Id];
        
        	Boolean hasLogo = false;
        	Boolean hasCardImage = false;
        
    	    for(Integer i = 0; i < attachments.size(); i++) {
	            if(attachments[i].name == 'ui-logo.png') { hasLogo = true; }
    	        if(attachments[i].name == 'ui-credit-card.png') { hasCardImage = true; }
	        }
        
    	    if(!hasCardImage || !hasLogo) {
	            prog.addError('Please ensure this program has both attachments - card image (\"ui-credit-card.png\") and logo (\"ui-logo.png\").');
        	}
            
            List<BOCA_res__c> br = [SELECT ISO_code__c, Email_Template_ID__c, Name FROM BOCA_res__c WHERE Program__c =: prog.id];
            if(br.size() == 0){
                prog.addError('Program must have at least one Branding Utility created in order to publish.');
                
            }
            if(br.size() != 0){
                for(BOCA_res__c b : br){
                    if(b.ISO_code__c == null){
                        prog.addError('Branding resource ' + b.name + ' must have an ISO code in order to publish the program');
                    }
                    if(b.Email_Template_ID__c == null){
                        prog.addError('Branding resource ' + b.Name + ' must have an email template in order to publish the program');
                    }
                }
                
            }
            
        }
        
        
        
    }
    
    public boolean hasDefaultTermsAndConditions(Id pgmId){
        
        List<Campaign_Program__c> cpList = [
            select id, Program__c, Default__c
            from Campaign_Program__c 
            where Program__c = :pgmId 
            and Default__c = true];
        
        if (cpList.size() > 0){
            return true;
        }
        
        return false;
    }
    
    public boolean hasDefaultOnlineApplicationOffer(Id pgmId){
        
        List<OnlineApplicationOffer__c> onlineOffers = [
            select id, Program__c, BOCA_Default_Offer__c
            from OnlineApplicationOffer__c 
            where Program__c = :pgmId 
            and BOCA_Default_Offer__c = true];
        
        if (onlineOffers.size() > 0){
            return true;
        }
        
        return false;
    }
    
    public boolean isPublished (id pgmId){
        List<Program__c> pgm = [select Publish_BOCA__c from program__c where id = :pgmId];
        
        if (pgm.size() > 0 && pgm[0].Publish_BOCA__c == true){
            return true;
        }
        
        return false;
    }
}