src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Tagline__c</fullName>
        <description>Branded Tagline for This Program</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Tagline</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Template_ID__c</fullName>
        <description>Custom email template id</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the id of the custom email template for this BOCA resource</inlineHelpText>
        <label>Email Template ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_code__c</fullName>
        <label>ISO code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>en_ca</fullName>
                </value>
                <value>
                    <fullName>en_us</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>fr_ca</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SideBar__c</fullName>
        <description>HTML of BOCA sidebar</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SideBar</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Side_Panel_Title__c</fullName>
        <description>Sidebar Panel Title</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Side Panel Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_And_Conditions__c</fullName>
        <inlineHelpText>By selecting a Terms and Conditions, this will override any values set at the Program level. This is mainly intended for overriding language (i.e. French, Spanish, etc)</inlineHelpText>
        <label>Terms And Conditions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BOCA_TNC_FR</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Esso</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Esso_FR</fullName>
                </value>
                <value>
                    <fullName>BLANK_TNC</fullName>
                    <isActive>false</isActive>
                    <label>BLANK_TNC</label>
                </value>
                <value>
                    <fullName>BOCA_TNC_MrGas</fullName>
                    <isActive>false</isActive>
                    <label>BOCA_TNC_MrGas</label>
                </value>
                <value>
                    <fullName>BOCA_TNC_MrGas_FR</fullName>
                    <isActive>false</isActive>
                    <label>BOCA_TNC_MrGas_FR</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates default campaign for this program.</description>
        <label>BOCA Default Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms and Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Analytics_Body_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analytics - Body Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Analytics_Head_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for google analytics code</inlineHelpText>
        <label>Analytics - Head Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auto_Send_BOCA_to_Siebel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Send BOCA to Siebel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BOCA_To_Prospect_Template__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>BOCA To Prospect Template</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 2</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <description>Branded heading for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Long_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Long Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Brand_Tagline__c</fullName>
        <description>Branded tagline for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Tagline</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Email_Header_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>URL to wexhosted for this program&apos;s email header</inlineHelpText>
        <label>Custom Email Header URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Template__c</fullName>
        <label>Form Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditApp_Revolver</fullName>
                </value>
                <value>
                    <fullName>WexBOCA</fullName>
                </value>
                <value>
                    <fullName>OTRBOCA</fullName>
                </value>
                <value>
                    <fullName>wexU</fullName>
                </value>
                <value>
                    <fullName>WexBOCA2</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Peoplesoft Rel Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Preferred_Language_Indicator__c</fullName>
        <label>Preferred Language Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENG</fullName>
                </value>
                <value>
                    <fullName>ENU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SideBar__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SideBar</label>
        <length>80000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Side_Panel_Title__c</fullName>
        <description>Title for left panel on BOCA</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a title to appear above left panel on BOCA layout</inlineHelpText>
        <label>Side Panel Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_C__c</fullName>
        <description>Generally static T&amp;C doc for bottom of BOCA, will default to the WEX BOCA but FlexCard should use the BOCA_TC</description>
        <inlineHelpText>Generally static T&amp;C doc for bottom of BOCA, will default to the WEX BOCA but FlexCard should use the BOCA_TC</inlineHelpText>
        <label>TNC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BLANK_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC</fullName>
                    <default>true</default>
                    <label>BOCA_TNC</label>
                </value>
                <value>
                    <fullName>FLEX_BOCA_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_FEE_699</fullName>
                </value>
                <value>
                    <fullName>BOCA_GETT_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Chevron</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Shell</fullName>
                </value>
                <value>
                    <fullName>CPBOCATNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_ShellSmallBusiness</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_ShellPlus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_Pricing_Data_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Upload Pricing Data Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Sales_Code__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Sales Codes</relationshipLabel>
        <relationshipName>Sales_Codes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Sales Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Sales Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CPBOCAToProspectTest.cls
/**
 * Created by dgilbert on 8/21/2018.
 */
@isTest
public with sharing class CPBOCAToProspectTest {

    @testSetup
    static void setupData(){

        UtilityTestLoader.setAutomation(false);
    
        // Revisit this later..
        BOCA_IDS__C bocaId = BOCAtestDataUtility.getBOCAids();
        insert bocaId;

        Campaign campaign = new Campaign();

        //create campaign test data
        campaign.Coupon_Code__c = 'TEST1';
        campaign.Name = 'TestCPCampaign';
        campaign.Type = 'Online Form';
        campaign.Status = 'In Progress';
        campaign.Drop_Date__c = date.today();
        campaign.EndDate = date.today();
        campaign.CurrencyIsoCode = 'USD';
        campaign.IsActive = true;

        insert campaign;

        Program__c program = new Program__c();

        program.Name = 'TestBOCA';
        program.Peoplesoft_rel_code__c = '012011';
        program.Form_Template__c = 'CPBOCA';
        program.Brand_Short_Name__c = 'TestBOCA';
        program.Preferred_Language_Indicator__c = 'ENU';
        program.Custom_Email_Header_URL__c = 'http://www.wexhosted.com/email/revolver/header_wexRevolver.jpg';
        program.Brand_Heading__c = 'Time is money. Use WEX and save both.';
        program.Brand_Long_Name__c = 'Test BOCA';
        program.Upload_Pricing_Data_Flag__c = false;
        program.Auto_Send_BOCA_to_Siebel__c = false;
        program.T_C__c = 'WEX_BOCA_TNC';
        program.Analytics_Body_Block__c = '';
        program.Analytics_Head_Block__c = '';
        program.Brand_Color_1__c = '#ccc';
        program.Brand_Color_2__c = '#fff';
        program.BOCA_To_Prospect_Template__c = '00X70000001EfPG';

        insert program;

        // Setup Attachments
        Attachment cardImage = new Attachment();
        cardImage.Name = 'ui-credit-card.png';
        Blob cardImageBlob = Blob.valueOf('Unit Test Attachment Body');
        cardImage.body = cardImageBlob;
        cardImage.parentId = program.Id;
        upsert cardImage;

        Attachment logo = new Attachment();
        logo.Name = 'ui-logo.png';
        Blob logoBlob = Blob.valueOf('Unit Test Attachment Body');
        logo.body = logoBlob;
        logo.parentId = program.Id;
        upsert logo;

        Campaign_Program__c campaignProgram = new Campaign_Program__c();
        //create campaign program test data
        campaignProgram.Name = 'Flex Test';
        campaignProgram.Campaign__c = campaign.Id;
        campaignProgram.Program__c = program.Id;
        campaignProgram.Terms_and_Conditions__c = 'Test T&C';
        campaignProgram.Default__c = true;

        insert campaignProgram;

        Boca_Res__c brandingUtility = new Boca_Res__c();
        brandingUtility.Email_Template_ID__c = '00X70000001EfPG';
        brandingUtility.Brand_Heading__c = 'Test Heading';
        brandingUtility.Brand_Tagline__c = 'Test Tagline';
        brandingUtility.ISO_code__c = 'en_us';
        brandingUtility.Program__c = program.id;
        brandingUtility.Side_Panel_Title__c = 'Test Sidebar Title';
        brandingUtility.SideBar__c = 'Test Sidebar';
        brandingUtility.Program_Name__c = program.Name;
        brandingUtility.Name = 'test';
        brandingUtility.Program_Sell_Sheets__c = 'www.sellsheet.com';

        insert brandingUtility;

        Partner__c partner = new Partner__c();

        partner.Name = 'Partners';

        insert partner;

        program.Partner__c = partner.Id;
        program.Publish_BOCA__c = true;

        upsert program;

        Profile profile = [SELECT Id FROM Profile WHERE Name = 'IS Sales'];

        User user = new User(Alias = 'tUse', Email='stanTestuser@wexinc.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = profile.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='stanarduser@wexinc.com');

        insert user;

        System.debug('### Campaign_Program__c Id: ' + campaignProgram.Campaign__c + ', Campaign Id: ' + campaign.Id);

        User integrationUser = [SELECT Id FROM User WHERE Alias = 'sinte'];

        System.runAs(user) {

            Account account = new account();
            
            account.name = 'TestAcc';
            
            insert account;
            
            Opportunity opportunity = new Opportunity();
            
            opportunity.Name = 'TestOpp';
            opportunity.AccountId = account.Id;
            opportunity.CloseDate = Date.newinstance(2099,1,1);
            opportunity.StageName = '1) Qualified';
            opportunity.Fleet_Size__c = 10;
            opportunity.OwnerId = user.Id;
            opportunity.SourceSystem__c = 'test';
            opportunity.Fueling_Methos__c = 'BP';
            opportunity.CampaignId = campaign.Id;
            opportunity.Campaign_Program__c = campaignProgram.Id;
            opportunity.Years_In_Business__c = 5;

            insert opportunity;

            Contact contact = new Contact();

            contact.FirstName = 'Tester';
            contact.LastName = 'Tester Last';
            contact.Email = 'Tester@UnitTest.com';

            insert contact;

            OpportunityContactRole opportunityContact = new OpportunityContactRole(contactId = contact.id, isPrimary = true, OpportunityId = opportunity.id);

            insert opportunityContact;

        }

    }

    @isTest
    static void testCPBOCAToProspectErrorHandler() {

        User integrationUser = [SELECT Id FROM User WHERE Alias = 'sinte'];

        System.runAs(integrationUser) {

            Test.startTest();

            TestUtils.enable_isRunningTest = true;

            Opportunity opportunity = [SELECT Id FROM Opportunity WHERE Name = 'TestOpp'];

            // Test without opportunity to test error handling
            PageReference cpBOCAToProspectPage = Page.CPBOCAToProspect;
            cpBOCAToProspectPage.getParameters().put('id', '');
            Test.setCurrentPage(cpBOCAToProspectPage);

            Apexpages.StandardController standardController = new ApexPages.StandardController(opportunity);
            CPBOCAToProspectController cpbocaToProspectController = new CPBOCAToProspectController(standardController);

            cpbocaToProspectController.init();

            System.assertEquals(true, cpbocaToProspectController.hasError);

            Test.stopTest();

        }

    }

    @isTest
    static void testCPBOCAToProspect() {

        User integrationUser = [SELECT Id FROM User WHERE Alias = 'sinte'];

        System.runAs(integrationUser) {

            Test.startTest();

            TestUtils.enable_isRunningTest = true;

            Opportunity opportunity = [SELECT Id, OwnerId FROM Opportunity WHERE Name = 'TestOpp'];

            // Test with opportunity
            PageReference cpBOCAToProspect = Page.CPBOCAToProspect;
            cpBOCAToProspect.getParameters().put('id', opportunity.Id);
            Test.setCurrentPage(cpBOCAToProspect);

            Apexpages.StandardController standardController = new ApexPages.StandardController(opportunity);
            CPBOCAToProspectController cpbocaToProspectController  = new CPBOCAToProspectController(standardController);

            cpbocaToProspectController.init();

            URLgenAttachmentLookupController ugalc = new URLgenAttachmentLookupController();
            System.assert(ugalc.folders != null);
            ugalc.displayDocuments();
            ugalc.clearSearch();

            Document tempDocument = new Document();
            tempDocument.Name = 'info.pdf';
            Blob tempDocumentBlob = Blob.valueOf('Unit Test Attachment Body');
            tempDocument.body = tempDocumentBlob;
            tempDocument.FolderId = UserInfo.getUserId();
            insert tempDocument;

            cpbocaToProspectController.attachments = '["' + tempDocument.Id + '"]';

            PageReference bocaToProspectRedirect = cpbocaToProspectController.bocaToProspect();

            List<user> salesReps = [SELECT Id, Name, FirstName, LastName, Email, Phone, Sales_Code__c FROM User WHERE Id =: opportunity.OwnerId LIMIT 1];
            System.debug('Opportunity Id: ' + opportunity.Id);
            System.debug('SalesRep: ' + Opportunity.OwnerId);
            System.debug('SalesRep Name: ' + salesReps[0].Name);
            System.assertNotEquals(null, cpbocaToProspectController.salesRepName);

            // Test the components
            CPBOCAToProspectComponentController cpBOCAToProspectComponentController = new CPBOCAToProspectComponentController();

            cpBOCAToProspectComponentController.bocaToProspectId = cpbocaToProspectController.bocaToProspect.Id;

            System.assertNotEquals(null, cpBOCAToProspectComponentController.bocaToProspect);
            System.assertNotEquals(null, cpBOCAToProspectComponentController.programId);
            System.assertNotEquals(null, cpBOCAToProspectComponentController.primaryBrandingCard);
            System.assertNotEquals(null, cpBOCAToProspectComponentController.primaryBrandingUtility);

            // Test the reminder function
            cpBOCAToProspect = Page.CPBOCAToProspect;
            cpBOCAToProspect.getParameters().put('bocaToProspectId', cpbocaToProspectController.bocaToProspect.Id);
            Test.setCurrentPage(cpBOCAToProspect);

            cpbocaToProspectController.init();

            bocaToProspectRedirect = cpbocaToProspectController.bocaToProspectReminder();

            // Test confirmation
            cpBOCAToProspect = Page.CPBOCAToProspect;
            cpBOCAToProspect.getParameters().put('bocaToProspectConfirm', 'true');
            Test.setCurrentPage(cpBOCAToProspect);

            cpbocaToProspectController.init();

            cpBOCAToProspect = Page.CPBOCAToProspect;
            cpBOCAToProspect.getParameters().put('bocaToProspectConfirm', 'false');
            Test.setCurrentPage(cpBOCAToProspect);

            cpbocaToProspectController.init();

            Test.stopTest();

        }

    }

}