src/objects/BOCA_IDs__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>IDs for orgs and email templates related to BOCA</description>
    <label>BOCA IDs</label>
</CustomObject>

src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Tagline__c</fullName>
        <description>Branded Tagline for This Program</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Tagline</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Template_ID__c</fullName>
        <description>Custom email template id</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the id of the custom email template for this BOCA resource</inlineHelpText>
        <label>Email Template ID</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISO_code__c</fullName>
        <label>ISO code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>en_ca</fullName>
                </value>
                <value>
                    <fullName>en_us</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>fr_ca</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Display Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Sell_Sheets__c</fullName>
        <description>Program specific information</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Program specific marketing information</inlineHelpText>
        <label>Program Sell Sheets</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SideBar__c</fullName>
        <description>HTML of BOCA sidebar</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SideBar</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Side_Panel_Title__c</fullName>
        <description>Sidebar Panel Title</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Side Panel Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Revolver</fullName>
        <active>true</active>
        <description>A Contact Type For Revolver Records</description>
        <label>Revolver</label>
    </recordTypes>
</CustomObject>

src/objects/OnlineApplicationOffer__c.object
<CustomObject>
    <description>Forseva Online Application Project</description>
    <fields>
        <fullName>Application_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BOCA_Default_Offer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BOCA Default Offer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete_Later_Text__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The text served to the customer if they click the &quot;Save and Complete Later&quot; button.</inlineHelpText>
        <label>Complete Later Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disclosure__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Disclosure</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EchoSign_User_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This must be the email (login ID) for a valid user associated with your EchoSign account.</inlineHelpText>
        <label>EchoSign User Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Online Application Offers</relationshipLabel>
        <relationshipName>Online_Application_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions_Version__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This must match the attached file name EXACTLY.  The attached file must be a valid HTML file with a file extension of &apos;html&apos;.</inlineHelpText>
        <label>Terms and Conditions Version</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Online Application Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Online Application Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Postcode__c.object
<CustomObject>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Analytics_Body_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analytics - Body Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Analytics_Head_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for google analytics code</inlineHelpText>
        <label>Analytics - Head Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Auto_Send_BOCA_to_Siebel__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Send BOCA to Siebel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BOCA_Type__c</fullName>
        <label>BOCA Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fuel Card</fullName>
                    <default>true</default>
                    <label>Fuel Card</label>
                </value>
                <value>
                    <fullName>Revolver Card</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>OTR</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 2</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <description>Branded heading for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Long_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Long Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Brand_Tagline__c</fullName>
        <description>Branded tagline for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Tagline</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Email_Header_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>URL to wexhosted for this program&apos;s email header</inlineHelpText>
        <label>Custom Email Header URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Template__c</fullName>
        <label>Form Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditApp_Revolver</fullName>
                </value>
                <value>
                    <fullName>WexBOCA</fullName>
                </value>
                <value>
                    <fullName>OTRBOCA</fullName>
                </value>
                <value>
                    <fullName>wexU</fullName>
                </value>
                <value>
                    <fullName>WexBOCA2</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preferred_Language_Indicator__c</fullName>
        <label>Preferred Language Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ENG</fullName>
                </value>
                <value>
                    <fullName>ENU</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Program Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>GU Fleet Card</fullName>
                </value>
                <value>
                    <fullName>SP Fleet Card</fullName>
                </value>
                <value>
                    <fullName>SG Fleet Card</fullName>
                </value>
                <value>
                    <fullName>HK Fleet Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SideBar__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SideBar</label>
        <length>80000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Side_Panel_Title__c</fullName>
        <description>Title for left panel on BOCA</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a title to appear above left panel on BOCA layout</inlineHelpText>
        <label>Side Panel Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_C__c</fullName>
        <description>Generally static T&amp;C doc for bottom of BOCA, will default to the WEX BOCA but FlexCard should use the BOCA_TC</description>
        <inlineHelpText>Generally static T&amp;C doc for bottom of BOCA, will default to the WEX BOCA but FlexCard should use the BOCA_TC</inlineHelpText>
        <label>TNC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BLANK_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC</fullName>
                    <default>true</default>
                    <label>BOCA_TNC</label>
                </value>
                <value>
                    <fullName>FLEX_BOCA_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_FEE_699</fullName>
                </value>
                <value>
                    <fullName>BOCA_GETT_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Chevron</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Shell</fullName>
                </value>
                <value>
                    <fullName>CPBOCATNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_ShellSmallBusiness</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_ShellPlus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_Pricing_Data_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Upload Pricing Data Flag</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OTRBOCAToProspectTest.cls
@isTest
public class OTRBOCAToProspectTest {
    
    @testSetup 
    static void setupData(){
        
        // Revisit this later..
        BOCA_IDS__C bocaId = BOCAtestDataUtility.getBOCAids();
        insert bocaId;
        
        Account offerAccount = new Account();
        offerAccount.Name ='TestAccount-01';
        
        insert offerAccount;
        
        OnlineApplicationOffer__c onlineApplicationOffer = new OnlineApplicationOffer__c();
        onlineApplicationOffer.Name = 'TestOffer-01';
        onlineApplicationOffer.Application_Title__c = 'TestTitle';
        onlineApplicationOffer.Complete_Later_Text__c = 'Test';
        onlineApplicationOffer.EchoSign_User_Email__c = 'test@test.com';
        onlineApplicationOffer.Terms_and_Conditions_Version__c = 'TestVersion-01';
        onlineApplicationOffer.BOCA_Default_Offer__c = true;
        onlineApplicationOffer.Disclosure__c = 'Test';
        
        insert onlineApplicationOffer;
        
        Program__c program = new Program__c();
        
        program.Name = 'OTRTestBOCA';
        program.Form_Template__c = 'OTRBOCA';
        program.Brand_Short_Name__c = 'OTR';
        program.Preferred_Language_Indicator__c = 'ENU';
        program.Custom_Email_Header_URL__c = 'http://www.wexhosted.com/email/revolver/header_wexRevolver.jpg';
        program.Brand_Heading__c = 'Time is money. Use WEX and save both.';
        program.Brand_Long_Name__c = 'OTR Test BOCA';
        program.Upload_Pricing_Data_Flag__c = false;
        program.Auto_Send_BOCA_to_Siebel__c = false;
        program.T_C__c = 'WEX_BOCA_TNC';
        program.Analytics_Body_Block__c = '';
        program.Analytics_Head_Block__c = '';
        program.Brand_Color_1__c = '#ccc';
        program.Brand_Color_2__c = '#fff';
        program.BOCA_Type__c = 'OTR';
        
        insert program;
        
        onlineApplicationOffer.Program__c = program.Id;
        
        upsert onlineApplicationOffer;
        
        // Setup Attachments
        Attachment cardImage = new Attachment();
        cardImage.Name = 'ui-credit-card.png';
        Blob cardImageBlob = Blob.valueOf('Unit Test Attachment Body');
        cardImage.body = cardImageBlob;
        cardImage.parentId = program.Id;
        upsert cardImage;
        
        Attachment logo = new Attachment();
        logo.Name = 'ui-logo.png';
        Blob logoBlob = Blob.valueOf('Unit Test Attachment Body');
        logo.body = logoBlob;
        logo.parentId = program.Id;
        upsert logo;
        
        Boca_Res__c brandingUtility = new Boca_Res__c();
        brandingUtility.Email_Template_ID__c = '00X70000001EfPG';
        brandingUtility.Brand_Heading__c = 'OTR Test Heading';
        brandingUtility.Brand_Tagline__c = 'OTR Test Tagline';
        brandingUtility.ISO_code__c = 'en_us';
        brandingUtility.Program__c = program.id;
        brandingUtility.Side_Panel_Title__c = 'OTR Test Sidebar Title';
        brandingUtility.SideBar__c = 'OTR Test Sidebar';
        brandingUtility.Program_Name__c = program.Name;
        brandingUtility.Name = 'OTRTest';
        brandingUtility.Program_Sell_Sheets__c = 'www.sellsheet.com';
        
        insert brandingUtility;
        
        PostCode__c postalCode = new PostCode__c();
        postalCode.State__c = 'ME';
        postalCode.Postcode__c = '4106';
        insert postalCode;
        
        Profile profile = [SELECT Id FROM Profile WHERE Name = 'IS Sales']; 
        
        User user = new User(Alias = 'tUse', Email='stanTestuser@wexinc.com', 
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = profile.Id, 
                             TimeZoneSidKey='America/Los_Angeles', UserName='stanarduser@wexinc.com');
        
        insert user;
        
        User integrationUser = [SELECT Id FROM User WHERE Alias = 'sinte'];
        
        System.runAs(user) {
            
            Id recordTypeId = Schema.Sobjecttype.Opportunity.getRecordTypeInfosByName().get('Fleet Card').getRecordTypeId();
            
            Opportunity opportunity = new Opportunity();
            
            opportunity.Name = 'TestOpp';
            opportunity.CloseDate = Date.newinstance(2099,1,1);
            opportunity.StageName = '1) Qualified';
            opportunity.Fleet_Size__c = 10;
            opportunity.OwnerId = user.Id;
            opportunity.SourceSystem__c = 'test';
            opportunity.RecordTypeId = recordTypeId;
            opportunity.Fueling_Methos__c = 'BP';
            opportunity.Number_of_18_Wheelers__c = 10;
            opportunity.F1_Account__c = '123456';
            
            insert opportunity;
            
            Contact contact = new Contact();
            
            contact.FirstName = 'Tester';
            contact.LastName = 'Tester Last';
            contact.Email = 'Tester@UnitTest.com';
            
            insert contact;
            
            OpportunityContactRole opportunityContact = new OpportunityContactRole(contactId = contact.id, isPrimary = true, OpportunityId = opportunity.id);
            
            insert opportunityContact;
            
        }
        
    }
    
    @isTest
    static void testBOCAToProspectErrorHandler() {
        
        User integrationUser = [SELECT Id FROM User WHERE Alias = 'sinte'];
        
        System.runAs(integrationUser) {
            
            Test.startTest();
            
            TestUtils.enable_isRunningTest = true;
            
            Opportunity opportunity = [SELECT Id FROM Opportunity WHERE Name = 'TestOpp'];
            
            // Test without opportunity to test error handling
            PageReference otrBocaToProspectPage = Page.OTRBOCAToProspect;
            otrBocaToProspectPage.getParameters().put('id', '');
            Test.setCurrentPage(otrBocaToProspectPage);
            
            Apexpages.StandardController standardController = new ApexPages.StandardController(opportunity);
            OTRBOCAToProspectController otrBocaToProspectController = new OTRBOCAToProspectController(standardController);
            
            otrBocaToProspectController.init();
            
            System.assertEquals(true, otrBocaToProspectController.hasError);
            
            Test.stopTest();
            
        }
        
    }
    
    @isTest
    static void testBOCAToProspect() {
        
        User integrationUser = [SELECT Id FROM User WHERE Alias = 'sinte'];
        
        System.runAs(integrationUser) {
            
            Test.startTest();
            
            TestUtils.enable_isRunningTest = true;
            
            Opportunity opportunity = [SELECT Id FROM Opportunity WHERE Name = 'TestOpp'];
            
            // Test with opportunity
            PageReference otrBocaToProspectPage = Page.OTRBOCAToProspect;
            otrBocaToProspectPage.getParameters().put('id', opportunity.Id);
            Test.setCurrentPage(otrBocaToProspectPage);
            
            Apexpages.StandardController standardController = new ApexPages.StandardController(opportunity);
            OTRBOCAToProspectController otrBocaToProspectController = new OTRBOCAToProspectController(standardController);
            
            otrBocaToProspectController.init();
            
            System.assert(otrBocaToProspectController.availablePrograms != null);
            System.assert(otrBocaToProspectController.availableOffers != null);
            
            Program__c program = [SELECT Id FROM Program__c LIMIT 1];
            
            OnlineApplicationOffer__c offer = [SELECT Id FROM OnlineApplicationOffer__c WHERE Program__c =: program.Id LIMIT 1];
            
            otrBOCAToProspectController.selectedProgram = program.Id;
            otrBOCAToProspectController.selectedOffer = offer.Id;
            
            URLgenAttachmentLookupController ugalc = new URLgenAttachmentLookupController();
            System.assert(ugalc.folders != null);
            ugalc.displayDocuments();
            ugalc.clearSearch();
            
            Document tempDocument = new Document();
            tempDocument.Name = 'info.pdf';
            Blob tempDocumentBlob = Blob.valueOf('Unit Test Attachment Body');
            tempDocument.body = tempDocumentBlob;
            tempDocument.FolderId = UserInfo.getUserId();
            insert tempDocument;
            
            otrBocaToProspectController.attachments = '["' + tempDocument.Id + '"]';

            PageReference otrBocaToProspectRedirect = otrBocaToProspectController.bocaToProspect();

            System.assertNotEquals(null, otrBocaToProspectController.salesRepName);
            System.assertNotEquals(null, otrBocaToProspectController.resend);

            otrBocaToProspectController.resendBOCAToProspect(); 
            
            // Test the components
            OTRBOCAToProspectComponentController otrBocaToProspectComponentController = new OTRBOCAToProspectComponentController();
            
            otrBocaToProspectComponentController.bocaToProspectId = otrBocaToProspectController.bocaToProspect.Id;
            
            //System.assertNotEquals(null, otrBocaToProspectComponentController.bocaToProspect);
            //System.assertNotEquals(null, otrBocaToProspectComponentController.primaryBrandingCard);
            //System.assertNotEquals(null, otrBocaToProspectComponentController.pgValue);
            //System.assertNotEquals(null, otrBocaToProspectComponentController.primaryBrandingUtility);
            
            // Test the reminder function
            otrBocaToProspectPage = Page.OTRBOCAToProspect;
            otrBocaToProspectPage.getParameters().put('bocaToProspectId', otrBocaToProspectController.bocaToProspect.Id);
            Test.setCurrentPage(otrBocaToProspectPage);
            
            otrBocaToProspectController.init();
            
            otrBocaToProspectRedirect = otrBocaToProspectController.bocaToProspectReminder();
            
            Test.stopTest();
            
        }
        
    }
    
}