src/objects/BOCA_res__c.object
<CustomObject>
    <description>Attaches to the Program object. Holds branding info for various languages.</description>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>BOCA_res</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Branding Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Branding Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branding Utilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CP_Application_Request__c.object
<CustomObject>
    <description>Corporate Payments BOCA application request</description>
    <fields>
        <fullName>Confirmation_Number__c</fullName>
        <formula>Opportunity__r.Opportunity_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Confirmation Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>CorporatePayments Application Requests</relationshipLabel>
        <relationshipName>CorporatePayments_Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CorporatePayments Application Request</label>
    <nameField>
        <displayFormat>Application-{YYYY}{MM}{0}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CorporatePayments Application Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CPBOCAConfirmationController.cls
public class CPBOCAConfirmationController {

    public CP_Application_Request__c creditApp { get; set; }
    
    public Program__c program { get; set; }
    
    public BOCA_res__c brandingUtility { get; set; }
    
    public String programParameter {
        get {
            return ApexPages.CurrentPage().getParameters().get('pgm');
        }
    }
    
    public String creditAppId {
        get {
            return ApexPages.CurrentPage().getParameters().get('id');
        }
    }
    
    public String languageCode {
        get {
            if(ApexPages.CurrentPage().getParameters().get('lang') != null) {
                return ApexPages.CurrentPage().getParameters().get('lang');
            }
            return 'en_us';
        }
    }
    
    // Get the branding logo
    public Id brandingLogo { get; set; }
    
    // Get the branding card
    public Id brandingCard { get; set; }
    
	public PageReference init() {
        
        if(programParameter != null) {

            if(UserInfo.getSessionId() != null && !TestUtils.isRunningTest()) {
                PageReference bocaAttachment = Page.BOCAAttachment;
                bocaAttachment.getParameters().put('pgm', programParameter);
                bocaAttachment.getParameters().put('applicationId', creditAppId);
                return bocaAttachment;
            }

            Id programId = WexBrandingController.getProgramIdByBrandShortName(programParameter);
            
            if(programId != null) {
                
                program = WexBrandingController.getProgram(programId);
                
                Id brandingUtilityId = WexBrandingController.getBrandingUtilityByProgramId(programId, languageCode);
                
                if(brandingUtilityId != null) {
                
                	brandingUtility = WexBrandingController.getBrandingUtility(brandingUtilityId);
                    
                }
                
                brandingLogo = WexBrandingController.getLogoId(programId);
                
                brandingCard = WexBrandingController.getCreditCardImageId(programId);
                
            }
            
        }
        
        if(creditAppId != null) {
            
            List<CP_Application_Request__c> creditApps = [SELECT Id, Confirmation_Number__c FROM CP_Application_Request__c WHERE Id =: creditAppId];
            
            if(creditApps.size() == 1) {
                
                creditApp = creditApps[0];
                
            }
            
        }

        return null;
        
    }
    
}