src/objects/Campaign_Pricing__c.object
<CustomObject>
    <description>Object for storing pricing data</description>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <description>Psoft Program Relationship Code</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Psoft Program Relationship Code</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contract_margin__c</fullName>
        <label>Contract Margin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <default>true</default>
                    <label>Y</label>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contract_rate_pct__c</fullName>
        <label>Contract Rate Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>coup_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Coupon Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>days_to_pay__c</fullName>
        <label>Days to Pay</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fixed_late_fee__c</fullName>
        <label>Fixed Late Fee</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>late_fee_type__c</fullName>
        <description>Late fee type (P = percentage, F = fixed)</description>
        <label>Late Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>minimum_payment_percentage__c</fullName>
        <description>Minimum Payment Percentage</description>
        <label>Minimum Payment Percentage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>nbr_billing_cyles__c</fullName>
        <description># of Billing Cycles Promotional Rate is valid for (if one exists for the coupon)</description>
        <encryptionScheme>None</encryptionScheme>
        <label># of Billing Cycles Promo Rate is valid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>over_limit_fee__c</fullName>
        <label>Over Limit Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>paper_delivery_fee__c</fullName>
        <label>Paper Delivery Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pct_late_fee__c</fullName>
        <label>Percent Late Fee</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pen_rate_pct__c</fullName>
        <label>Penalty Percentage Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>penalty_margin__c</fullName>
        <label>Penalty Margin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <default>true</default>
                    <label>Y</label>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>penalty_rate_ceiling__c</fullName>
        <label>Penalty Rate Ceiling</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>prime_rate__c</fullName>
        <description>Most recent Prime Rate</description>
        <label>Prime Rate</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>prime_rate_effective_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Prime Rate Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>promo_add_prime__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Promo Add Prime</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>promo_periods__c</fullName>
        <label>Promo Periods</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>promotional_rate__c</fullName>
        <label>Promotional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>return_payment_fee__c</fullName>
        <label>Return Payment Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>risk_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Risk Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Pricing</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PricingController.cls
public class PricingController{

    public static Set<Campaign_Pricing__c> pricingController(Map<String, String> codes){
        
        Set <Campaign_Pricing__c> result = new Set<Campaign_Pricing__c>();

        //list for the XML nodes
        List<TG_XmlNode> recs = new List<TG_XmlNode>();
        //Check if the caller is test
        UnitTestUtil oUtil = UnitTestUtil.getInstance();
        if (oUtil.IsUnitTesting) {
            result.add(elementToResult(oUtil.MockResponse));
        }
        else{
            for(String prog : codes.keySet()){
                String coupon = codes.get(prog);
                String psCode = prog;
                SYSTEM.debug('coupon'+coupon);
                SYSTEM.debug('psCode' + psCode);
                
                Http h = new Http();
                httpRequest req = createRequest(psCode, coupon);
                
                HttpResponse res = h.send(req);
                
                String requestXml = res.getBody();

                TG_XmlDom dom = new TG_XmlDom(requestXml);
                TG_XmlNode root = dom.root;	
                
                recs.addAll(root.getElementsByTagName('pric:CouponPricing'));
				        if(recs.size() != 0){
                    for(TG_XmlNode rec : recs){
                        SYSTEM.debug('rec'+rec);
                        result.add(elementToResult(rec));
                    }
                }
       
             }//end for
            
        }
        
         return result;
   	
    }

    //encapsulate callout request for testing
    public static HttpRequest createRequest(String code, String coupon){
        String psCode = code;
        //String coupon = coupon;
        Http h = new Http();
        httpRequest req = new HttpRequest();
        String body = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pric="http://xmlns.wexinc.com/Internal/BOD/Price" xmlns:com="http://xmlns.wexinc.com/Internal/BOD/Common"><soapenv:Header/><soapenv:Body><pric:GetPricingRateByCouponInputMsg><pric:Source><!--Optional:--><com:Name>?</com:Name><!--Optional:--><com:EntityType>?</com:EntityType><!--Optional:--><com:EntityId></com:EntityId></pric:Source><pric:RelationCode>'+psCode+'</pric:RelationCode><pric:CouponCode>'+coupon+'</pric:CouponCode></pric:GetPricingRateByCouponInputMsg></soapenv:Body></soapenv:Envelope>';

        req.setMethod('POST');
        req.setEndpoint('https://wexfleet.wexapi.com/pricingservice');
        req.setHeader('Accept-Encoding', 'gzip,deflate');
        req.setHeader('Content-Type', 'text/xml;charset=UTF-8');
        req.setHeader('SOAPAction', '"GetPricingRateByCoupon"');
        req.setHeader('Content-Length', '724');
//                req.setHeader('Host', 'webservices.wexinc.com');
        req.setHeader('Connection', 'Keep-Alive');
        req.setHeader('User-Agent', 'Apache-HttpClient/4.1.1: (java 1.5)');
        req.setTimeout(120000);
        req.setBody(body);


        return req;
    }

    public static Campaign_Pricing__c elementToResult(TG_XmlNode node){
        if(node.getElementByTagName('pric:RiskCode').textContent == ''){
            node.getElementByTagName('pric:RiskCode').textContent = 'No';
        }
        Campaign_Pricing__c price = new Campaign_Pricing__c();
        price.prime_rate_effective_date__c = date.valueOf(node.getElementByTagName('pric:PrimeRateDate').textContent);
        price.Name = node.getElementByTagName('pric:CouponCode').textContent+' Risk-'+ node.getElementByTagName('pric:RiskCode').textContent;
        price.coup_code__c = node.getElementByTagName('pric:CouponCode').textContent;
        price.Peoplesoft_rel_code__c = node.getElementByTagName('pric:RelationCode').textContent;
        price.risk_code__c =node.getElementByTagName('pric:RiskCode').textContent;
        price.prime_rate__c = double.valueOf(node.getElementByTagName('pric:PrimeRate').textContent);
        price.nbr_billing_cyles__c = node.getElementByTagName('pric:PromoPeriods').textContent;
        price.promo_periods__c = integer.valueOf(node.getElementByTagName('pric:PromoPeriods').textContent);
        price.promotional_rate__c = double.valueOf(node.getElementByTagName('pric:PromoRate').textContent);
        price.promo_add_prime__c = node.getElementByTagName('pric:PromoAddPrime').textContent;
        price.contract_rate_pct__c = double.valueOf(node.getElementByTagName('pric:ContractRate').textContent);
        price.contract_margin__c =  node.getElementByTagName('pric:PenaltyAddPrime').textContent;
        price.pen_rate_pct__c= double.valueOf(node.getElementByTagName('PenaltyRate').textContent);
        price.penalty_margin__c = node.getElementByTagName('PenaltyAddPrime').textContent;
        price.days_to_pay__c = integer.valueOf(node.getElementByTagName('DaysToPay').textContent);
        price.late_fee_type__c = node.getElementByTagName('LateFeeType').textContent;
        price.pct_late_fee__c = double.valueOf(node.getElementByTagName('LatePctFee').textContent);
        price.fixed_late_fee__c = double.valueOf(node.getElementByTagName('FixedLateFee').textContent);
        price.return_payment_fee__c = double.valueOf(node.getElementByTagName('RepaymentFee').textContent);
        price.over_limit_fee__c = double.valueOf(node.getElementByTagName('OverLimitFee').textContent);
        price.paper_delivery_fee__c = double.valueOf(node.getElementByTagName('PaperDeliveryFee').textContent);
        price.penalty_rate_ceiling__c = double.valueOf(node.getElementByTagName('PenaltyRateCeiling').textContent);
        price.minimum_payment_percentage__c = double.valueOf(node.getElementByTagName('MinPayPct').textContent);
        SYSTEM.debug('new pricing' + price);
        return price;
    }
    
    
    
    
}