src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates default campaign for this program.</description>
        <label>BOCA Default Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms and Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Partner__c.object
<CustomObject>
    <description>Object to link partner programs together</description>
    <label>Partner</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The partner this Program belongs to, which is used for grouping programs together.</description>
        <inlineHelpText>The partner this Program belongs to, which is used for grouping programs together.</inlineHelpText>
        <label>Partner</label>
        <referenceTo>Partner__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/CampaignProgramcStatsTriggerTest.cls
@isTest
private class CampaignProgramcStatsTriggerTest {

    static testMethod void testTrigger() {
        //   try {
        //       Campaign_Program__c o = new Campaign_Program__c();
        //       insert o;

        //       System.assertNotEquals(null, o);
        //   }
        //   catch(Exception e) {
        //       List<Campaign_Program__c> l = [SELECT Id from Campaign_Program__c LIMIT 1];
        //       update l;
        //       System.assertNotEquals(null, l);
        //   }

        UtilityTestLoader.setAutomation(false);

        Partner__c part1 = new Partner__c(Name = 'partner1');
        insert part1;

        Program__c program1 = new Program__c();
        program1.Name = 'test prog1' ;
        program1.Brand_Short_Name__c = 'test1';
        program1.Partner__c = part1.Id;

        insert program1;

        Campaign campaign = new Campaign();
        campaign.Coupon_Code__c = 'TEST1';
        campaign.Name = 'TestCampaign';
        campaign.Type = 'Online Form';
        campaign.Status = 'In Progress';
        campaign.Drop_Date__c = date.today();
        campaign.EndDate = date.today();
        campaign.CurrencyIsoCode = 'USD';
        campaign.IsActive = true;

        insert campaign;

        Campaign_Program__c campaignProgram1 = new Campaign_Program__c();
        campaignProgram1.Name = 'test campaign program1';
        campaignProgram1.Campaign__c = campaign.Id;
        campaignProgram1.Program__c = program1.Id;
        campaignProgram1.Terms_and_Conditions__c = 'Test T&C';
        campaignProgram1.Default__c = true;

        insert campaignProgram1;

        List<Campaign_Program__c> cpList = [SELECT Id FROM Campaign_Program__c WHERE Id =: campaignProgram1.Id];

        System.assertEquals(1, cpList.size());

        campaignProgram1.Name = 'test campaign program2';
        update campaignProgram1;

        cpList = [SELECT Id FROM Campaign_Program__c WHERE Name = 'test campaign program2'];

        System.assertEquals(1, cpList.size());
    }
}