src/objects/Campaign_Pricing__c.object
<CustomObject>
    <description>Object for storing pricing data</description>
    <fields>
        <fullName>coup_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Coupon Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Pricing</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUpdateCoupon.cls
@IsTest
public class TestUpdateCoupon{
    
//    static testmethod void insertCampaignPricing(){
//
//        Campaign testCampaign = new Campaign();
//
//        testCampaign.Name = 'TestCampaign';
//        testCampaign.Coupon_Code__c = 'FFF';
//        testCampaign.IsActive = true;
//
//        insert testCampaign;
//
//        Campaign_Pricing__c cmp= new Campaign_Pricing__c();
//
//        cmp.Name = 'TestCampaignPricing';
//        cmp.coup_code__c = 'FFF';
//
//        insert cmp;
//
//        Campaign_Pricing__c cmpInActive = new Campaign_Pricing__c();
//
//        cmpInActive.Name = 'TestCampaignPricing';
//        cmpInActive.coup_code__c = 'FAA';
//
//        insert cmpInActive;
//
//    }

}