src/objects/Campaign_Pricing__c.object
<CustomObject>
    <description>Object for storing pricing data</description>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <description>Psoft Program Relationship Code</description>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Psoft Program Relationship Code</label>
        <length>24</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contract_margin__c</fullName>
        <label>Contract Margin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <default>true</default>
                    <label>Y</label>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contract_rate_pct__c</fullName>
        <label>Contract Rate Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>nbr_billing_cyles__c</fullName>
        <description># of Billing Cycles Promotional Rate is valid for (if one exists for the coupon)</description>
        <encryptionScheme>None</encryptionScheme>
        <label># of Billing Cycles Promo Rate is valid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Campaign Pricing</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates default campaign for this program.</description>
        <label>BOCA Default Campaign</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Terms and Conditions</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Analytics_Body_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analytics - Body Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Analytics_Head_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for google analytics code</inlineHelpText>
        <label>Analytics - Head Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>BOCA_Type__c</fullName>
        <label>BOCA Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fuel Card</fullName>
                    <default>true</default>
                    <label>Fuel Card</label>
                </value>
                <value>
                    <fullName>Revolver Card</fullName>
                </value>
                <value>
                    <fullName>Factoring</fullName>
                </value>
                <value>
                    <fullName>OTR</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 2</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Folder_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Folder Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Heading__c</fullName>
        <description>Branded heading for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Heading</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Long_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Long Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Brand_Tagline__c</fullName>
        <description>Branded tagline for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Tagline</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Confirmation_Info__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for confirmation page related text, urls, etc.</inlineHelpText>
        <label>Confirmation Info</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Custom_Email_Header_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>URL to wexhosted for this program&apos;s email header</inlineHelpText>
        <label>Custom Email Header URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Template__c</fullName>
        <label>Form Template</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditApp_Revolver</fullName>
                </value>
                <value>
                    <fullName>WexBOCA</fullName>
                </value>
                <value>
                    <fullName>OTRBOCA</fullName>
                </value>
                <value>
                    <fullName>wexU</fullName>
                </value>
                <value>
                    <fullName>WexBOCA2</fullName>
                </value>
                <value>
                    <fullName>CPBOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Inside_Sales_Phone_Number__c</fullName>
        <description>Phone number of inside sales for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Inside Sales Phone Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Person_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for liver person code</inlineHelpText>
        <label>Live Person Code</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Peoplesoft_rel_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Peoplesoft Rel Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_BOCA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish BOCA</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Section_Titles__c</fullName>
        <description>BOCA Section Headers</description>
        <label>Section Titles</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tell Us About Your Business</fullName>
                </value>
                <value>
                    <fullName>Billing Contact Information</fullName>
                </value>
                <value>
                    <fullName>Promotional Information</fullName>
                </value>
                <value>
                    <fullName>Statement &amp; Report Delivery</fullName>
                </value>
                <value>
                    <fullName>Tell Us About Yourself</fullName>
                </value>
                <value>
                    <fullName>Authorization</fullName>
                </value>
                <value>
                    <fullName>Terms &amp; Conditions</fullName>
                </value>
                <value>
                    <fullName>Business Information</fullName>
                </value>
                <value>
                    <fullName>Billing Information</fullName>
                </value>
                <value>
                    <fullName>Additional Information</fullName>
                </value>
                <value>
                    <fullName>Authorized Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SideBar__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>SideBar</label>
        <length>80000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Side_Panel_Title__c</fullName>
        <description>Title for left panel on BOCA</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a title to appear above left panel on BOCA layout</inlineHelpText>
        <label>Side Panel Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>T_C__c</fullName>
        <description>Generally static T&amp;C doc for bottom of BOCA, will default to the WEX BOCA but FlexCard should use the BOCA_TC</description>
        <inlineHelpText>Generally static T&amp;C doc for bottom of BOCA, will default to the WEX BOCA but FlexCard should use the BOCA_TC</inlineHelpText>
        <label>TNC</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BLANK_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC</fullName>
                    <default>true</default>
                    <label>BOCA_TNC</label>
                </value>
                <value>
                    <fullName>FLEX_BOCA_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_FEE_699</fullName>
                </value>
                <value>
                    <fullName>BOCA_GETT_TNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Chevron</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_Shell</fullName>
                </value>
                <value>
                    <fullName>CPBOCATNC</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_ShellSmallBusiness</fullName>
                </value>
                <value>
                    <fullName>BOCA_TNC_ShellPlus</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Template__c</fullName>
        <inlineHelpText>disable this once new BOCA code is done</inlineHelpText>
        <label>Form Template OLD</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CreditApp_Revolver</fullName>
                </value>
                <value>
                    <fullName>WexBOCA</fullName>
                </value>
                <value>
                    <fullName>creditApp_noPG</fullName>
                </value>
                <value>
                    <fullName>eAppBOCA</fullName>
                </value>
                <value>
                    <fullName>OTR_BOCA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Upload_Pricing_Data_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Upload Pricing Data Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>url__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>url</label>
        <type>Url</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/URL__c.object
<CustomObject>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL of the link</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The URL of the link</inlineHelpText>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/WEXBrandUtility.cls
public class WEXBrandUtility {
   
    public Program__c setProgramFromURL(String brandUrlParam, String url){
        
        List<Program__C> programs;
 		
        system.debug('brandUrlParam in wexbrandutility is: ' + brandUrlParam);
        if (brandUrlParam != null){
        	programs = [select Name, Brand_Short_Name__c, Brand_Folder_Name__c, Brand_Long_Name__c, T_C__c, SideBar__c, Analytics_Body_Block__c, Analytics_Head_Block__c, Brand_Heading__c, Custom_Email_Header_URL__c,
                         Brand_Tagline__c, Brand_Color_1__c, Brand_Color_2__c, Peoplesoft_rel_code__c, Upload_Pricing_Data_Flag__c, Publish_BOCA__c, Confirmation_Info__c, Inside_Sales_Phone_Number__c,
                         Live_Person_Code__c, form_template__c,  Side_Panel_Title__c, toLabel(Section_Titles__c), BOCA_Type__c
                         from program__c 
                         where Brand_Short_Name__c = :brandUrlParam ];    
        }
        
        if (programs == null || programs.size() == 0 || programs[0].Brand_Short_Name__c == ''){
            programs = [select Name, Brand_Short_Name__c, Brand_Folder_Name__c, Brand_Long_Name__c, T_C__c, SideBar__c, Analytics_Body_Block__c, Analytics_Head_Block__c, Brand_Heading__c, Custom_Email_Header_URL__c,
                         Brand_Tagline__c, Brand_Color_1__c, Brand_Color_2__c, Peoplesoft_rel_code__c, Upload_Pricing_Data_Flag__c, Publish_BOCA__c, Confirmation_Info__c, Inside_Sales_Phone_Number__c,
                         Live_Person_Code__c, form_template__c, Side_Panel_Title__c, toLabel(Section_Titles__c), BOCA_Type__c
                          from program__c 
                         where url__c = :url ];   
        }  
        
        if (programs == null || programs.size() == 0 || programs[0].Brand_Short_Name__c == ''){
        	//error - no program found
        }
        
		if (programs != null && programs.size() > 0)        
        	return programs[0];  
        else 
            return null;
    }
    
    public Campaign_Program__c getCampaignProgram(Program__c pgm, Campaign camp){
        
        List<Campaign_Program__c> cpList = [
            select id, Default__c, Terms_and_Conditions__c, campaign__c
        	from Campaign_Program__c
            where program__c = :pgm.Id
            and campaign__c = :camp.Id
        ];
        
        //If both the program and campaign are valid but aren't tied to each other
        //then get the default one for the program
        if (cpList.size() == 0){
        	return getDefaultCampaignProgram(pgm);
        }
        
        return cpList[0];
    }
    public Campaign_Program__c getDefaultCampaignProgram(Program__c pgm){
        List<Campaign_Program__c> cpList = [
            select id, Default__c, Terms_and_Conditions__c, campaign__c
        	from Campaign_Program__c
            where program__c = :pgm.Id
            and Default__c = true
        ];
        return cpList[0];
    }
    /*
    public Terms_and_Conditions__c getTermsAndConditions(String couponCodeUrlParam, Program__c pgm){

        List<Terms_and_Conditions__c> tAndC;
        List<Campaign> camp = new List<Campaign>();
         
        //If we come in with a coupon code then get use that to get the campaign program
        if (couponCodeUrlParam != '' && couponCodeUrlParam != null){
            
            camp = [select id from campaign where Coupon_Code__c = :couponCodeUrlParam];
            
            SYSTEM.debug('CAMPAIGN: ' + camp + 'for this one: ' + couponCodeUrlParam);
            
            if (camp != null && camp.size() > 0){
                tAndC = [
                    select id, T_C_Text__c, Campaign__c 
                    from Terms_and_Conditions__c
                    where Campaign__c = :camp[0].id
                    and Program__c = :pgm.id
                ];
            }
        } 

        //if no coupon code came in .. or the coupon code isnt set up for the specific program, 
        //then get the default campaign_program for the program
        if (couponCodeUrlParam == '' || couponCodeUrlParam == null || tAndC == null || tAndC.size() == 0){
          	//get the default campaign_program for the program
        	tAndC = [
                select id, Campaign__c , T_C_Text__c 
                from Terms_and_Conditions__c 
                where Program__c = :pgm.id
                and Is_Default__c = true
            ];  
            
        }            
        
        if (tAndC.size() > 0)
        	return tAndC[0];
        else 
            return null;
        
	}
    */ 
    public String getCouponCode(Campaign_Program__c cp){
        if (cp == null) return null;
        
        List<Campaign> camp = [select Coupon_Code__c from campaign where id = :cp.Campaign__c];
        
        if (camp == null || camp.size() == 0) return null;
        
        return camp[0].Coupon_Code__c;        
    }
  
  public boolean isValidTemplateForProgram(String url, Program__c pgm){
		system.debug('template is: ' + pgm.Form_Template__c);
        system.debug('url is: ' + url);
        
        //TODO - figure out a better way of querying the url... possibly
        String template = pgm.Form_Template__c;
      	if(template == null){template = pgm.Template__c;}
            
            if (url.containsIgnoreCase(template)){
                return true;
            }
   
         
        return false;
    }

    public String getValidCouponCode(String ProgramId, String couponCode){
        if (ProgramId == null) return null;

		//Does this campaign exist?        
        List<Campaign> camp = [select Id, Coupon_Code__c from campaign where Coupon_Code__c = :couponCode];
        
        //Does this campaign exist for the program in focus?
        if (camp != null && camp.size() > 0){
            List<Campaign_Program__c> cp = [
                select campaign__c
                from Campaign_Program__c
                where program__c = :ProgramId
                and campaign__c = :camp[0].Id
            ];         
            
            if (cp.size() > 0){
                return camp[0].Coupon_Code__c;
            }
        }
        
        //else get the default coupon code for the program
        List<Campaign_Program__c> cp1 = [
            select campaign__c
            from Campaign_Program__c
            where program__c = :ProgramId
            and Default__c = true
        ]; 
        system.debug('cp1 Id: ' + cp1[0].Id );
        camp = [select Coupon_Code__c from campaign where Id = :cp1[0].campaign__c];
            
        return camp[0].Coupon_Code__c;
        
    } 
    
    public String getDefault(String ProgramId){
        Campaign_Program__c cp =  [select campaign__c from Campaign_Program__c where program__c =: ProgramId and Default__c = true];
        Campaign c = [select Coupon_Code__c from campaign where Id =: cp.Campaign__c];
        String code = c.Coupon_Code__c;
        return code;
    }
    
    public List<Campaign_Pricing__c> getPricing(String peoplesoft_rel_code, String couponCode){

        List<Campaign_Pricing__c> pricingList = [
            select 
                nbr_billing_cyles__c,contract_rate_pct__c,
                contract_margin__c, Contract_Rate_Type__c,
                coup_code__c, Coupon_Status__c,
                days_to_pay__c, fixed_late_fee__c,
                is_Active__c, late_fee_type__c,
                minimum_payment_percentage__c,over_limit_fee__c,
                paper_delivery_fee__c,pct_late_fee__c,
                pen_rate_pct__c, penalty_margin__c,
                penalty_rate_ceiling__c, Penalty_Rate_Type__c,
                prime_rate__c,prime_rate_effective_date__c,
                promo_add_prime__c, promo_periods__c,
                promotional_rate__c, Peoplesoft_rel_code__c,
                return_payment_fee__c, risk_code__c
            from Campaign_Pricing__c
            where Peoplesoft_rel_code__c = :peoplesoft_rel_code
        	and coup_code__c = :couponCode];
 		if(pricingList.size() > 0)return pricingList;
  		else return null;
    }
    
 
}