src/objects/Campaign_Pricing__c.object
<CustomObject>
    <description>Object for storing pricing data</description>
    <fields>
        <fullName>Contract_Rate_Type__c</fullName>
        <formula>IF(  ISPICKVAL(  contract_margin__c ,  &quot;Y&quot;) , &quot;Variable&quot;, &quot;Fixed&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Penalty_Rate_Type__c</fullName>
        <formula>IF(  ISPICKVAL( penalty_margin__c,  &quot;Y&quot;) , &quot;Variable&quot;, &quot;Fixed&quot;)</formula>
        <label>Penalty Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>contract_margin__c</fullName>
        <label>Contract Margin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <default>true</default>
                    <label>Y</label>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>contract_rate_pct__c</fullName>
        <label>Contract Rate Percent</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fixed_late_fee__c</fullName>
        <label>Fixed Late Fee</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>late_fee_type__c</fullName>
        <description>Late fee type (P = percentage, F = fixed)</description>
        <label>Late Fee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>F</fullName>
                </value>
                <value>
                    <fullName>P</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>nbr_billing_cyles__c</fullName>
        <description># of Billing Cycles Promotional Rate is valid for (if one exists for the coupon)</description>
        <encryptionScheme>None</encryptionScheme>
        <label># of Billing Cycles Promo Rate is valid</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>over_limit_fee__c</fullName>
        <label>Over Limit Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>paper_delivery_fee__c</fullName>
        <label>Paper Delivery Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>pct_late_fee__c</fullName>
        <label>Percent Late Fee</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>pen_rate_pct__c</fullName>
        <label>Penalty Percentage Rate</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>penalty_margin__c</fullName>
        <label>Penalty Margin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <default>true</default>
                    <label>Y</label>
                </value>
                <value>
                    <fullName>N</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>prime_rate_effective_date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Prime Rate Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>promo_periods__c</fullName>
        <label>Promo Periods</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>promotional_rate__c</fullName>
        <label>Promotional Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>return_payment_fee__c</fullName>
        <label>Return Payment Fee</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>risk_code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Risk Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Campaign Pricing</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WEXPricingHelper.cls
public class WEXPricingHelper {

    
    Public Map<String, String> getPricing(Campaign_Pricing__c cp){
        Map<String, String> pricing = new Map<String, String>();
        String rate = ' ';
        String penRate = ' ';
        String primeDate = ' ';
        String lateFee = ' ';
        String retFee = ' ';
        String paperFee = ' ';
        String ovrLimFee = ' ';
    
        
        
        //test condition for rate 
        if((cp.risk_code__c.equalsIgnoreCase('No')) && (cp.contract_margin__c.equalsIgnoreCase('Y')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Variable'))){
            rate = 'Prime + ' + cp.contract_rate_pct__c + '%';
        }
        if((cp.risk_code__c.equalsIgnoreCase('No')) && (cp.contract_margin__c.equalsIgnoreCase('N')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Fixed'))){
            rate = cp.contract_rate_pct__c + '%';
        }
        if((cp.risk_code__c.equalsIgnoreCase('7')) && (cp.contract_margin__c.equalsIgnoreCase('Y')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Variable'))){
            rate = 'Up to Prime + ' + cp.contract_rate_pct__c + '%';
        }
        if((cp.risk_code__c.equalsIgnoreCase('7')) && (cp.contract_margin__c.equalsIgnoreCase('N')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Fixed'))){
            rate = 'Up to ' + cp.contract_rate_pct__c + '%';
        }
        
        //test condition for penalty
        if((cp.risk_code__c.equalsIgnoreCase('No')) && (cp.penalty_margin__c.equalsIgnoreCase('Y')) && (cp.Penalty_Rate_Type__c.equalsIgnoreCase('Variable'))){
            penRate = 'Prime + ' + cp.pen_rate_pct__c + '%';
        }
        if((cp.risk_code__c.equalsIgnoreCase('No')) && (cp.penalty_margin__c.equalsIgnoreCase('N')) && (cp.Penalty_Rate_Type__c.equalsIgnoreCase('Fixed'))){
            penRate = cp.pen_rate_pct__c + '%';
        }
        if((cp.risk_code__c.equalsIgnoreCase('7')) && (cp.penalty_margin__c.equalsIgnoreCase('Y')) && (cp.Penalty_Rate_Type__c.equalsIgnoreCase('Variable'))){
            penRate = 'Up to Prime + ' + cp.pen_rate_pct__c + '%';
        }
        if((cp.risk_code__c.equalsIgnoreCase('7')) && (cp.penalty_margin__c.equalsIgnoreCase('N')) && (cp.Penalty_Rate_Type__c.equalsIgnoreCase('Fixed'))){
            penRate = 'Up to ' + cp.pen_rate_pct__c + '%';
        }
        
       //Test condition for Prime Rate Effective Date
        if((cp.contract_margin__c.equalsIgnoreCase('Y')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Variable')) && (cp.penalty_margin__c.equalsIgnoreCase('Y')) && 
           cp.Penalty_Rate_Type__c.equalsIgnoreCase('Variable')){
            primeDate = 'Variable rates are based on the Prime Rate as of ' + cp.prime_rate_effective_date__c.format();
        }
         if((cp.contract_margin__c.equalsIgnoreCase('Y')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Variable')) && (cp.penalty_margin__c.equalsIgnoreCase('N')) && 
           cp.Penalty_Rate_Type__c.equalsIgnoreCase('Fixed')){
            primeDate = 'Variable rates are based on the Prime Rate as of ' + cp.prime_rate_effective_date__c.format();
        }
         if((cp.contract_margin__c.equalsIgnoreCase('N')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Fixed')) && (cp.penalty_margin__c.equalsIgnoreCase('Y')) && 
           cp.Penalty_Rate_Type__c.equalsIgnoreCase('Variable')){
            primeDate = 'Variable rates are based on the Prime Rate as of  ' + cp.prime_rate_effective_date__c.format();
        }
         if((cp.contract_margin__c.equalsIgnoreCase('N')) && (cp.Contract_Rate_Type__c.equalsIgnoreCase('Fixed')) && (cp.penalty_margin__c.equalsIgnoreCase('N')) && 
           cp.Penalty_Rate_Type__c.equalsIgnoreCase('Fixed')){
            primeDate = 'N/A';
        }
        
        //Test Condition For Fixed Late Fee
        if((cp.risk_code__c.equalsIgnoreCase('No')) && (cp.late_fee_type__c.equalsIgnoreCase('P'))){
            lateFee = cp.pct_late_fee__c + '% of the account balance';
        }
        if((cp.risk_code__c.equalsIgnoreCase('No')) && (cp.late_fee_type__c.equalsIgnoreCase('F'))){
            lateFee = '$' + cp.fixed_late_fee__c;
        }
        if((cp.risk_code__c.equalsIgnoreCase('7')) && (cp.late_fee_type__c.equalsIgnoreCase('P'))){
            lateFee = 'Up to '+ cp.pct_late_fee__c + '% of the account balance';
        }
        if((cp.risk_code__c.equalsIgnoreCase('7')) && (cp.late_fee_type__c.equalsIgnoreCase('F'))){
            lateFee = 'Up to $'+ cp.fixed_late_fee__c;
        }
        
        //Test for retFee, paperFee, and ovrLimFee
        if(cp.risk_code__c.equalsIgnoreCase('No')){
            retFee = '$' + cp.return_payment_fee__c + ' per occurrence';
            paperFee = '$' + cp.paper_delivery_fee__c + ' per month for paper statement and reporting';
            ovrLimFee = '$' + cp.over_limit_fee__c + ' per occurrence';
        }
        if(cp.risk_code__c.equalsIgnoreCase('7')){
            retFee = 'Up to $' + cp.return_payment_fee__c + ' per occurrence';
            paperFee = 'Up to $' + cp.paper_delivery_fee__c + ' per month for paper statement and reporting';
            ovrLimFee = 'Up to $' + cp.over_limit_fee__c + ' per occurrence';
        }
        //Add Key/Value pairs
        pricing.put('Annual Percentage Rate (APR) for Purchases: ', rate);
        if(cp.promo_periods__c != 0){
        pricing.put('Introductory APR for Purchases: ', cp.promotional_rate__c + '% introductory APR for ' + cp.nbr_billing_cyles__c + '  cycles after account opening.');
        }
        pricing.put('Penalty APR: ', penRate);
        //check for N/A on Prime
        if(primeDate != 'N/A'){
            pricing.put('Prime Rate: ', primeDate);
        }
        pricing.put('Paper Delivery Fee: ', paperFee);
        pricing.put('Late Payment Fee: ', lateFee);
        pricing.put('Overlimit Fee: ', ovrLimFee);
        pricing.put('Returned Payment Fee: ', retFee);


        
        
        
        
        
        return pricing;
    }
}