src/objects/Campaign_Program__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Campaign Programs</relationshipLabel>
        <relationshipName>Campaign_Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Campaign Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OnlineApplicationOffer__c.object
<CustomObject>
    <description>Forseva Online Application Project</description>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Online Application Offers</relationshipLabel>
        <relationshipName>Online_Application_Offers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Online Application Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Online Application Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/WexBrandingControllerTest.cls
@isTest(seeAllData=True)
public class WexBrandingControllerTest {
    
    static testMethod void testBrandingControler() {
        
        Id programId = WexBrandingController.getProgramIdByBrandShortName('Edge');
        
        Program__c program = WexBrandingController.getProgram(programId);
        
        Id brandingUtilityId = WexBrandingController.getBrandingUtilityByProgramId(programId, 'en_us');
        
        WexBrandingController.getBrandingUtility(brandingUtilityId);
        
        WexBrandingController.getAvailableLanguages(programId);
        
        WexBrandingController.getLogoId(programId);
        
        WexBrandingController.getCreditCardImageId(programId);
        
        WexBrandingController.getCreditCardNotTextImageId(programId);
        
        WexBrandingController.getBPAVLogoId(programId);
        
        WexBrandingController.getPartnerLogoId(null);
        
        WexBrandingController.getPartnerByPartnerKey(null);
        
        Id programTemplateAccountId = WexBrandingController.getDefaultAccountTemplateByProgram(programId);
        
        WexBrandingController.getProgramTemplateAccount(programTemplateAccountId);
        
        WexBrandingController.getDefaultCampaignProgramByProgram(programId, 'en_us');
        
        Campaign_Program__c campaignProgram = WexBrandingController.getCampaignProgramByCouponCode(programId, null, 'en_us');
        
        if(campaignProgram != null) {
        
        	WexBrandingController.getCampaignByCampaignProgram(campaignProgram.Id);
            
        }
        
        OnlineApplicationOffer__c offer = WexBrandingController.getDefaultOnlineApplicationOfferByProgramId(programId);
        
        WexBrandingController.getOnlineApplicationOfferById(offer.Id);  
        
    }
    
}