src/objects/Campaign_Code__c.object
<CustomObject>
    <description>CRM-217 &amp; EAPT-280: Contains Marketing Campaign Codes</description>
    <fields>
        <fullName>Code_Used__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True when the generated code has been used</description>
        <inlineHelpText>True when the generated code has been used</inlineHelpText>
        <label>Code Used</label>
        <type>Checkbox</type>
    </fields>
    <label>Campaign Code</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campaign Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaign Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CampaignCodeGeneratorTest.cls
@isTest
public class CampaignCodeGeneratorTest {

    public static void test_generateCode() {

        final String CHARS = '1234ABCD';
        final List<String> CHARS_LIST = CHARS.split('');
        final Integer LENGTH = 4;

        Test.startTest();
        String code = CampaignCodeGenerator.generateCode(LENGTH, CHARS);
        Test.stopTest();

        // Assert code is of correct length
        System.assertEquals(LENGTH, code.length());

        // Assert all the characters in the code are also in our original chars list
        List<String> codeList = code.split('');
        for (String character : codeList) {
            System.assertEquals(true, CHARS_LIST.contains(character));
        }
    }

    public static void test_getCode() {

        Test.startTest();
        String code = CampaignCodeGenerator.getCampaignCode();
        Test.stopTest();

        Campaign_Code__c campaignCode = [ SELECT Id, Code_Used__c FROM Campaign_Code__c WHERE Name = :code];

        // Assert that the method didn't return null
        System.assertEquals(true, code != null);

        // Assert that code used flag was set true
        System.assertEquals(true, campaignCode.Code_Used__c);

    }
}