src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Browser_Used__c</fullName>
        <label>Browser Used</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Chrome</fullName>
                </value>
                <value>
                    <fullName>Internet Explorer</fullName>
                </value>
                <value>
                    <fullName>Edge</fullName>
                </value>
                <value>
                    <fullName>Firefox</fullName>
                </value>
                <value>
                    <fullName>Safari</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <description>CP Departments</description>
        <inlineHelpText>Choose the department the case is relevant to</inlineHelpText>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sales</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>I.T</fullName>
                </value>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Customer Service</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>Correspondence</fullName>
                </value>
                <value>
                    <fullName>CS Helpdesk</fullName>
                </value>
                <value>
                    <fullName>eServices</fullName>
                </value>
                <value>
                    <fullName>Premium Fleet</fullName>
                </value>
                <value>
                    <fullName>Receivables</fullName>
                </value>
                <value>
                    <fullName>Operations</fullName>
                </value>
                <value>
                    <fullName>Marketing</fullName>
                </value>
                <value>
                    <fullName>Contact Center</fullName>
                </value>
                <value>
                    <fullName>Fraud</fullName>
                </value>
                <value>
                    <fullName>Corporate Payments AU Account Management</fullName>
                </value>
                <value>
                    <fullName>Corporate Payments ASIA Account Management</fullName>
                </value>
                <value>
                    <fullName>Corporate Payments Account Management Leadership</fullName>
                </value>
                <value>
                    <fullName>Corporate Payments EU Account Management</fullName>
                </value>
                <value>
                    <fullName>Account Management</fullName>
                </value>
                <value>
                    <fullName>Corporate Payments NA Account Management</fullName>
                </value>
                <value>
                    <fullName>Support Operations</fullName>
                </value>
                <value>
                    <fullName>Salesforce Support</fullName>
                </value>
                <value>
                    <fullName>Portfolio &amp; Risk Operations</fullName>
                </value>
                <value>
                    <fullName>Global Fleet</fullName>
                </value>
                <value>
                    <fullName>Corporate Payments</fullName>
                </value>
                <value>
                    <fullName>Corporate Technology</fullName>
                </value>
                <value>
                    <fullName>Corporate Development</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>List the exact error message you received</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>List the exact error message you received. There will also be an option to add screenshots on the case summary page.</inlineHelpText>
        <label>Error Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Functional_Area__c</fullName>
        <label>Functional Area</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Data Issue</fullName>
                </value>
                <value>
                    <fullName>Lightning</fullName>
                </value>
                <value>
                    <fullName>Reports &amp; Dashboards</fullName>
                </value>
                <value>
                    <fullName>Set Up Customization</fullName>
                </value>
                <value>
                    <fullName>Solution Design</fullName>
                </value>
                <value>
                    <fullName>Training</fullName>
                </value>
                <value>
                    <fullName>User Management</fullName>
                </value>
                <value>
                    <fullName>User Permissions</fullName>
                </value>
                <value>
                    <fullName>WEX Network</fullName>
                </value>
                <value>
                    <fullName>WEX SFDC</fullName>
                </value>
                <value>
                    <fullName>Salesforce</fullName>
                </value>
                <value>
                    <fullName>Zuora</fullName>
                </value>
                <value>
                    <fullName>Integration Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Nature_of_Case__c</fullName>
        <label>Nature of Case</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Issue</fullName>
                    <default>true</default>
                    <label>Issue</label>
                </value>
                <value>
                    <fullName>Enhancement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Steps_to_Reproduce__c</fullName>
        <description>List detailed steps taken to reproduce the issue</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>List detailed steps taken to reproduce the issue</inlineHelpText>
        <label>Steps to Reproduce</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Workaround__c</fullName>
        <description>Is there a current workaround in place</description>
        <inlineHelpText>Is there a current workaround in place</inlineHelpText>
        <label>Workaround</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/classes/WEXSFDCSupportTest.cls
/**
 * Created by lhowland on 12/12/2018.
 */
@isTest (SeeAllData = true)
public with sharing class WEXSFDCSupportTest {

    public static Account setupAccount() {

        Account account = new Account();
        account.Name ='TestAccount-01';

        insert account;

        return account;
    }

    public static Contact setupContact() {

        Contact contact = new Contact();

        contact.FirstName = 'Tester';
        contact.LastName = 'Tester Last';
        contact.Email = 'Tester@UnitTest.com';

        insert contact;

        return contact;
    }

    static testMethod void WEXSFDCSupportTest() {

        Account account = setupAccount();

        Contact contact = setupContact();

        Test.startTest();

        PageReference wexSDFCSupport = Page.WEXSFDCSupport;

        // TEST NEW CASE

        wexSDFCSupport.getParameters().put('action','newCase');
        Test.setCurrentPage(wexSDFCSupport);

        SFDCSupportWebToCaseController controller = new SFDCSupportWebToCaseController();
        controller.init();

        System.assert(controller.caseIdParameter == null);
        System.assert(controller.caseTypes == null);
        System.assert(controller.departments == null);
        System.assert(controller.natureOfCaseOptions == null);
        System.assert(controller.browser == null);
        System.assert(controller.nextStep != null);
        System.assert(controller.caseAttachmentsSize == 0);
        System.assert(controller.offset != null);
        
        controller.caseRequest.Account = account;
        controller.caseRequest.Contact = contact;

        controller.caseRequest.Department__c = 'Corporate Development';
        controller.caseRequest.Nature_of_Case__c = 'Issue';
        controller.caseRequest.Functional_Area__c = 'Data Issue';
        controller.caseRequest.Subject = 'Ninjas are invading my SF account';
        controller.caseRequest.Description = 'I swear little gnome ninjas are mucking with my data in the night!';
        controller.caseRequest.Error_Message__c = 'Warning: You have stage 4 gnome ninjas in your environment. Precede with server (get it...) caution.';
        controller.caseRequest.Steps_to_Reproduce__c = '1. Log into SF. 2. View gnome ninja data destruction.';
        controller.caseRequest.Browser_Used__c = 'Chrome';
        controller.caseRequest.Number_of_Users_Affected__c = '1';
        controller.caseRequest.Workaround__c = 'No';
        
        controller.previousStep();
        controller.beginningStep();
        controller.nextStep();

        controller.submitCase();

        controller.fileCount = '1';
        PageReference changeFileCount = controller.ChangeCount();
        System.assert(changeFileCount == null);
        Attachment attachment = new Attachment(ParentId = controller.caseRequest.Id, Name = 'TestName', Body = Blob.valueOf('Blob of Strings'));
        insert attachment;

        System.assert(controller.caseRequest.Id != null);
        System.assert(controller.caseRequest.OwnerId != null);
        System.assert(controller.caseRequest.Status.equals('New'));
        System.assert(controller.caseRequest.Priority.equals('Normal'));
        System.assert(controller.caseRequest.Origin.equals('Web'));
        System.assert(controller.caseRequest.SuppliedName != null);
        System.assert(controller.caseRequest.SuppliedEmail != null);
        //System.assert(controller.caseRequest.EntitlementId != null);
        System.assert(!controller.hasError);
        System.assert(controller.previousStep);
        System.assert(controller.isIssue);

        wexSDFCSupport.getParameters().put('action','home');
        Test.setCurrentPage(wexSDFCSupport);

        controller.init();

        // TEST VIEW OPEN CASE

        wexSDFCSupport.getParameters().put('action','viewCase');
        wexSDFCSupport.getParameters().put('caseNumber', controller.caseRequest.Id);
        Test.setCurrentPage(wexSDFCSupport);

        controller.init();

        System.assert(controller.currentCase != null);
        System.assert(controller.sizeOfOpenCases > 0);
        System.assert(controller.sizeOfClosedCases == 0);

        // TEST POST COMMENT

        controller.comment = 'I have a new Sensei who is going to train me in the martial arts in order to defeat the gnome ninjas.';
        PageReference errorPage = controller.postFeed();
        System.assert(errorPage == null);

        // TEST ERROR SECTIONS

        controller.currentCase.Id = null;
        errorPage = controller.postFeed();
        System.assert(errorPage != null);

        wexSDFCSupport.getParameters().put('action','viewCase');
        Test.setCurrentPage(wexSDFCSupport);

        controller.init();

        System.assert(controller.hasError);

        controller.caseRequest = null;
        errorPage = controller.submitCase();
        String errorCode = errorPage.getParameters().get('errorCode');
        System.assert(errorCode != null);

        Test.stopTest();
    }

}