src/objects/CommHomePageSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Common_Reports_Height__c</fullName>
        <description>Height number in pixels for the Common Reports component for community homepage.</description>
        <label>Common Reports Height</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Common_Reports_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Common Reports Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Common_Reports_Width__c</fullName>
        <description>Width number in percentage for the Common Reports component for community homepage.</description>
        <label>Common Reports Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Top_Opportunities_Height__c</fullName>
        <description>Height number in pixels for the Common Reports component for community homepage.</description>
        <label>Top Opportunities Height</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Top_Opportunities_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Top Opportunities Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Opportunities_Width__c</fullName>
        <description>Width number in percent for the Top Opportunities component for community homepage.</description>
        <label>Top Opportunities Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CommHomePageSettings</label>
</CustomObject>

src/objects/CommonReports__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Report_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Report Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Report_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Report URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Sort__c</fullName>
        <label>Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CommonReports</label>
</CustomObject>

src/objects/TopOpportunities__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <description>This is the unique id of the Opportunity.  Like &quot;0067000000d8OKl&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the unique id of the Opportunity.  Like &quot;0067000000d8OKl&quot;</inlineHelpText>
        <label>Opportunity Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort__c</fullName>
        <description>This is the number that the list will sort on in Ascending order.</description>
        <inlineHelpText>This is the number that the list will sort on in Ascending order.</inlineHelpText>
        <label>Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/Test_PartnersHomePageComponents.cls
@isTest
private class Test_PartnersHomePageComponents {
	
	@isTest static void testCommonReports() {
		

		CommHomePageSettings__c ch = new CommHomePageSettings__c();
		ch.common_reports_title__c='test';
        ch.common_reports_height__c=200;
        ch.common_reports_width__c=200;
        insert ch;

        CommonReports__c cr = new CommonReports__c();
        cr.Active__c = true;
        cr.name = 'test';
        cr.Report_Title__c = 'test';
        cr.Report_URL__c = 'www.yahoo.com';
        cr.Sort__c = 1;
        insert cr;

        test.starttest();
        CommonReportsController crc = new CommonReportsController();
        test.stoptest();

	}
	
	@isTest static void testTopOpportunities() {
		

		CommHomePageSettings__c ch = new CommHomePageSettings__c();
		ch.name='test';
		ch.top_opportunities_title__c = 'test';
        ch.top_opportunities_height__c = 200;
        ch.top_opportunities_width__c=200;
        insert ch;

        List<Account> a = UTestData.getAccounts(1);
        insert a;

        Opportunity o = UTestData.getOpportunities(a)[0];
        insert o;

        TopOpportunities__c topp = new TopOpportunities__c();
        topp.name = 'test';
        topp.Opportunity_Id__c = o.Id;
        topp.Sort__c = 1;
        insert topp;

        test.starttest();

        TopOpportunityController topc = new TopOpportunityController();

        test.stoptest();




	}
	
}