src/objects/CommHomePageSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Top_Opportunities_Height__c</fullName>
        <description>Height number in pixels for the Common Reports component for community homepage.</description>
        <label>Top Opportunities Height</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Top_Opportunities_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Top Opportunities Title</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Top_Opportunities_Width__c</fullName>
        <description>Width number in percent for the Top Opportunities component for community homepage.</description>
        <label>Top Opportunities Width</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CommHomePageSettings</label>
</CustomObject>

src/objects/TopOpportunities__c.object
<CustomObject>
    <fields>
        <fullName>Fleet_Size__c</fullName>
        <description>Captures fleet size field from opportunity</description>
        <label>Fleet Size</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Id__c</fullName>
        <description>This is the unique id of the Opportunity.  Like &quot;0067000000d8OKl&quot;</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the unique id of the Opportunity.  Like &quot;0067000000d8OKl&quot;</inlineHelpText>
        <label>Opportunity Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort__c</fullName>
        <description>This is the number that the list will sort on in Ascending order.</description>
        <inlineHelpText>This is the number that the list will sort on in Ascending order.</inlineHelpText>
        <label>Sort</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/TopOpportunityController.cls
public with sharing class TopOpportunityController {
    
    public List<OppWrapper> opps {get;set;}
    public Integer compheight{get;set;}
    public Integer compwidth{get;set;}
    public String comptitle{get;set;}

    public TopOpportunityController() {
        loadData();
    }

    private void loadData()
    {
    
        CommHomePageSettings__c comsettings = CommHomePageSettings__c.getorgdefaults();
        comptitle = comsettings.top_opportunities_title__c;
        compheight = integer.valueof(comsettings.top_opportunities_height__c);
        compwidth = integer.valueof(comsettings.top_opportunities_width__c);
        
        opps = new List<OppWrapper>();
        Map<Id,Integer> idAndSort = new Map<Id,Integer>();

        
        for(TopOpportunities__c tt : TopOpportunities__c.getall().values())
        {
            //if(tt.Opportunity_Id__c==null || tt.Opportunity_Id__c.length()!=18) continue;

            if(tt.Opportunity_Id__c==null || !(tt.Opportunity_Id__c InstanceOf Id)) continue;

            idAndSort.put((Id)tt.Opportunity_Id__c, (Integer)tt.Sort__c);
        }
        
        Set<Id> idSet = idAndSort.keySet();
        

        for(Opportunity o : [Select Id, Name, Fleet_Size__c from Opportunity Where Id IN :idSet])
        {
            opps.add(new OppWrapper(o, idAndSort.get(o.Id)));
        }

        opps.sort();
        
        for(integer x = 0; x<opps.size(); x++)
        {
            opps[x].setcounter(x+1);
        }
    }

    public class OppWrapper implements Comparable
    {
        public Opportunity opp{get;set;}
        public String oppLink{get;set;}
        private Integer sortOrder{get;set;}
        public integer counter{get;set;}

        public OppWrapper(Opportunity o, Integer sortOrd)
        {
            opp = o;
            oppLink = '/' + o.Id;
            sortOrder = sortOrd;
            counter = 0;

        }
        public void setcounter(Integer i)
        {
            counter = i;
        }

        public Integer compareTo(object compareTo)
        {
            OppWrapper rw = (OppWrapper)compareTo;
            if(sortOrder == rw.sortOrder)
            {
                return 0;
            }
            else if(sortOrder > rw.SortOrder || rw.SortOrder==null)
            {
                return 1;
            }

            return -1;
        }
    }
}