src/objects/Credit_Utilization_History__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Credit_Utilizations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Credit_Utilization__c</fullName>
        <formula>( Overall_balance__c  / Overall_Credit_limit__c )</formula>
        <label>Credit Utilisation</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Credit Utilisation History</label>
    <nameField>
        <displayFormat>CredutilHist{00000}</displayFormat>
        <label>Credit Utilisation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Utilisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreditUtilizationHistory_trigger_handler.cls
public class CreditUtilizationHistory_trigger_handler {
	public static void updateCreditUtilizationOnUltParentAccount(List<Credit_Utilization_History__c> creditUtilHistories){

		Set<Id> setAccountIds = new Set<Id>(); // Set of Ids to hold Account Ids

		for(Credit_Utilization_History__c cUtilHist : creditUtilHistories){
			setAccountIds.add(cUtilHist.Account__c);
		}

		List<Account> listAccounts = [select id, Credit_Utilization__c, Account_Id__c, Ultimate_Parent_External_Id__c, (select id, Credit_Utilization__c from Credit_Utilizations__r order by lastmodifieddate desc limit 1) from Account where  id =: setAccountIds]; 
		List<Account> toUpdateAccounts = new List<Account>();

		for(Account acc : listAccounts){

			Credit_Utilization_History__c cUtil = null;

			if(!acc.Credit_Utilizations__r.isEmpty()){
				cUtil =  acc.Credit_Utilizations__r[0];
			}
			
			if(!String.isBlank(acc.Account_Id__c) && !String.isBlank(acc.Ultimate_Parent_External_Id__c) && acc.Account_Id__c == acc.Ultimate_Parent_External_Id__c && !String.isBlank(String.valueOf(cUtil.Credit_Utilization__c))){
				acc.Credit_Utilization__c = cUtil.Credit_Utilization__c;
				toUpdateAccounts.add(acc);
			}

		}

		if(!toUpdateAccounts.isEmpty()){
			Database.update(toUpdateAccounts,false);
		}
	}
}