src/objects/Credit_Override__c.object
<CustomObject>
    <description>The credit override objects to be attached to an Account.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Credit Overrides</relationshipLabel>
        <relationshipName>Credit_Overrides</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Expiry Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Override_Type__c</fullName>
        <description>Override type for the Account</description>
        <label>Override Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Limit (TCL) Override</fullName>
                </value>
                <value>
                    <fullName>Overdue (AOT) Override</fullName>
                </value>
                <value>
                    <fullName>Security Exception</fullName>
                </value>
                <value>
                    <fullName>Dishonoured Payment Override</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Credit Override</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Credit Override Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Client_Id__c</fullName>
        <label>Client Id</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>30</fullName>
                </value>
                <value>
                    <fullName>31</fullName>
                </value>
                <value>
                    <fullName>32</fullName>
                </value>
                <value>
                    <fullName>33</fullName>
                </value>
                <value>
                    <fullName>34</fullName>
                </value>
                <value>
                    <fullName>TBC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>31</fullName>
                </value>
                <value>
                    <fullName>34</fullName>
                </value>
                <value>
                    <fullName>35</fullName>
                </value>
                <value>
                    <fullName>36</fullName>
                </value>
                <value>
                    <fullName>37</fullName>
                </value>
                <value>
                    <fullName>38</fullName>
                </value>
                <value>
                    <fullName>39</fullName>
                </value>
                <value>
                    <fullName>40</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Late_Payer_Days__c</fullName>
        <defaultValue>5</defaultValue>
        <description>The Invoice Paid In Full On date needs to be &gt;= Payment Due Date + Late Payer Days</description>
        <label>Late Payer Days</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EMAP_AccountAutoSusReact_Handler.cls
public class EMAP_AccountAutoSusReact_Handler {
    
    //************ Queries will not be used any more ***************************************************//
    public final static String QUERY_HongKong_OVERDUE_SUSPENSION = 'select Id from Account where Client_Id__c = \'32\' AND Status__c = \'1 - Active\' AND Customer_Type__c = \'3 - Standard\' AND Overdue_Days__c >= 6 AND AOT_Threshold_Exceeded__c = true';
    
    public final static String QUERY_GMSPSG_OVERDUE_SUSPENSION = 'select Id from Account where Client_Id__c in (\'30\',\'31\',\'33\') AND Status__c = \'1 - Active\' AND Customer_Type__c = \'3 - Standard\' AND Overdue_Days__c >= 6 AND AOT_Threshold_Exceeded__c = true';
    
    public final static String QUERY_HongKong_REACTIVATION = '' + 
        ' select Id ' +
        ' from Account ' +
        ' where Client_Id__c = \'32\' ' +
        ' AND Status__c = \'9 - Temporary Locked\' ' +
        ' AND Account_Sub_Status__c = \'J - AutoStop Delinquent\'' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND AOT_Threshold_Exceeded__c = false ' +
        ' AND ( ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c = \'5 - High\' ' +
        '       AND Percent_Secured__c >= 50 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '   Percent_Secured__c >= 100 ' +
        '   ) ' +
        ' )';
        
    public final static String QUERY_GMSPSG_REACTIVATION = '' + 
        ' select Id ' +
        ' from Account ' +
        ' where Client_Id__c in (\'30\',\'31\',\'33\') ' +
        ' AND Status__c = \'9 - Temporary Locked\' ' +
        ' AND Account_Sub_Status__c = \'J - AutoStop Delinquent\'' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND AOT_Threshold_Exceeded__c = false ' +
        ' AND ( ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c = \'5 - High\' ' +
        '       AND Percent_Secured__c >= 50 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '   Percent_Secured__c >= 100 ' +
        '   ) ' +
        ' )';
    //************ Queries will not be used any more ***************************************************//

        
    //Added Updated Queries here. Above queries will not be used any more
    
    //Exclude Accounts having below Credit Overrides
    public final static String CREDIT_OVERRIDE_QUERY = ' (Select Account__c From Credit_Override__c Where Override_Type__c IN (\'Overdue (AOT) Override\', \'Dishonoured Payment Override\') AND Effective_Date__c <= TODAY AND Expiry_Date__c  >= TODAY) ';    
    public final static Decimal Late_Payer_Days = [Select Late_Payer_Days__c From Program__c Where Client_Id__c ='30' OR Client_Id__c ='31' LIMIT 1].Late_Payer_Days__c;
    public final static Decimal Late_Payer_Days_HK = [Select Late_Payer_Days__c From Program__c Where Client_Id__c ='32' LIMIT 1].Late_Payer_Days__c;    
    public final static Decimal Late_Payer_Days_SG = [Select Late_Payer_Days__c From Program__c Where Client_Id__c ='33' LIMIT 1].Late_Payer_Days__c;        
    
    //Query to Auto Suspend GMSP Accounts automatically through Batch
    public final static String QUERY_GMSP_OVERDUE_SUSPENSION = '' +
        ' Select Id From Account ' + 
        ' Where RecordType.name = \'EMAP Fuel Accounts\' ' +
        ' AND Id NOT IN ' + CREDIT_OVERRIDE_QUERY +
        ' AND Client_Id__c in (\'30\',\'31\') ' +
        ' AND Status__c = \'1 - Active\' ' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND Overdue_Days__c >=' + Integer.valueOf(Late_Payer_Days) +
        ' AND AOT_Threshold_Exceeded__c = true';
    
    //Query to Auto Suspend HK Accounts automatically through Batch
    public final static String QUERY_HK_OVERDUE_SUSPENSION = '' +
        ' Select Id From Account ' + 
        ' Where RecordType.name = \'EMAP Fuel Accounts\' ' +
        ' AND Id NOT IN ' + CREDIT_OVERRIDE_QUERY +
        ' AND Client_Id__c in (\'32\') ' +
        ' AND Status__c = \'1 - Active\' ' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND Overdue_Days__c >=' + Integer.valueOf(Late_Payer_Days_HK) +
        ' AND AOT_Threshold_Exceeded__c = true';

        //Query to Auto Suspend SG Accounts automatically through Batch
    public final static String QUERY_SG_OVERDUE_SUSPENSION = '' +
        ' Select Id From Account ' + 
        ' Where RecordType.name = \'EMAP Fuel Accounts\' ' +
        ' AND Id NOT IN ' + CREDIT_OVERRIDE_QUERY +
        ' AND Client_Id__c in (\'33\') ' +
        ' AND Status__c = \'1 - Active\' ' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND Overdue_Days__c >='+ Integer.valueOf(Late_Payer_Days_SG) +
        ' AND AOT_Threshold_Exceeded__c = true';

    //Query to Re-instate GMSP Accounts automatically through Batch
    public final static String QUERY_GMSP_REACTIVATION = '' + 
        ' Select Id ' +
        ' From Account ' +
        ' Where RecordType.name = \'EMAP Fuel Accounts\' ' +
        ' AND Id NOT IN ' + CREDIT_OVERRIDE_QUERY +
        ' AND Client_Id__c in (\'30\',\'31\') ' +
        ' AND Status__c = \'3 - Stopped (blocked)\' ' +
        ' AND Account_Sub_Status__c = \'R - Delinquent (man.)\'' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND AOT_Threshold_Exceeded__c = false ' +
        ' AND ( ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c = \'5 - High\' ' +
        '       AND Percent_Secured__c >= 50 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '   Percent_Secured__c >= 100 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Hierarchy_Level__c = \'03\' AND ParentId <> null ' +
        '       AND Parent.Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Hierarchy_Level__c = \'03\' AND ParentId <> null ' +
        '       AND Parent.Risk_Grade__c = \'5 - High\' ' +
        '       AND Parent.Percent_Secured__c >= 50 ' +
        '   ) ' +
        ' )';

    //Query to Re-instate HK Accounts automatically through Batch
    public final static String QUERY_HK_REACTIVATION = '' + 
        ' Select Id ' +
        ' From Account ' +
        ' Where RecordType.name = \'EMAP Fuel Accounts\' ' +
        ' AND Id NOT IN ' + CREDIT_OVERRIDE_QUERY +
        ' AND Client_Id__c in (\'32\') ' +
        ' AND Status__c = \'3 - Stopped (blocked)\' ' +
        ' AND Account_Sub_Status__c = \'R - Delinquent (man.)\'' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND AOT_Threshold_Exceeded__c = false ' +
        ' AND ( ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c = \'5 - High\' ' +
        '       AND Percent_Secured__c >= 50 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '   Percent_Secured__c >= 100 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Hierarchy_Level__c = \'03\' AND ParentId <> null ' +
        '       AND Parent.Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Hierarchy_Level__c = \'03\' AND ParentId <> null ' +
        '       AND Parent.Risk_Grade__c = \'5 - High\' ' +
        '       AND Parent.Percent_Secured__c >= 50 ' +
        '   ) ' +
        ' )';

    //Query to Re-instate SG Accounts automatically through Batch
    public final static String QUERY_SG_REACTIVATION = '' + 
        ' Select Id ' +
        ' From Account ' +
        ' Where RecordType.name = \'EMAP Fuel Accounts\' ' +
        ' AND Id NOT IN ' + CREDIT_OVERRIDE_QUERY +
        ' AND Client_Id__c in (\'33\') ' +
        ' AND Status__c = \'3 - Stopped (blocked)\' ' +
        ' AND Account_Sub_Status__c = \'R - Delinquent (man.)\'' +
        ' AND Customer_Type__c = \'3 - Standard\' ' +
        ' AND AOT_Threshold_Exceeded__c = false ' +
        ' AND ( ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Risk_Grade__c = \'5 - High\' ' +
        '       AND Percent_Secured__c >= 50 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '   Percent_Secured__c >= 100 ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Hierarchy_Level__c = \'03\' AND ParentId <> null ' +
        '       AND Parent.Risk_Grade__c in (\'0 - Limited Assessment\',\'2 - Very Low\',\'3 - Low\',\'4 - Medium\') ' +
        '   ) ' +
        '   OR ' +
        '   ( ' +
        '       (Number_of_Late_Payments_Last_3_Months__c = null OR Number_of_Late_Payments_Last_3_Months__c < 2) ' +
        '       AND (Number_of_Dishonours_in_Last_3_Months__c = null OR Number_of_Dishonours_in_Last_3_Months__c < 2) ' +
        '       AND Hierarchy_Level__c = \'03\' AND ParentId <> null ' +
        '       AND Parent.Risk_Grade__c = \'5 - High\' ' +
        '       AND Parent.Percent_Secured__c >= 50 ' +
        '   ) ' +
        ' )';
        
}