src/objects/Currency_Conversion__c.object
<CustomObject>
</CustomObject>

src/objects/Wex_UK_Configurable__c.object
<CustomObject>
    <fields>
        <fullName>Account_Dates__c</fullName>
        <description>In days First Trans Date  Invoice Date Account Creation</description>
        <label>Account Dates</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confidence_Threshold_DNB__c</fullName>
        <label>Confidence Threshold DNB</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Confidence_Threshold_EFX__c</fullName>
        <label>Confidence Threshold EFX</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Limit_Threshold__c</fullName>
        <label>Credit Limit Threshold (Euros)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Credit_Util_threshold__c</fullName>
        <label>Credit Utilisation Threshold (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_Date_upper__c</fullName>
        <description>creditAssRiskGrade &gt; 3</description>
        <label>Expiry Date Upper (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Expiry_date_lower__c</fullName>
        <description>creditAssRiskGrade &lt;= 3</description>
        <label>Expiry Date Lower (Months)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>HLA_Threshold__c</fullName>
        <label>HLA Threshold (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>High_Cred_Util_limit__c</fullName>
        <label>High Cred Utilisation Limit (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nird_Review__c</fullName>
        <description>The number of days until expiration.</description>
        <label>Nird Review (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_Cred_Lmt_threshold__c</fullName>
        <label>Overall Credit Limit Threshold (Euros)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pre_HLA_Lower__c</fullName>
        <label>Pre HLA Lower (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pre_HLA_Upper__c</fullName>
        <label>Pre HLA Upper (%)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/classes/WexUK_CreditReassessment_BatchClass_Test.cls
@isTest
private class WexUK_CreditReassessment_BatchClass_Test{

        
        static testmethod void CreditReassessment_BatchClass_Test() {
        
        //List<Account> acc = TestDatatUtility.getWexUKAccountList();
        Schema.RecordTypeInfo accRecordType = TestDatatUtility.getRecordTypeInfo('Account', 'WES Accounts');
        Account acc = new Account();
            acc.RecordTypeId = accRecordType.getRecordTypeId();
            acc.Name ='Test Accountaaaa';
            acc.Account_Type__c='Prospect';
            acc.Auth_Node_Indicator__c = 'Y';
            acc.Credit_Limit_Status__c = 'Approved';
            acc.account_id__c = '1001nnnnnnnaaaa' ;
            
            
            acc.Credit_Utilization__c =76;
            acc.Nird__c=System.Today();
        insert acc;
        Wex_UK_Configurable__c configVals = new Wex_UK_Configurable__c(Account_Dates__c=-90 ,Confidence_Threshold_DNB__c=-1 ,Confidence_Threshold_EFX__c=-1 ,Credit_Limit_Threshold__c=12500    ,Credit_Util_threshold__c=75    ,CurrencyIsoCode='USD'   ,Expiry_date_lower__c=24    ,Expiry_Date_upper__c=12    ,High_Cred_Util_limit__c=50 ,HLA_Threshold__c=80        ,Name='Wex UK'    ,Nird_Review__c=30  ,Overall_Cred_Lmt_threshold__c=10000    ,Pre_HLA_Lower__c=75    ,Pre_HLA_Upper__c=80);
        insert configVals ;
        Currency_Conversion__c cc = new Currency_Conversion__c(Currency_Value_Euro__c = 100, Client_Id__c = '1001');
        insert cc;
       Test.startTest();
       WexUK_CreditReassessment_BatchClass CreditReassessmentBatch= new WexUK_CreditReassessment_BatchClass ();
       Database.executeBatch(CreditReassessmentBatch,1);
       Test.stopTest();
       

    }
}