src/objects/Deleted_Records_Stage__c.object
<CustomObject>
    <description>Staging table to store deleted records for i2i</description>
    <fields>
        <fullName>Date_Deleted__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Date Deleted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delete_Initiated_By__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Delete Initiated By</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Delete_Source__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Stamped by the trigger when the record is deleted</inlineHelpText>
        <label>Delete Source</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Record Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Deleted Records Stage</label>
    <nameField>
        <displayFormat>DR-{00000}</displayFormat>
        <label>Deleted Records Stage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deleted Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/GlobalSettings__c.object
<CustomObject>
</CustomObject>

src/classes/DeletedRecordsStageClass.cls
public class DeletedRecordsStageClass {

	public static Map<Id,String> deletedRecordsReasons = new Map<Id,String>();

    public static void preDeleteAccount (List <Account> records)
	{
		GlobalSettings__c gs = GlobalSettings__c.getOrgDefaults();
		
		List <Deleted_Records_Stage__c> recordsToInsert = new List <Deleted_Records_Stage__c>();
		
		for(Account a: [select id,
							   (select id from Contacts),
							   (select id from Opportunities)
						from account 
						where id in :records])
		{
			
			for(Contact c : a.contacts)
			{
				Deleted_Records_Stage__c d = new Deleted_Records_Stage__c();
				d.Record_ID__c = c.id;
				d.Date_Deleted__c = system.now();
				d.Record_Type__c = 'Contact';
				d.Delete_Initiated_By__c = 'User';
				d.Delete_Source__c = (deletedRecordsReasons.containskey(a.Id)) ? deletedRecordsReasons.get(a.Id) : 'Manual';
			
				if(userInfo.getUserId() == gs.Integration_User_ID__c)
				{
					d.Delete_Initiated_By__c = 'i2i';	
				}
			
				recordsToInsert.add(d);
			}
			
			for(Opportunity o : a.opportunities)
			{
				Deleted_Records_Stage__c d = new Deleted_Records_Stage__c();
				d.Record_ID__c = o.id;
				d.Date_Deleted__c = system.now();
				d.Record_Type__c = 'Opportunity';
				d.Delete_Initiated_By__c = 'User';
				d.Delete_Source__c = (deletedRecordsReasons.containskey(a.Id)) ? deletedRecordsReasons.get(a.Id) : 'Manual';
			
				if(userInfo.getUserId() == gs.Integration_User_ID__c)
				{
					d.Delete_Initiated_By__c = 'i2i';	
				}
			
				recordsToInsert.add(d);
			}
			
		}
		
		if(recordsToInsert.size() > 0)
		{
			insert recordsToInsert;
		}
	
	}


	public static void processDelete (List <sObject> records)
	{
		GlobalSettings__c gs = GlobalSettings__c.getOrgDefaults();
		
		List <Deleted_Records_Stage__c> recordsToInsert = new List <Deleted_Records_Stage__c>();
		
		for(sObject s : records)
		{
			Deleted_Records_Stage__c d = new Deleted_Records_Stage__c();
			d.Record_ID__c = s.id;
			d.Date_Deleted__c = system.now();
			d.Record_Type__c = string.valueOf(s.getSObjectType());
			d.Delete_Initiated_By__c = 'User';
			d.Delete_Source__c = (deletedRecordsReasons.containskey(s.Id)) ? deletedRecordsReasons.get(s.Id) : 'Manual';
			
			if(userInfo.getUserId() == gs.Integration_User_ID__c)
			{
				d.Delete_Initiated_By__c = 'i2i';	
			}
			
			recordsToInsert.add(d);
			
		}
		
		if(recordsToInsert.size() > 0)
		{
			insert recordsToInsert;
		}
		
	}

}