src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Template_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Template Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Program_Template_Account__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Program_Template_Account__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <recordTypes>
        <fullName>Internal</fullName>
        <active>true</active>
        <label>Internal</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Template_Account__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Program Template Accounts</relationshipLabel>
        <relationshipName>Program_Template_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Program Template Account</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Template Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program Template Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerTest.cls
/*
Description:        Test class for Opportunity Trigger
Revision History:
*/
@isTest
public class OpportunityTriggerTest {

    public static void testFleetEnrollmentOpptyInfoOnInsert() {
        Opportunity oppty = [SELECT Id, Campaign_Program__r.Program__c FROM Opportunity WHERE Name = 'Test Oppty' LIMIT 1];
        Program_Template_Account__c pta = [SELECT Id, Program__c FROM Program_Template_Account__c WHERE Program__c =: oppty.Campaign_Program__r.Program__c LIMIT 1];

        FleetEnrollment__c fleetEnrollment = new FleetEnrollment__c();
        fleetEnrollment.Opportunity__c = oppty.id;
        fleetEnrollment.Program__c = oppty.Campaign_Program__r.Program__c;
        fleetEnrollment.Program_Template_Account__c = pta.Id;
        fleetEnrollment.RecordTypeId = Schema.Sobjecttype.FleetEnrollment__c.getRecordTypeInfosByName().get('Internal').getRecordTypeId();

        Test.startTest();
        insert fleetEnrollment;
        Test.stopTest();

        //Asserts for After Insert logic on mapping parents
        FleetEnrollment__c myFE = [SELECT Id, Opportunity__c, Program__c, Program_Template_Account__c FROM FleetEnrollment__c WHERE Id =:fleetEnrollment.Id];
        system.assertEquals(oppty.id, myFE.Opportunity__c);
        system.assertEquals(oppty.Campaign_Program__r.Program__c, myFE.Program__c);
        system.assertEquals(oppty.Campaign_Program__r.Program__c, myFE.Program_Template_Account__r.Program__c);
        system.assertEquals('Internal', myFE.RecordType.Name);

    }

}