src/objects/Fleet_Enrollment_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Mass_Export_Limit__c</fullName>
        <label>Mass Export Limit</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Fleet Enrollment Settings</label>
</CustomObject>

src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Application_Status__c</fullName>
        <formula>Application_Request__r.Sales_Stage__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Application Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Opportunity Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Working</fullName>
                </value>
                <value>
                    <fullName>Ready For Siebel</fullName>
                </value>
                <value>
                    <fullName>Pending Ready For Siebel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/FleetEnrollmentExportController.cls
public class FleetEnrollmentExportController {

    public Integer exportLimit {
        get {
            Fleet_Enrollment_Settings__c FES = Fleet_Enrollment_Settings__c.getOrgDefaults();
            
            Integer exportLimit = 200;
            
            if(FES.Mass_Export_Limit__c != null) {
                exportLimit = Integer.valueOf(FES.Mass_Export_Limit__c);
            }
            
            return exportLimit;
        }
    }
    
    public List<FleetEnrollment__c> fleetEnrollments { 
        get {
            
            System.debug('### Export Limit Is: ' + exportLimit);
            
            List<FleetEnrollment__c> fleetEnrollments = [SELECT Id, Name, Opportunity_Number__c, Application_Status__c, Status__c FROM FleetEnrollment__c WHERE Status__c = 'New' and Opportunity_Number__c != null LIMIT :exportLimit];
            
            System.debug(fleetEnrollments);
            
            return fleetEnrollments;
        }
    }
    
    public String fleetEnrollmentsToDownload { 
        get {
            return String.valueOf(fleetEnrollments.size());
        }
    }
    
    public Integer fleetEnrollmentsToDownloadInt { 
        get {
            return fleetEnrollments.size();
        }
    }
    
    private ApexPages.StandardSetController standardController;
    
    public FleetEnrollmentExportController(ApexPages.StandardSetController standardController)
    {
        this.standardController = standardController;
    }
    
    public PageReference downloadAttachments() {
        
        PageReference zipFile = null;
        
        List<Attachment> attachments = new List<Attachment>();
        
        List<FleetEnrollment__c> fleetEnrollments = [SELECT Id, Opportunity_Number__c FROM FleetEnrollment__c WHERE Status__c = 'New' and Opportunity_Number__c != null LIMIT :exportLimit];
        
        System.debug(fleetEnrollments);
        
        if(!fleetEnrollments.isEmpty()) {
            
            for(FleetEnrollment__c fleetEnrollment : fleetEnrollments) {
                
                PageReference xlsGenerator = Page.FleetEnrollmentXLS;
                
                xlsGenerator.getParameters().put('id', fleetEnrollment.Id);
                
                if(xlsGenerator != null) {
                    
                    Attachment xlsAttachment = new Attachment();
                    
                    xlsAttachment.ParentId = fleetEnrollment.Id;
                    
                    xlsAttachment.Name = fleetEnrollment.Opportunity_Number__c + '.xls';
                    
                    if(Test.isRunningTest()) {
                        xlsAttachment.Body = Blob.valueOf('UNIT.TEST');
                    }
                    else { 
                    	xlsAttachment.Body = xlsGenerator.getContent();
                    }
                    
                    xlsAttachment.contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
                    
                    attachments.add(xlsAttachment);
                    
                }
                
            }
            
            insert attachments;
            
            Zippex xlsZipFile = new Zippex();
            
            for(Attachment xlsAttachment : attachments) {
                
                xlsZipFile.addFile('enrollments/' + xlsAttachment.Name, xlsAttachment.Body, null);
                
            }
            
            try {
                
                Document doc = new Document();
                
                doc.FolderId = UserInfo.getUserId();
                doc.Name = 'FleetEnrollmentExport.zip';
                doc.Body = xlsZipFile.getZipArchive();
                
                insert doc;
                
                for(FleetEnrollment__c fleetEnrollment : fleetEnrollments) {
                    
                    fleetEnrollment.Status__c = 'Completed';
                    
                }
                
				upsert fleetEnrollments;                
                
                return new PageReference('/servlet/servlet.FileDownload?file=' + doc.Id);
                
            } catch ( Exception ex ) {
                System.debug('>>> ERROR ' + ex);
            }
            
        }

        return zipFile;
        
    }
    
}