src/objects/FleetEnrollment__c.object
<CustomObject>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FleetEnrollment_Contact__c.object
<CustomObject>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/FleetEnrollment_Contact__c/fields/Fleet_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fleet Enrollment</label>
    <referenceTo>FleetEnrollment__c</referenceTo>
    <relationshipName>Fleet_Enrollment_Fleet_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/FleetEnrollment_Driver__c.object
<CustomObject>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/FleetEnrollment_Driver__c/fields/Fleet_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fleet Enrollment</label>
    <referenceTo>FleetEnrollment__c</referenceTo>
    <relationshipName>Fleet_Enrollment_Drivers</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/FleetEnrollmentDataTest.cls
@isTest
public class FleetEnrollmentDataTest {

    public static void test_fleetEnrollmentHasData() {

        List<FleetEnrollment_Contact__c> fleetEnrollmentContacts = [SELECT Id, Fleet_Enrollment__c from FleetEnrollment_Contact__c WHERE Name = 'FleetEnrollmentDataTest'];
        Set<Id> fleetEnrollmentIds = FleetEnrollmentUtils.listToFleetIdMap(fleetEnrollmentContacts).keySet();

        Test.startTest();
        FleetEnrollmentData.fleetEnrollmentDataUpdated(fleetEnrollmentContacts);
        Test.stopTest();


        List<FleetEnrollment__c> fleetEnrollments = [SELECT Id, Has_Fleet_Enrollment_Data__c FROM FleetEnrollment__c WHERE Id IN :fleetEnrollmentIds];

        for (FleetEnrollment__c fleetEnrollment : fleetEnrollments) {
            System.assertEquals(true, fleetEnrollment.Has_Fleet_Enrollment_Data__c);
        }
    }

    public static void test_fleetEnrollmentMissingData() {

        List<FleetEnrollment_Contact__c> fleetEnrollmentContacts = [SELECT Id, Fleet_Enrollment__c from FleetEnrollment_Contact__c WHERE Name = 'FleetEnrollmentDataTest'];
        Set<Id> fleetEnrollmentIds = FleetEnrollmentUtils.listToFleetIdMap(fleetEnrollmentContacts).keySet();

        delete [SELECT Id FROM FleetEnrollment_Driver__c WHERE Fleet_Enrollment__c IN :fleetEnrollmentIds];
        Test.startTest();
        FleetEnrollmentData.fleetEnrollmentDataUpdated(fleetEnrollmentContacts);
        Test.stopTest();


        List<FleetEnrollment__c> fleetEnrollments = [SELECT Id, Has_Fleet_Enrollment_Data__c FROM FleetEnrollment__c WHERE Id IN :fleetEnrollmentIds];

        for (FleetEnrollment__c fleetEnrollment : fleetEnrollments) {
            System.assertEquals(false, fleetEnrollment.Has_Fleet_Enrollment_Data__c);
        }
    }

    public static void test_fleetEnrollmentHasFile() {

        List<FleetEnrollment_Contact__c> fleetEnrollmentContacts = [SELECT Id, Fleet_Enrollment__c from FleetEnrollment_Contact__c WHERE Name = 'FleetEnrollmentDataTest'];
        Set<Id> fleetEnrollmentIds = FleetEnrollmentUtils.listToFleetIdMap(fleetEnrollmentContacts).keySet();

        delete [SELECT Id FROM FleetEnrollment_Driver__c WHERE Fleet_Enrollment__c IN :fleetEnrollmentIds];

        Test.startTest();

        // Assert that there's no fleet data
        FleetEnrollmentData.fleetEnrollmentDataUpdated(fleetEnrollmentContacts);
        for (FleetEnrollment__c fleetEnrollment : [
                SELECT Id, Has_Fleet_Enrollment_Data__c
                FROM FleetEnrollment__c
                WHERE Id IN :fleetEnrollmentIds
        ]) {
            System.assertEquals(false, fleetEnrollment.Has_Fleet_Enrollment_Data__c);
        }

        // Create the file
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.ContentLocation = 'S';
        contentVersion.PathOnClient = 'testing.txt';
        contentVersion.Title = 'Fleet Data Test';
        contentVersion.VersionData = Blob.valueOf('test');
        insert contentVersion;

        // Link file to fleet enrollment
        for (FleetEnrollment__c fleetEnrollment : [
                SELECT Id, Has_Fleet_Enrollment_Data__c
                FROM FleetEnrollment__c
                WHERE Id IN :fleetEnrollmentIds
        ]) {
            ContentDocumentLink contentDocumentLink = new ContentDocumentLink();
            contentDocumentLink.LinkedEntityId = fleetEnrollment.Id;
            contentDocumentLink.ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVersion.Id].ContentDocumentId;
            contentDocumentLink.shareType = 'V';
            insert contentDocumentLink;
        }

        Test.stopTest();

        // Assert that there's fleet data
        FleetEnrollmentData.fleetEnrollmentDataUpdated(fleetEnrollmentContacts);
        for (FleetEnrollment__c fleetEnrollment : [
                SELECT Id, Has_Fleet_Enrollment_Data__c
                FROM FleetEnrollment__c
                WHERE Id IN :fleetEnrollmentIds
        ]) {
            System.assertEquals(true, fleetEnrollment.Has_Fleet_Enrollment_Data__c);
        }
    }
}