src/objects/FleetEnrollment_Contact__c.object
<CustomObject>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/FleetEnrollment_Contact__c/fields/Fleet_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Fleet_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fleet Enrollment</label>
    <referenceTo>FleetEnrollment__c</referenceTo>
    <relationshipName>Fleet_Enrollment_Fleet_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/FleetEnrollmentUtilsTest.cls
@isTest
public class FleetEnrollmentUtilsTest {

    public static void test_hasFleetEnrollmentData() {

        Id fleetEnrollmentId = [SELECT Id, Fleet_Enrollment__c from FleetEnrollment_Contact__c WHERE Name = 'FleetEnrollmentDataTest' LIMIT 1].Fleet_Enrollment__c;

        Test.startTest();
        Boolean hasFleetEnrollmentData = FleetEnrollmentUtils.hasFleetEnrollmentData(fleetEnrollmentId);
        Test.stopTest();

        System.assertEquals(true, hasFleetEnrollmentData);
    }
}