src/objects/FleetEnrollment__c.object
<CustomObject>
    <fields>
        <fullName>Confirmation_Number__c</fullName>
        <displayFormat>FE-{000000}</displayFormat>
        <label>Confirmation Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Credit_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Credit_Line_Amount__c</fullName>
        <label>Credit Line Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Print_Token__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Print Token</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Fleet Enrollments</relationshipLabel>
        <relationshipName>Fleet_Enrollments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Fleet Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>FleetEnrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fleet Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Long_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Long Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fleet_Data_Capture_Form_Delivery__c</fullName>
        <label>Fleet Card Delivery Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5-7</fullName>
                </value>
                <value>
                    <fullName>2-3</fullName>
                </value>
                <value>
                    <fullName>3-5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Implementation_Team_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Implementation Team Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FleetEnrollmentConfirmationController.cls
public class FleetEnrollmentConfirmationController {

    public String printToken {
        get {
            return ApexPages.currentPage().getParameters().get('token');
        }
    }
    
    public String applicantId { 
        get {
            return ApexPages.currentPage().getParameters().get('applicant');
        }
    }
    
    public FleetEnrollment__c fleetEnrollment { 
        get {
            FleetEnrollment__c fleetEnrollment = [SELECT Id, Credit_Line_Amount__c, Confirmation_Number__c, Credit_Approved__c, Program__c FROM FleetEnrollment__c WHERE Print_Token__c = :printToken and Id = :applicantId];
            return fleetEnrollment;
        }
    }
    
    // Branding - Elements from the specified program
    public Program__c program { 
        get {
            Program__c program = [SELECT Id, Fleet_Data_Capture_Form_Delivery__c, Brand_Long_Name__c, Implementation_Team_Number__c, Brand_Color_1__c FROM Program__c WHERE Id = :fleetEnrollment.Program__c];
            
            return program; 
        }
    }
    
    // Branding - Card image from the chosen program
    public Id brandingCard { 
        get {
            transient Attachment card = [SELECT Id, Name, Body FROM Attachment where ParentId = : program.Id AND Name=:'ui-credit-card.png'];
            return card.Id;
        }
    }

}