src/objects/GenericDeleteBatchQueries__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>QueryString__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>QueryString</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>GenericDeleteBatchQueries</label>
</CustomObject>

src/classes/GenericDeleteBatch_Test.cls
@isTest (seeallData = true)
private class GenericDeleteBatch_Test {

//	static testmethod void testBatch()
//	{
//		test.startTest();
//
//		Account a = new Account();
//		a.name = 'test';
//		insert a;
//
//		GenericDeleteBatchQueries__c g = new GenericDeleteBatchQueries__c();
//		g.name = 'xxxxx';
//		g.queryString__c = 'select id from account where id = \'' + a.id + '\'';
//		insert g;
//
//
//		GenericDeleteBatch batchApex = new GenericDeleteBatch('xxxxx');
//      	ID batchprocessid = Database.executeBatch(batchApex);
//
//      	test.stopTest();
//	}
}