src/objects/Invoice__c.object
<CustomObject>
    <description>Created for AU Exxon Mobile Asia Pac (EMAP) project.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoice</relationshipLabel>
        <relationshipName>Invoice</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Late_Payer__c</fullName>
        <formula>IF(
OR(
AND(
ISBLANK(Invoice_Paid_in_Full_On__c),
(Payment_Due_Date__c + Account__r.Program__r.Late_Payer_Days__c ) &lt; TODAY()
),
AND(
NOT(ISBLANK(Invoice_Paid_in_Full_On__c)),
(Payment_Due_Date__c + Account__r.Program__r.Late_Payer_Days__c ) &lt; Invoice_Paid_in_Full_On__c 
)
),
true, 
false 
)</formula>
        <label>Is Late Payer?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Late_And_AOT__c</fullName>
        <defaultValue>&apos;No&apos;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Late And AOT</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Overdue__c</fullName>
        <label>Total Overdue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/EMAP_Invoice_TriggerHandler.cls
public with sharing class EMAP_Invoice_TriggerHandler {
	
	/* used to check Is invoive Late and AOT?
    *  Parameters: List of new Invoice records
    */
    public static void isLateAndAOT(List<Invoice__c> invoiceNewList){
        
        List<Id> accIdList = new List<Id>();
        
        //get list of Account Ids
        for(Invoice__c invoiceNew: invoiceNewList){
            accIdList.add(invoiceNew.Account__c);
        }
    
        Map<Id, Account> accMap = new Map<Id, Account>([Select Id, Name, Total_Overdue__c, Program__r.AOT_Amount__c  From Account Where Id In: accIdList]);
        
        for(Invoice__c invoice: invoiceNewList){
            Account acc = accMap.get(invoice.Account__c);
            
            if(invoice.Late_And_AOT__c == null){
            	invoice.Late_And_AOT__c = 'No';
            }
            
            //check Is invoice Late and AOT? 
            if( (invoice.Late_And_AOT__c == 'No') && 
                (invoice.Is_Late_Payer__c && acc.Total_Overdue__c > acc.Program__r.AOT_Amount__c) ) {
                    invoice.Late_And_AOT__c = 'Yes';
            }
        }
    }

}