src/objects/Lead_RR_Queue_Member_Assignments__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Round_Robin_Queue__c</fullName>
        <label>Lead Round Robin Queue</label>
        <referenceTo>LeadRoundRobinQueue__c</referenceTo>
        <relationshipLabel>Lead RR Queue Member Assignments</relationshipLabel>
        <relationshipName>Lead_RR_Queue_Member_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Lead_RR_Queue_Member_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead RR Queue Member Assignments</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Lead_RR_Queue_Member_Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead RR Queue Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LeadRoundRobinQueue__c.object
<CustomObject>
</CustomObject>

src/objects/LeadRoundRobinQueueMember__c.object
<CustomObject>
</CustomObject>

src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Online Applications</relationshipLabel>
        <relationshipName>Online_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>OnlineApplicationOffer__c</referenceTo>
        <relationshipLabel>Online Applications</relationshipLabel>
        <relationshipName>Online_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Online Applications</relationshipLabel>
        <relationshipName>Online_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions_Version__c</fullName>
        <formula>Offer__r.Terms_and_Conditions_Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Terms and Conditions Version</label>
        <type>Text</type>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OnlineApplicationOffer__c.object
<CustomObject>
    <description>Forseva Online Application Project</description>
    <fields>
        <fullName>Application_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complete_Later_Text__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The text served to the customer if they click the &quot;Save and Complete Later&quot; button.</inlineHelpText>
        <label>Complete Later Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EchoSign_User_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This must be the email (login ID) for a valid user associated with your EchoSign account.</inlineHelpText>
        <label>EchoSign User Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions_Version__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This must match the attached file name EXACTLY.  The attached file must be a valid HTML file with a file extension of &apos;html&apos;.</inlineHelpText>
        <label>Terms and Conditions Version</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Online Application Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Online Application Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OnlineApplicationWeightedRoundRobinTest.cls
@isTest
private class OnlineApplicationWeightedRoundRobinTest 
{
	static testMethod void test1() 
    {
        LeadRoundRobinQueue__c rrq = new LeadRoundRobinQueue__c();
        rrq.Name = 'Test';
        rrq.Standard_Queue_Id__c = [SELECT QueueId
                                    FROM QueueSobject q
                                    WHERE SObjectType = 'OnlineApplication__c' limit 1].QueueId;
        rrq.Next_Position__c = 1;
        insert rrq;

        LeadRoundRobinQueueMember__c rrm = new LeadRoundRobinQueueMember__c();
        rrm.Lead_Round_Robin_Queue__c = rrq.Id;
        rrm.Member__c = [SELECT Id FROM User WHERE isActive = TRUE LIMIT 1].Id;
        rrm.Position__c = 1;
        insert rrm;

        Account acc1 = new Account(Name = 'Test Acc');
        insert acc1;
        
        OnlineApplicationOffer__c oao = new OnlineApplicationOffer__c (
            Name = 'TestOffer-01',
            Application_Title__c = 'TestTitle',
            Complete_Later_Text__c = 'Test',
            EchoSign_User_Email__c = 'test@test.com',
            Terms_and_Conditions_Version__c = 'TestVersion-01'
        );
        
        insert oao;
        
        OnlineApplication__c req = new OnlineApplication__c();
        req.Account__c = acc1.Id;
        req.Offer__c = oao.Id;
        //req.Opportunity__c = opp.Id;
        insert req;

        req.OwnerId = [SELECT 
                       		Lead_Round_Robin_Queue__r.Standard_Queue_Id__c 
                       FROM 
                       		LeadRoundRobinQueueMember__c 
                       WHERE 
                       		Lead_Round_Robin_Queue__r.isActive__c = TRUE LIMIT 1].Lead_Round_Robin_Queue__r.Standard_Queue_Id__c;

        update req;

        Lead_RR_Queue_Member_Assignments__c ll = new Lead_RR_Queue_Member_Assignments__c();
        ll.weight__c = 4;
        ll.Member__c = [select id from user where isActive = true limit 1].id;
        ll.Lead_Round_Robin_Queue__c = rrq.id;
        insert ll;

        Lead_RR_Queue_Member_Assignments__c ll2 = new Lead_RR_Queue_Member_Assignments__c();
        ll2.weight__c = 3;
        ll2.Member__c = [select id from user where isActive = true and id != :rrm.member__c limit 1].id;
        ll2.Lead_Round_Robin_Queue__c = rrq.id;
        insert ll2;

        RoundRobinDistribution.loadDistribution(rrq.id);
    }
}