src/objects/Lead_RR_Queue_Member_Assignments__c.object
<CustomObject>
    <fields>
        <fullName>Lead_Round_Robin_Queue__c</fullName>
        <label>Lead Round Robin Queue</label>
        <referenceTo>LeadRoundRobinQueue__c</referenceTo>
        <relationshipLabel>Lead RR Queue Member Assignments</relationshipLabel>
        <relationshipName>Lead_RR_Queue_Member_Assignments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Lead_RR_Queue_Member_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <label>Weight</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Lead RR Queue Member Assignments</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Lead_RR_Queue_Member_Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead RR Queue Member Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LeadRoundRobinQueue__c.object
<CustomObject>
</CustomObject>

src/objects/LeadRoundRobinQueueMember__c.object
<CustomObject>
</CustomObject>

src/classes/TestWeightedRoundRobin.cls
public class TestWeightedRoundRobin {

   static testMethod void test1(){
    
      LeadRoundRobinQueue__c rrq = new LeadRoundRobinQueue__c();
      rrq.Name = 'Test';
      rrq.Standard_Queue_Id__c = [Select QueueId
                                              From QueueSobject q
                                              where sobjecttype = 'Lead'
                                              limit 1].QueueId; 
      rrq.Next_Position__c = 1;
      insert rrq;
      
      LeadRoundRobinQueueMember__c rrm = new LeadRoundRobinQueueMember__c();
      rrm.Lead_Round_Robin_Queue__c = rrq.id;
      rrm.Member__c = [select id from user where isActive = true limit 1].id;
      rrm.Position__c = 1;
      insert rrm;
    
    
    
      lead l = [select id, ownerid from lead where isconverted = false limit 1];
      
      l.ownerid = [Select Lead_Round_Robin_Queue__r.Standard_Queue_Id__c From LeadRoundRobinQueueMember__c where Lead_Round_Robin_Queue__r.isActive__c = true limit 1].Lead_Round_Robin_Queue__r.Standard_Queue_Id__c ;
      
      try
      {
      	update l;
      }
      catch (Exception e)
      {
      	
      }
      
      Lead_RR_Queue_Member_Assignments__c ll = new Lead_RR_Queue_Member_Assignments__c();
      ll.weight__c = 4;
      ll.Member__c = [select id from user where isActive = true limit 1].id;
      ll.Lead_Round_Robin_Queue__c = rrq.id;
      insert ll;
      
      Lead_RR_Queue_Member_Assignments__c ll2 = new Lead_RR_Queue_Member_Assignments__c();
      ll2.weight__c = 3;
      ll2.Member__c = [select id from user where isActive = true and id != :rrm.member__c limit 1].id;
      ll2.Lead_Round_Robin_Queue__c = rrq.id;
      insert ll2;
      
      RoundRobinDistribution.loadDistribution(rrq.id);
    
   }
   


}