src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>AO_Date_of_Birth__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter date of birth in MM/DD/YYYY format.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>AO_First_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_Last_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Experian_Premier_Attributes__c</fullName>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>Experian Premier Attributes</label>
        <length>9000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Inquiry_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Inquiry Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>On_File_Address_High_Risk__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>On File Address High Risk</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PG_Data__c</fullName>
        <description>All data from the PG credit bureau response</description>
        <encryptionScheme>ProbabilisticEncryption</encryptionScheme>
        <label>PG Data</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PG_High_Credit_Amount__c</fullName>
        <label>PG High Credit Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PG_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PG Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PG_Score__c</fullName>
        <description>Consumer FICO Score for Personal Guarantor</description>
        <label>PG FICO Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Security_Statement_on_Report__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Fraud Indicator returned from Experian</inlineHelpText>
        <label>Security Statement on Report</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type_of_Business__c</fullName>
        <inlineHelpText>Type of business organization your individual or group is formed as.</inlineHelpText>
        <label>Type of Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Corporation</fullName>
                </value>
                <value>
                    <fullName>Partnership</fullName>
                </value>
                <value>
                    <fullName>Non-Profit</fullName>
                </value>
                <value>
                    <fullName>Limited Liability Company</fullName>
                </value>
                <value>
                    <fullName>Sole Proprietorship</fullName>
                </value>
                <value>
                    <fullName>Bank/Bank Holding Co/Credit Union</fullName>
                </value>
                <value>
                    <fullName>Federal/State/Local Government Agency or Authority</fullName>
                </value>
                <value>
                    <fullName>Insurance Company</fullName>
                </value>
                <value>
                    <fullName>Investment Company/Adviser</fullName>
                </value>
                <value>
                    <fullName>Non-Statutory Trust</fullName>
                </value>
                <value>
                    <fullName>Public Accounting Firm</fullName>
                </value>
                <value>
                    <fullName>Public Company and Majority Owned Affiliate</fullName>
                </value>
                <value>
                    <fullName>Unincorporated Association</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreditDecisionEngineQueueableTest.cls
@isTest
public class CreditDecisionEngineQueueableTest {

    public static void testExperianOnlineApp(){
        /*
        need onlineapp with pg required false (nothing should happen)
        need onlineapps with PG_Required__c
        need one with Type_of_Business__c==Proprietorship
        need one with Type_of_Business__c==null (or not proprietorship or partnership)
        need one with AO_First_Name__c and AO_Last_Name__c null, AO_Name__c not null
        need one with AO_First_Name__c and AO_Last_Name__c not null, AO_Name__c not null
        need AO_Date_of_Birth__c not null
        */
        OnlineApplication__c oa1 = [SELECT Id FROM OnlineApplication__c WHERE AO_NAME__C = 'Peter File' AND PG_Required__c = false LIMIT 1];
        OnlineApplication__c oa2 = [SELECT Id FROM OnlineApplication__c WHERE AO_NAME__C = 'Maurice Moss' AND PG_Required__c = true LIMIT 1];
        OnlineApplication__c oa3 = [SELECT Id FROM OnlineApplication__c WHERE AO_NAME__C = 'Peter File' AND PG_Required__c = true LIMIT 1];

        List<Id> oaList = new List<Id>{oa1.Id,oa2.Id,oa3.Id};
        Test.startTest();
        //Test.setMock(HTTPCalloutMock.class,MockCalloutGenerator.makeRequest('expGood'));
        for(Id i : oaList)
            System.enqueueJob(new CreditUtilQueueable_ExperianPG(i));
        Test.stopTest();

        oa1 = [SELECT Id,PG_Score__c,PG_Data__c,Experian_Premier_Attributes__c,PG_High_Credit_Amount__c,Inquiry_Address_High_Risk__c,Security_Statement_on_Report__c,On_File_Address_High_Risk__c FROM OnlineApplication__c WHERE Id = :oa1.Id LIMIT 1];
        oa2 = [SELECT Id,PG_Score__c,PG_Data__c,Experian_Premier_Attributes__c,PG_High_Credit_Amount__c,Inquiry_Address_High_Risk__c,Security_Statement_on_Report__c,On_File_Address_High_Risk__c FROM OnlineApplication__c WHERE Id = :oa2.Id LIMIT 1];
        oa3 = [SELECT Id,PG_Score__c,PG_Data__c,Experian_Premier_Attributes__c,PG_High_Credit_Amount__c,Inquiry_Address_High_Risk__c,Security_Statement_on_Report__c,On_File_Address_High_Risk__c FROM OnlineApplication__c WHERE Id = :oa3.Id LIMIT 1];


    }

    public static void testExperianAppRequest(){
        
    }

    public static void testExperianCPAppRequest(){
        
    }
}