src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>AO_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AO_Work_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Work Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Business_Street_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Your business&apos; physical street address.  Not a PO box (Ex: 123 Main Street).</inlineHelpText>
        <label>Street Address</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>City</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Federal_Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Your business&apos; Employer Identification Number (EIN) or business owner&apos;s social security number, if there is no EIN.</inlineHelpText>
        <label>Federal Tax ID #</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IP_Address__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>IP Address</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The name of your business as listed on your business license or according to the Federal Government.</inlineHelpText>
        <label>Legal Business Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Phone #</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State / Province</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Country__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AB</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>AS</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>BC</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>FM</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>GU</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MB</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MH</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ThreatMetrix_Request_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ThreatMetrix Request ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trade_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The name your business is typically called in your day-to-day operations.</inlineHelpText>
        <label>Trade Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/ThreatMetrixService.cls
/**
* Copyright 2014 Forseva, LLC.  All rights reserved.
*/
public with sharing class ThreatMetrixService {

    @future(callout=true)
    public static void processApplication(Id onlineApplicationId) {
    	    	
        ThreatMetrixService tms = new ThreatMetrixService();
        String response = tms.process(onlineApplicationId);
        System.debug('THREATMETRIX RESPONSE: ' + response);
        
        try {
        
        	Map<String, String> results = new Map<String, String>();

       		for(String pair : (EncodingUtil.urlDecode(response, 'UTF-8')).split('&')) {
                
        		results.put(pair.split('=')[0], pair.split('=')[1]);
                
       		}
        
        	List<OnlineApplication__c> onlineApplications = [SELECT Id, ThreatMetrix_Request_ID__c FROM OnlineApplication__c WHERE Id =: onlineApplicationId LIMIT 1];
        
        	if(onlineApplications.size() > 0) {
        
        		onlineApplications[0].ThreatMetrix_Request_ID__c = results.get('request_id');
        
        		upsert onlineApplications[0];
            
        	}
            
        }
        catch(Exception e) {
            System.debug('THREATMETRIX EXCEPTION: Unable to get request_id');
        }
        
    }

    public ThreatMetrixService() {}

    public String process(Id onlineApplicationId) {

        Map<String,String> parms = new Map<String,String>();

        try {

            OnlineApplication__c oaso = (OnlineApplication__c)SOUtility.getCompleteSObject(OnlineApplication__c.SOBjectType, onlineApplicationId);
            String baseUrl = OnlineApplicationParameters.getThreatMetrixURL();

            Http h = new Http();
            HttpRequest request = new HttpRequest();
            request.setTimeout(60000);
            request.setMethod('GET');

            parms.put('org_id', OnlineApplicationParameters.getThreatMetrixOrgId());
            parms.put('api_key', OnlineApplicationParameters.getThreatMetrixAPIKey());
            parms.put('session_id', '' + onlineApplicationId);                        
            parms.put('service_type', 'device');
            parms.put('event_type', 'ACCOUNT_CREATION');
            parms.put('transaction_id', oaso.Id);
            parms.put('account_name', oaso.Legal_Business_Name__c);
            parms.put('local_attrib_1', oaso.Trade_Name__c); 
            if(oaso.Federal_Tax_ID__c != null) {
                parms.put('ssn_hash', EncodingUtil.convertToHex(Crypto.generateDigest('SHA1', Blob.valueOf(oaso.Federal_Tax_ID__c))));
            }
            parms.put('account_address_street1', oaso.Business_Street_Address__c);
            parms.put('account_address_city', oaso.City__c);
            parms.put('account_address_state', oaso.State__c);
            parms.put('account_address_zip', oaso.Zip_Code__c);
            parms.put('account_telephone', oaso.Phone_Number__c);
            parms.put('local_attrib_2', oaso.Phone_Number__c);
            parms.put('local_attrib_3', oaso.AO_Name__c);
            parms.put('account_email', oaso.AO_Work_Email__c);
            parms.put('shipping_address_street1', oaso.Business_Street_Address__c);
            parms.put('shipping_address_city', oaso.City__c);
            parms.put('shipping_address_state', oaso.State__c);
            parms.put('shipping_address_zip', oaso.Zip_Code__c);
            parms.put('local_attrib_4', oaso.AO_Name__c);
            parms.put('local_attrib_5', oaso.AO_Work_Email__c);            
            parms.put('input_ip_address', oaso.IP_Address__c);

            String endpoint = baseUrl + '?' + mapToString(parms);
            request.setEndpoint(endpoint);
            if(!Test.isRunningTest()) {
                HttpResponse response = h.send(request);
        	    return response.getBody();
            }
            else {
                return 'test response';
            }
        }
        catch(Exception e) {
        	String msg = 'ERROR CALLING THREATMETRIX:' + e.getMessage() + ' -- ' + parms;
            System.debug(msg);
            return msg;
        }        
    }

    //------------------------
    // private
    //------------------------

    private String mapToString(Map<String,String> parms) {
    
        String parmString = '';
        List<String> keyList = new List<String>();
        keyList.addAll(parms.keySet());
                
        for(String key : keyList) {
        	String value = parms.get(key);
        	if(value != null) {
                if(parmString.length() > 0) {
                    parmString += '&';
                }
                parmString += (key + '=' + EncodingUtil.urlEncode(value, 'UTF-8'));
        	}
        }
        
        return parmString;
    }

}

// EOF