src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>Application_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Business_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The name of your business as listed on your business license or according to the Federal Government.</inlineHelpText>
        <label>Legal Business Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Stage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Saved-Complete</fullName>
                </value>
                <value>
                    <fullName>Saved-PaperApp</fullName>
                </value>
                <value>
                    <fullName>Saved-eApp</fullName>
                </value>
                <value>
                    <fullName>Saved-Incomplete</fullName>
                </value>
                <value>
                    <fullName>App-Incomplete</fullName>
                </value>
                <value>
                    <fullName>Prefill in Progress</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost</fullName>
                </value>
                <value>
                    <fullName>Decisioned</fullName>
                </value>
                <value>
                    <fullName>Credit-Incomplete</fullName>
                </value>
                <value>
                    <fullName>Saved-Rereview</fullName>
                </value>
                <value>
                    <fullName>Decisioned-Rereview</fullName>
                </value>
                <value>
                    <fullName>Pending Setup</fullName>
                </value>
                <value>
                    <fullName>Pending Setup Data</fullName>
                </value>
                <value>
                    <fullName>Pending Setup-Generic</fullName>
                </value>
                <value>
                    <fullName>Setup Complete</fullName>
                </value>
                <value>
                    <fullName>Cards Produced</fullName>
                </value>
                <value>
                    <fullName>Cards Shipped</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Manual Review</fullName>
                </value>
                <value>
                    <fullName>PrePay</fullName>
                </value>
                <value>
                    <fullName>PrePay Requested</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Audit Complete</fullName>
                </value>
                <value>
                    <fullName>Pending Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>eSignature_Status__c</fullName>
        <label>eSignature Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Executed</fullName>
                </value>
                <value>
                    <fullName>Executed</fullName>
                </value>
                <value>
                    <fullName>Executed and Received</fullName>
                </value>
                <value>
                    <fullName>Executed and Invalid Signer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/UOnlineApplicationHomePgComp.cls
/**
    ClassName  : UOnlineApplicationHomePgComp 
    Case Number :00022578
    Description : Retrive the Online Applications owned by the logged in user
*/

public with sharing class UOnlineApplicationHomePgComp {
    
    public String applicationFilter { get; set; }
    
    public List<OnlineApplication__c> lstOnlineApplication { get;set; }
    
    public UOnlineApplicationHomePgComp() {
        
        applicationFilter = 'completed';
        
        getApplications();
        
    }
    
    public void getApplications() {
        
        System.debug(applicationFilter);
        
        if(applicationFilter.equalsIgnoreCase('completed')) {
            lstOnlineApplication = new List<OnlineApplication__c>();
        	lstOnlineApplication = [ Select Name, eSignature_Status__c, Status__c, Legal_Business_Name__c, Id, Application_Title__c 
                                 From OnlineApplication__c 
                                 where OwnerId =: UserInfo.getUserId() and (NOT Status__c LIKE '%Incomplete%')
                                 ORDER BY CreatedDate DESC ];
        }
        else {
            lstOnlineApplication = new List<OnlineApplication__c>();
        	lstOnlineApplication = [ Select Name, eSignature_Status__c, Status__c, Legal_Business_Name__c, Id, Application_Title__c 
                                 From OnlineApplication__c 
                                 where OwnerId =: UserInfo.getUserId() and (Status__c LIKE '%Incomplete%')
                                 ORDER BY CreatedDate DESC ];
        }
        
    }
}