src/objects/OnlineApplication__c.object
<CustomObject>
    <description>Forseva Online Application Project (OTR application request)</description>
    <fields>
        <fullName>Application_Stage__c</fullName>
        <description>This will be set up to be automated based on the Status.</description>
        <inlineHelpText>This will be set up to be automated based on the Status.</inlineHelpText>
        <label>Application Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Application</fullName>
                    <default>true</default>
                    <label>Application</label>
                </value>
                <value>
                    <fullName>Adjudication</fullName>
                </value>
                <value>
                    <fullName>Credit Follow-up</fullName>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                </value>
                <value>
                    <fullName>Expansion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Application_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Offer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Offer</label>
        <referenceTo>OnlineApplicationOffer__c</referenceTo>
        <relationshipLabel>Online Applications</relationshipLabel>
        <relationshipName>Online_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Application_Stage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Saved-Complete</fullName>
                </value>
                <value>
                    <fullName>Saved-PaperApp</fullName>
                </value>
                <value>
                    <fullName>Saved-eApp</fullName>
                </value>
                <value>
                    <fullName>Saved-Incomplete</fullName>
                </value>
                <value>
                    <fullName>App-Incomplete</fullName>
                </value>
                <value>
                    <fullName>Prefill in Progress</fullName>
                </value>
                <value>
                    <fullName>Closed/Lost</fullName>
                </value>
                <value>
                    <fullName>Decisioned</fullName>
                </value>
                <value>
                    <fullName>Credit-Incomplete</fullName>
                </value>
                <value>
                    <fullName>Saved-Rereview</fullName>
                </value>
                <value>
                    <fullName>Decisioned-Rereview</fullName>
                </value>
                <value>
                    <fullName>Pending Setup</fullName>
                </value>
                <value>
                    <fullName>Pending Setup Data</fullName>
                </value>
                <value>
                    <fullName>Pending Setup-Generic</fullName>
                </value>
                <value>
                    <fullName>Setup Complete</fullName>
                </value>
                <value>
                    <fullName>Cards Produced</fullName>
                </value>
                <value>
                    <fullName>Cards Shipped</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Manual Review</fullName>
                </value>
                <value>
                    <fullName>PrePay</fullName>
                </value>
                <value>
                    <fullName>PrePay Requested</fullName>
                </value>
                <value>
                    <fullName>Declined</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
                <value>
                    <fullName>Audit Complete</fullName>
                </value>
                <value>
                    <fullName>Pending Decision</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions_Version__c</fullName>
        <formula>Offer__r.Terms_and_Conditions_Version__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Terms and Conditions Version</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Established__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>If your business is a corporation, the year it was incorporated.  Example: 1980.</inlineHelpText>
        <label>Year Established</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Online Application</label>
    <nameField>
        <displayFormat>Application-{0}</displayFormat>
        <label>Application Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Online Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OnlineApplicationOffer__c.object
<CustomObject>
    <description>Forseva Online Application Project</description>
    <fields>
        <fullName>Application_Title__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Application Title</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Complete_Later_Text__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The text served to the customer if they click the &quot;Save and Complete Later&quot; button.</inlineHelpText>
        <label>Complete Later Text</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EchoSign_User_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This must be the email (login ID) for a valid user associated with your EchoSign account.</inlineHelpText>
        <label>EchoSign User Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Terms_and_Conditions_Version__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This must match the attached file name EXACTLY.  The attached file must be a valid HTML file with a file extension of &apos;html&apos;.</inlineHelpText>
        <label>Terms and Conditions Version</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Online Application Offer</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Offer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Online Application Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SBQQ__Quote__c.object
<CustomObject>
</CustomObject>

src/objects/SBQQ__QuoteDocument__c.object
<CustomObject>
    <fields>
        <fullName>Incorporation_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Incorporation Date</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Online_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Online Application</label>
        <referenceTo>OnlineApplication__c</referenceTo>
        <relationshipLabel>Quote Documents</relationshipLabel>
        <relationshipName>Quote_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/QuoteDocumentTriggerHandlerTest.cls
@isTest
public class QuoteDocumentTriggerHandlerTest {
    public static testmethod void insertDoc() {
        OnlineApplicationOffer__c offer1 = new OnlineApplicationOffer__c(Application_Title__c = 'test', Complete_Later_Text__c = 'test', EchoSign_User_Email__c = 'test@test.com', Terms_and_Conditions_Version__c = '1.0');
        insert offer1;

        SBQQ__Quote__c q1 = new SBQQ__Quote__c(Online_Application_Offer__c = offer1.Id);
        insert q1;
        q1 = [select OwnerId from SBQQ__Quote__c where Id = :q1.Id];


        SBQQ__QuoteDocument__c doc1 = new SBQQ__QuoteDocument__c(SBQQ__SignatureStatus__c = 'Signed', Incorporation_Date__c = '2008', SBQQ__Quote__c = q1.Id);
        insert doc1;
        doc1 = [select Online_Application__c, SBQQ__Quote__r.OwnerId from SBQQ__QuoteDocument__c where Id = : doc1.Id];
        System.assert(doc1.Online_Application__c != null);
        OnlineApplication__c app = [select OwnerId, Offer__c, Application_Stage__c, Status__c,  Year_Established__c from OnlineApplication__c where Id = :doc1.Online_Application__c];

        System.assertEquals(q1.OwnerId, app.OwnerId);
        System.assertEquals(offer1.Id, app.Offer__c);
        System.assertEquals('Application', app.Application_Stage__c);
        System.assertEquals('Saved-Complete', app.Status__c);
        System.assertEquals('2008', app.Year_Established__c);
    }

    public static testmethod void updateDoc() {
        OnlineApplicationOffer__c offer1 = new OnlineApplicationOffer__c(Application_Title__c = 'test', Complete_Later_Text__c = 'test', EchoSign_User_Email__c = 'test@test.com', Terms_and_Conditions_Version__c = '1.0');
        insert offer1;
        SBQQ__Quote__c q1 = new SBQQ__Quote__c();
        insert q1;
        q1 = [select OwnerId from SBQQ__Quote__c where Id = :q1.Id];

        SBQQ__QuoteDocument__c doc1 = new SBQQ__QuoteDocument__c(SBQQ__Quote__c = q1.Id);
        insert doc1;

        List<OnlineApplication__c> appList = [select Id from OnlineApplication__c];
        System.assertEquals(0, appList.size());

        q1.Online_Application_Offer__c = offer1.Id;
        update q1;

        doc1.Incorporation_Date__c = '2008' ;
        update doc1;

        appList = [select Id from OnlineApplication__c];
        System.assertEquals(0, appList.size());

        doc1.SBQQ__SignatureStatus__c = 'Signed';
        update doc1;

        appList = [select OwnerId, Offer__c, Application_Stage__c, Status__c, Year_Established__c from OnlineApplication__c];
        System.assertEquals(1, appList.size());

        doc1 = [select Online_Application__c, SBQQ__Quote__r.OwnerId from SBQQ__QuoteDocument__c where Id = : doc1.Id];
        System.assert(doc1.Online_Application__c != null);

        OnlineApplication__c app = appList[0];

        System.assertEquals(q1.OwnerId, app.OwnerId);
        System.assertEquals(offer1.Id, app.Offer__c);
        System.assertEquals('Application', app.Application_Stage__c);
        System.assertEquals('Saved-Complete', app.Status__c);
        System.assertEquals('2008', app.Year_Established__c);

    }

    public static testmethod void bulkInsertDoc() {
        OnlineApplicationOffer__c offer1 = new OnlineApplicationOffer__c(Application_Title__c = 'test', Complete_Later_Text__c = 'test', EchoSign_User_Email__c = 'test@test.com', Terms_and_Conditions_Version__c = '1.0');
        insert offer1;
        SBQQ__Quote__c q1 = new SBQQ__Quote__c(Online_Application_Offer__c = offer1.Id);
        insert q1;
        List<SBQQ__QuoteDocument__c> docList = new List<SBQQ__QuoteDocument__c>();
        for (Integer i = 0; i < 200; i++) {
            SBQQ__QuoteDocument__c doc1 = new SBQQ__QuoteDocument__c(SBQQ__SignatureStatus__c = 'Signed', Incorporation_Date__c = '2008', SBQQ__Quote__c = q1.Id);
            docList.add(doc1);
        }

        insert docList;

        for (SBQQ__QuoteDocument__c doc : [select Online_Application__c, SBQQ__Quote__r.OwnerId from SBQQ__QuoteDocument__c]) {
            System.assert(doc.Online_Application__c != null);
        }

        List<OnlineApplication__c> appList = [select Application_Stage__c, Status__c, Year_Established__c from OnlineApplication__c];

        System.assertEquals(200,  appList.size());

        for (OnlineApplication__c app : appList ) {
            System.assertEquals('Application', app.Application_Stage__c);
            System.assertEquals('Saved-Complete', app.Status__c);
            System.assertEquals('2008', app.Year_Established__c);

        }
    }

    public static testmethod void insertUpdateDoc() {
        OnlineApplicationOffer__c offer1 = new OnlineApplicationOffer__c(Application_Title__c = 'test', Complete_Later_Text__c = 'test', EchoSign_User_Email__c = 'test@test.com', Terms_and_Conditions_Version__c = '1.0');
        insert offer1;
        SBQQ__Quote__c q1 = new SBQQ__Quote__c(Online_Application_Offer__c = offer1.Id);
        insert q1;
        SBQQ__QuoteDocument__c doc1 = new SBQQ__QuoteDocument__c(SBQQ__SignatureStatus__c = 'Signed', SBQQ__Quote__c = q1.Id);
        insert doc1;

        List<OnlineApplication__c> appList = [select Id from OnlineApplication__c];
        System.assertEquals(1, appList.size());

        doc1.Incorporation_Date__c = '2012';
        update doc1;

        appList = [select Id, Year_Established__c from OnlineApplication__c];
        System.assertEquals(1, appList.size());
        System.assertEquals('2012', appList[0].Year_Established__c);
    }
}