src/objects/PartnersCommunityLogos__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Allow admin user to set a unique image to each partner profile for branding purposes in the community</description>
    <fields>
        <fullName>FileName__c</fullName>
        <description>Complete filename, with extension, of the logo to be used for the profile or user.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FileName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PartnersCommunityLogos</label>
</CustomObject>

src/classes/PartnerCommunityCustomTemplateCtlTest.cls
@isTest
private class PartnerCommunityCustomTemplateCtlTest {
    @testSetup
    static void setup(){
        UtilityTestLoader.setAutomation(false);
    }

    static testmethod void testController() {
        PartnersCommunityLogos__c settings = new PartnersCommunityLogos__c();
        settings.SetupOwnerId = UserInfo.getProfileId();
        settings.FileName__c = 'test.png';
        insert settings;

        Test.startTest();
        String logo = PartnerCommunityCustomTemplateController.getLogoServ();
        Test.stopTest();
        
        System.assertEquals('test.png', logo);
    }
}