src/objects/PartnersCommunityLogos__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Allow admin user to set a unique image to each partner profile for branding purposes in the community</description>
    <fields>
        <fullName>FileName__c</fullName>
        <description>Complete filename, with extension, of the logo to be used for the profile or user.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>FileName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PartnersCommunityLogos</label>
</CustomObject>

src/classes/Test_PartnersCommHeaderImg.cls
@isTest
private class Test_PartnersCommHeaderImg {
	
//	@isTest static void test_method_one() {
//
//        test.starttest();
//	PartnersCommunityLogos__c pcl = new PartnersCommunityLogos__c();
//        //pcl.Name = 'test';
//        //pcl.ProfileId__c = '111111111111111111';
//        pcl.FileName__c = 'test.png';
//        insert pcl;
//
//        /*
//        Id profId = [Select Id from Profile Where Name = 'System Administrator' LIMIT 1].Id;
//	PartnersCommunityLogos__c pcl2 = new PartnersCommunityLogos__c();
//        pcl2.Name = 'test2';
//        pcl2.ProfileId__c = profId;
//        pcl2.FileName__c = 'test2.png';
//        insert pcl2;
//        */
//
//        test.stoptest();
//
//        PartnersCommHeaderImgController pc = new PartnersCommHeaderImgController();
//        string x = pc.logofilePath;
//
//
//
//	}

	
}