src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Analytics_Body_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Analytics - Body Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Analytics_Head_Block__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Area for google analytics code</inlineHelpText>
        <label>Analytics - Head Block</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Color_2__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 2</label>
        <length>800</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Inside_Sales_Phone_Number__c</fullName>
        <description>Phone number of inside sales for the program.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Inside Sales Phone Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OTRBOCAErrorController.cls
public class OTRBOCAErrorController {
    
    public Program__c program { get; set; }
    
    public String errorReferenceNumber { 
        get {
            return ApexPages.CurrentPage().getParameters().get('errorReferenceNumber');
        }
    }
    
    public String errorTimeStamp { 
        get {
            return String.valueOf(Date.today());
        }
    }
    
    public String programParameter { 
        get { 
            return ApexPages.CurrentPage().getParameters().get('pgm');
        }                           
	}
    
    public String languageCode { 
        get {
            String languageCodeParameter = ApexPages.CurrentPage().getParameters().get('lang');
        	
            if(languageCodeParameter == null || languageCodeParameter == '') {
                return 'en_us';
            }
            return languageCodeParameter;
    	}
	}
    
    public String errorCode {
        get {
            String errorCodeParameter = ApexPages.currentPage().getParameters().get('errorCode');
            
            if(errorCodeParameter == '' || errorCodeParameter == null) {
                return '1';
            }
            
            return errorCodeParameter;
        }
    }
    
    public OTRBOCAErrorController() {
        
        if(!String.isEmpty(programParameter)) {
            List<Program__c> programs = [SELECT Id, Analytics_Body_Block__c, Analytics_Head_Block__c,  
                                         Inside_Sales_Phone_Number__c, Brand_Color_1__c, Brand_Color_2__c
                                         FROM Program__c WHERE Brand_Short_Name__c = :programParameter];
            
            if(!programs.isEmpty()) {
				program = programs[0]; 
			}
        }
        
    }
    
}