src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Color_1__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter a hexadecimal color value in the format: #ffffff  or copy and paste css gradient code from the color picker button here.</inlineHelpText>
        <label>Brand Color 1</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Brand_Long_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Brand Long Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brand_Short_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This value is used to determine which brand/program is associated with the BOCA.  It is passed in via the url (example would be &apos;?pgm=wex&apos;)</inlineHelpText>
        <label>Brand Short Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Custom_Email_Header_URL__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>URL to wexhosted for this program&apos;s email header</inlineHelpText>
        <label>Custom Email Header URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fleet_Data_Capture_Email_Template__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Fleet Data Capture Email Template</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fleet_Data_Capture_Form_Delivery__c</fullName>
        <label>Fleet Card Delivery Timeframe</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>5-7</fullName>
                </value>
                <value>
                    <fullName>2-3</fullName>
                </value>
                <value>
                    <fullName>3-5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Implementation_Team_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Implementation Team Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Publish_Fleet_Data_Capture_Form__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Publish Fleet Data Capture Form</label>
        <type>Checkbox</type>
    </fields>
    <label>Program</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/FleetEnrollmentValidateTest.cls
@isTest
public class FleetEnrollmentValidateTest {

    @testSetup
    static void setup(){
        UtilityTestLoader.setAutomation(false);
    }

    static testMethod void testFleetEnrollmentValidate() {
        
        Test.startTest();
        
        // Setup Program
        Program__c program = new Program__c();
        
        program.Name = 'Sunoco Fleet';         
      
        insert program;
        
        try {
        	program.Publish_Fleet_Data_Capture_Form__c = true;
        	update program;
        }
        catch(Exception e) {
            Boolean expectedExceptionThrown =  e.getMessage().contains('Please ensure Brand Short Name is not blank for the Fleet Data Capture Form') ? true : false;
			System.AssertEquals(expectedExceptionThrown, true);
        }
        
        Program__c updatedProgram = [SELECT Id, Publish_Fleet_Data_Capture_Form__c FROM Program__c WHERE Id = :program.Id];
        
        System.assert(updatedProgram.Publish_Fleet_Data_Capture_Form__c != true);
              
        // Setup Attachments
        Attachment cardImage = new Attachment();
        cardImage.Name = 'ui-credit-card.png';
        Blob cardImageBlob = Blob.valueOf('Unit Test Attachment Body');
        cardImage.body = cardImageBlob;
        cardImage.parentId = program.Id;
        upsert cardImage;
        
        Attachment cardImageNoText = new Attachment();
        cardImageNoText.Name = 'ui-credit-card-no-text.png';
        Blob cardImageNoTextBlob = Blob.valueOf('Unit Test Attachment Body');
        cardImageNoText.body = cardImageNoTextBlob;
        cardImageNoText.parentId = program.Id;
        upsert cardImageNoText;

        program.Brand_Short_Name__c = 'sunoco';
        program.Custom_Email_Header_URL__c = 'http://www.wexhosted.com/email/revolver/header_wexRevolver.jpg';
        program.Brand_Long_Name__c = 'Sunoco Fleet';
        program.Brand_Color_1__c = '#ccc';
        program.Implementation_Team_Number__c = '1-888-888-8888';
        program.Fleet_Data_Capture_Email_Template__c = '0000000';
        program.Fleet_Data_Capture_Form_Delivery__c = '2-3';
		program.Publish_Fleet_Data_Capture_Form__c = true;

	    upsert program;

        updatedProgram = [SELECT Id, Publish_Fleet_Data_Capture_Form__c FROM Program__c WHERE Id = :program.Id];
        
        System.assert(updatedProgram.Publish_Fleet_Data_Capture_Form__c == true);
        
        Test.stopTest();
        
    }
    
}