src/objects/Refund_Adjustment__c.object
<CustomObject>
    <description>Captures Refund and Adjustment requests made by Customer Service and RSLPO.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Refunds/Adjustments</relationshipLabel>
        <relationshipName>Refunds_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount_Waived__c</fullName>
        <inlineHelpText>Amount to be adjusted (waived) or refunded</inlineHelpText>
        <label>Ref / Adj Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Refunds_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseNumber__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Case</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Case must be Service Operations or VAS - Retention Record Type.</errorMessage>
            <filterItems>
                <field>Case.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Operations, VAS - Retention, VAS - Retention, Service Operations</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Refunds/Adjustments</relationshipLabel>
        <relationshipName>Refunds_Adjustments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <label>Refund/Adjustment</label>
    <nameField>
        <displayFormat>RFADJ-{00000000}</displayFormat>
        <label>Refund/Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds/Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Adjustment</fullName>
        <active>true</active>
        <label>Adjustment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PriorRefundAdjustmentListControllerTest.cls
/**
 * Created by W083158 on 5/6/2019.
 */

@IsTest
private class PriorRefundAdjustmentListControllerTest {

    @testSetup
    static void setup() {

        Id AccountRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Service Operations').getRecordTypeId();

        Id CaseRecordType = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Service Operations').getRecordTypeId();

        List<User> userList = [SELECT Id, Name FROM User WHERE IsActive = true LIMIT 1];


        Account account = new Account(Name='TestAccount',RecordTypeId=AccountRecordType);
        insert account;

        Case testCase = new Case(Account = account, Subject = 'TestCase', RecordTypeId = CaseRecordType);
        insert testCase;

        Id[] refundAdjustmentRecordTypes = new Id[2];
        refundAdjustmentRecordTypes[0] = Schema.SObjectType.Refund_Adjustment__c.getRecordTypeInfosByName().get('Refund').getRecordTypeId();
        refundAdjustmentRecordTypes[1] = Schema.SObjectType.Refund_Adjustment__c.getRecordTypeInfosByName().get('Adjustment').getRecordTypeId();


        Id approvingUser = userList[0].Id;
        System.debug('### approvingUser='+approvingUser);

        for (Integer i=1; i<6; i++) {
            String approvalStatus = 'Pending';
            Id tempUser = null;
            Datetime decisionDate = null;
            if (i*150 < 500) {
                approvalStatus = 'Approved';
                tempUser   = approvingUser;
                decisionDate   = System.now();
            }

            Refund_Adjustment__c refadj = new Refund_Adjustment__c
                    (RecordTypeId = refundAdjustmentRecordTypes[Math.mod(i,2)],
                            Account__c = account.Id,
                            CaseNumber__c = testCase.Id,
                            Amount_Waived__c = i*150,
                            Approval_Status__c = approvalStatus,
                            Approver_Name__c   = tempUser,
                            Decision_Date__c   = decisionDate
                    );
            System.debug('### RefAdj '+i+': '+refadj);
            insert refadj;
        }
    }


    @IsTest
    static void testBehavior() {
        Test.startTest();
        Account testAccount = [SELECT Id FROM Account WHERE Name='TestAccount' LIMIT 1];
        System.debug('### testAccount Id = '+testAccount.Id);
        List<PriorRefundAdjustmentListController.RefundAdjustmentRecord> resultList = PriorRefundAdjustmentListController.getPriorRefundAdjustments(testAccount.Id);
        integer j=0;
        System.assert(resultList.size() > 0);
        for (PriorRefundAdjustmentListController.RefundAdjustmentRecord record : resultList) {
            System.debug('***** Record '+j);
            System.debug('Id='+record.Id);
            System.debug('IdLink='+record.IdLink);
            System.debug('Name='+record.Name);
            System.debug('DeveloperName='+record.DeveloperName);
            System.debug('CaseId='+record.CaseId);
            System.debug('CaseIdLink='+record.CaseIdLink);
            System.debug('CaseNumber='+record.CaseNumber);
            System.debug('Amount_Waived='+record.Amount_Waived);
            System.debug('Approval_Status='+record.Approval_Status);
            System.debug('Approver_Name='+record.Approver_Name);
            System.debug('Decision_Date='+record.Decision_Date);
            System.debug('CreatedDate='+record.CreatedDate);
            System.assert(record.Amount_Waived < 500 || record.Approval_Status != 'Approved');
            j++;
        }
        Test.stopTest();
    }

    @IsTest
    static void throwError() {
        Test.startTest();
        String message = '';
        try {
            List<PriorRefundAdjustmentListController.RefundAdjustmentRecord> resultList = PriorRefundAdjustmentListController.getPriorRefundAdjustments(null);
        } catch (Exception e) {
            message = e.getMessage();
        }
        System.assert(message.length() > 0);
        Test.stopTest();
    }
    
}