src/objects/Refund_Adjustment__c.object
<CustomObject>
    <description>Captures Refund and Adjustment requests made by Customer Service and RSLPO.</description>
    <fields>
        <fullName>Amount_Waived__c</fullName>
        <inlineHelpText>Amount to be adjusted (waived) or refunded</inlineHelpText>
        <label>Ref / Adj Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Refunds_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <label>Refund/Adjustment</label>
    <nameField>
        <displayFormat>RFADJ-{00000000}</displayFormat>
        <label>Refund/Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds/Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RefundAdjustmentTriggerHelper.cls
/**
 * Created by W083158 on 10/16/2019.
 */

public with sharing class RefundAdjustmentTriggerHelper {
    public static void insertRefAdj(List<Refund_Adjustment__c> records) {
        for (Refund_Adjustment__c refadj : records) {
            if (refadj.Amount_Waived__c > 500) {
                refadj.Approval_Status__c = 'Held';
            } else {
                refadj.Approval_Status__c = 'Pending';
            }
        }
    }

    public static void updateRefAdj(List<Refund_Adjustment__c> records, Map<Id, Refund_Adjustment__c> oldmap, Id userId) {
        Datetime now = System.now();

        for (Refund_Adjustment__c refadj : records) {
            Refund_Adjustment__c prior = oldmap.get(refadj.Id);
            if ((refadj.Approval_Status__c == 'Approved' || refadj.Approval_Status__c ==  'Denied') && refadj.Approval_Status__c != prior.Approval_Status__c) {
                refadj.Decision_Date__c = now;
                refadj.Approver_Name__c = userId;
            }
            
        }
    }
}