src/objects/Refund_Adjustment__c.object
<CustomObject>
    <description>Captures Refund and Adjustment requests made by Customer Service and RSLPO.</description>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Refunds_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Iten_id__c</fullName>
        <defaultValue>&quot;REFUND&quot;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>Iten ID</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Refund/Adjustment</label>
    <nameField>
        <displayFormat>RFADJ-{00000000}</displayFormat>
        <label>Refund/Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds/Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Adjustment</fullName>
        <active>true</active>
        <label>Adjustment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RefundsAdjustmentsBulkAction.cls
/**
 * Created by W083158 on 4/24/2019.
 */

public with sharing class RefundsAdjustmentsBulkAction {
    ApexPages.StandardSetController setCon;

    public RefundsAdjustmentsBulkAction(ApexPages.StandardSetController controller) {
        setCon = controller;
        ((Refund_Adjustment__c)(setCon.getRecord())).Approver_Name__c = UserInfo.getUserId();
        ((Refund_Adjustment__c)(setCon.getRecord())).Decision_Date__c = System.now();
    }

    public Integer getMySelectedSize() {
        return setCon.getSelected().size();
    }
    public Integer getMyRecordsSize() {
        return setCon.getRecords().size();
    }

    public List<SelectOption> getApprovalOptions() {
        List<SelectOption> newApprovalOptions = new List<SelectOption>();
        newApprovalOptions.add(new SelectOption('Pending','Pending',true)); //That last boolean is isDisabled.
        newApprovalOptions.add(new SelectOption('Approved','Approved'));
        newApprovalOptions.add(new SelectOption('Held','Held'));
        newApprovalOptions.add(new SelectOption('Denied','Denied'));
        return newApprovalOptions;
    }

    public PageReference updateRecords() {
        //IF all the records were selected, and all the records are the same record type,
        //forward to the appropriate report to extract and send to Finance.
        String recordTypeName;
        Boolean allAlike = (setCon.getSelected().size() == setCon.getResultSize());
        if (((Refund_Adjustment__c)(setCon.getRecord())).Approval_Status__c == 'Held') {
            ((Refund_Adjustment__c) (setCon.getRecord())).Decision_Date__c = null;
        } else if (((Refund_Adjustment__c)(setCon.getRecord())).Approval_Status__c == 'Approved') {
            for (Refund_Adjustment__c refadj : (List<Refund_Adjustment__c>)(setCon.getSelected())) {
                if (recordTypeName == null) {
                    recordTypeName = refadj.RecordType.DeveloperName;
                } else {
                    allAlike = (allAlike && (recordTypeName.equals(refadj.RecordType.DeveloperName)));
                }
                refadj.Iten_id__c = RefundsAdjustmentsCommon.getItemId(refadj);
            }
        }
        PageReference ref = setCon.save();
        if (allAlike && recordTypeName != null) {
            String url;
            if ('Refund'.equals(recordTypeName)) {
                url = RefundsAdjustmentsCommon.getRefundsPageRef();
            } else if ('Adjustment'.equals(recordTypeName)) {
                url = RefundsAdjustmentsCommon.getAdjustmentsPageRef();
            }
            if (url != null) {
                ref = new PageReference(url);
            }
        }
        System.debug('Ref='+ref);
        return ref;
    }
}