src/objects/Refund_Adjustment__c.object
<CustomObject>
    <description>Captures Refund and Adjustment requests made by Customer Service and RSLPO.</description>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CS</fullName>
                    <label>Customer Service</label>
                </value>
                <value>
                    <fullName>SRS</fullName>
                    <label>Strategic Receivables</label>
                </value>
                <value>
                    <fullName>RSLPO</fullName>
                </value>
                <value>
                    <fullName>SAVEDESK</fullName>
                    <isActive>false</isActive>
                    <label>Retention</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Refund/Adjustment</label>
    <nameField>
        <displayFormat>RFADJ-{00000000}</displayFormat>
        <label>Refund/Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds/Adjustments</pluralLabel>
    <recordTypes>
        <fullName>Adjustment</fullName>
        <active>true</active>
        <label>Adjustment</label>
    </recordTypes>
    <recordTypes>
        <fullName>Refund</fullName>
        <active>true</active>
        <label>Refund</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Support_Operation_Settings__c.object
<CustomObject>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/Support_Operation_Settings__c/fields/Adjustments_for_Finance_Approval_Rpt_ID__c.field-meta.xml
<CustomField>
    <fullName>Adjustments_for_Finance_Approval_Rpt_ID__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Adjustments for Finance Approval Rpt ID</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Support_Operation_Settings__c/fields/RefundsForFinanceApprovalReportId__c.field-meta.xml
<CustomField>
    <fullName>RefundsForFinanceApprovalReportId__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Refunds For Finance Approval Report Id</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

src/classes/RefundsAdjustmentsCommon.cls
/**
 * Created by W083158 on 6/25/2019.
 */

public with sharing class RefundsAdjustmentsCommon {
    private static String dateString = System.now().format('MMddYY')+ ' ';

    private static Support_Operation_Settings__c sos;

    public static String getItemId(Refund_Adjustment__c refadj) {
        String result = 'REFUND';
        if ('Adjustment' == refadj.RecordType.DeveloperName) {
            result = dateString + refadj.Department__c;
        }
        return result;
    }

    public static String getAdjustmentsPageRef() {
        getSupportOperationsSettings();
        return makeReportPageRef(sos.Adjustments_for_Finance_Approval_Rpt_ID__c);
    }

    public static String getRefundsPageRef() {
        getSupportOperationsSettings();
        return makeReportPageRef(sos.RefundsForFinanceApprovalReportId__c);
    }

    private static void getSupportOperationsSettings() {
        if (sos == null) {
            sos = Support_Operation_Settings__c.getInstance();
        }
    }

    private static String makeReportPageRef(String reportId) {
        return '/lightning/r/Report/' + reportId + '/view';
    }

}