src/objects/Refund_Adjustment__c.object
<CustomObject>
    <description>Captures Refund and Adjustment requests made by Customer Service and RSLPO.</description>
    <fields>
        <fullName>Approval_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Required for denial</inlineHelpText>
        <label>Approval Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Held</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Refunds_Adjustments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Decision_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Decision Date</label>
        <type>DateTime</type>
    </fields>
    <label>Refund/Adjustment</label>
    <nameField>
        <displayFormat>RFADJ-{00000000}</displayFormat>
        <label>Refund/Adjustment ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Refunds/Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RefundsAdjustmentsInstantApprover.cls
/**
 * Created by W083158 on 4/24/2019.
 */

public with sharing class RefundsAdjustmentsInstantApprover {
    ApexPages.StandardSetController setCon;

    public RefundsAdjustmentsInstantApprover(ApexPages.StandardSetController controller) {
        System.debug('Load RefundsAdjustmentsInstantApprover');
        setCon = controller;
        ((Refund_Adjustment__c)(setCon.getRecord())).Approver_Name__c = UserInfo.getUserId();
        ((Refund_Adjustment__c)(setCon.getRecord())).Decision_Date__c = System.now();
    }

    public PageReference updateRecords() {
        System.debug('Saving RefundsAdjustmentsInstantApprover');
        System.debug('Updating record count: '+setCon.getSelected().size());
        for (Refund_Adjustment__c refadj : (List<Refund_Adjustment__c>)(setCon.getSelected())) {
            if (refadj.Approval_Status__c != 'Approved' && refadj.Approval_Status__c != 'Denied') {
                refadj.Approver_Name__c = UserInfo.getUserId();
                refadj.Decision_Date__c = System.now();
                refadj.Approval_Status__c = 'Approved';
                refadj.Approval_Comment__c = '';
            }
        }
        PageReference ref = setCon.save();
        System.debug('Ref='+ref);
        return ref;
    }
}