src/objects/Shipment_Charge__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Price__c</fullName>
        <label>Effective Price</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Price_Check__c</fullName>
        <description>Check whether the effective price is greater than the minimum price from the product catalog.</description>
        <label>Min Price Check</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductRatePlanCharge__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Rate Plan Charge</label>
        <referenceTo>zqu__ProductRatePlanCharge__c</referenceTo>
        <relationshipLabel>Shipment Charges</relationshipLabel>
        <relationshipName>Shipment_Charges</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>7</scale>
        <type>Currency</type>
    </fields>
    <label>Shipment Charge</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Shipment Charge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipment Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/zqu__ProductRatePlanCharge__c.object
<CustomObject>
    <fields>
        <fullName>WEXMinPrice__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>WEX Min Price (TEXT)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/Z_SC_TriggerHandler.cls
public with sharing class Z_SC_TriggerHandler {
  
  public Z_SC_TriggerHandler() {
  
  }
  
  public void onAfterInsert(Map<Id, Shipment_Charge__c> newSCsMap) {
    
    List<Shipment_Charge__c> scToUpdate; 
    Decimal minPrice; 
    
    scToUpdate = [SELECT  Id, 
        Name, 
        Min_Price_Check__c, 
        Effective_Price__c,
        Total__c,          
        ProductRatePlanCharge__r.WEXMinPrice__c 
      FROM    Shipment_Charge__c 
      WHERE   Id in: newSCsMap.keySet()]; 
    
    for (Shipment_Charge__c sc : scToUpdate) {
      try {
          minPrice = Decimal.valueOf(sc.ProductRatePlanCharge__r.WEXMinPrice__c); 
      } catch(Exception e) {
          minPrice = 0;
      }
      if (sc.Total__c < minPrice) {
        sc.Min_Price_Check__c = 0; 
      }
      else {
        sc.Min_Price_Check__c = 1; 
      }
    }
    
    update scToUpdate; 
    
  }
  
}