src/objects/URL__c.object
<CustomObject>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>If part of a list, like the Top FAQs, the sort order of where it appears in that list</description>
        <inlineHelpText>If part of a list, like the Top FAQs, the sort order of where it appears in that list</inlineHelpText>
        <label>Sort Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>URL_Category__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>URL Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Group__c</fullName>
        <description>The grouping for the URL. This determines where on the page the URL is listed. New ones can not be added without the page layout of the PKB being adjusted</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The grouping for the URL. This determines where on the page the URL is listed. New ones can not be added without the page layout of the PKB being adjusted</inlineHelpText>
        <label>URL Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Label__c</fullName>
        <description>The text that appears on the page for the URL</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The text that appears on the page for the URL</inlineHelpText>
        <label>URL Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL_Target__c</fullName>
        <defaultValue>&apos;_self&apos;</defaultValue>
        <description>Target of the URL link</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Target of the URL link</inlineHelpText>
        <label>URL Target</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <description>The URL of the link</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>The URL of the link</inlineHelpText>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/PartnersCommLeftNavController.cls
/*

    Name: PartnersCommLeftNavController
    Created By: Jason McCormack (GearsCRM)
    Created Date: 
    Description: 
    
    Modified By: 
    Modified Date: 
    Description: 

*/

public class PartnersCommLeftNavController 
{	
	public List<URL__c> LeftNavURLs {get; private set;}	
	public List<URL__c> LeftNavCommonIssuesURLs {get; private set;}
	
    public PartnersCommLeftNavController()
    {    	
		loadLeftNavURLs();
		loadLeftNavCommonIssuesURLs();
    }    
    
    private void loadLeftNavURLs()
    {
    	String urlCategory = Deployment_PartnersCommunity.LeftNavURLsCategoryName;
    	String urlGroup = Deployment_PartnersCommunity.LeftNavURLsGroupName; 
    	    	
    	this.LeftNavURLs = [select 
    							Id, 
    							URL_Label__c,    
    							URL__c, 							
    							URL_Target__c 
    						from 
    							URL__c 
    						where 
    							URL_Category__c = :urlCategory and 
    							URL_Group__c = :urlGroup 
    						order by 
    							Sort_Order__c asc];		
	}
    
    private void loadLeftNavCommonIssuesURLs()
    {
    	String urlCategory = Deployment_PartnersCommunity.LeftNavCommonIssuesURLsCategoryName;
    	String urlGroup = Deployment_PartnersCommunity.LeftNavCommonIssuesURLsGroupName; 
    	
    	this.LeftNavCommonIssuesURLs = [select 
			    							Id, 
			    							URL_Label__c, 
			    							URL__c, 
			    							URL_Target__c 
			    						from 
			    							URL__c 
			    						where 
			    							URL_Category__c = :urlCategory and 
			    							URL_Group__c = :urlGroup 
			    						order by 
			    							Sort_Order__c asc];
	}
        
    public class CustomException extends Exception {}
}