src/objects/Velocity_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Country_code__c</fullName>
        <label>Country Code</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GB</fullName>
                    <default>true</default>
                    <label>GB</label>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>IE</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LU</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                    <isActive>false</isActive>
                    <label>Benelux</label>
                </value>
                <value>
                    <fullName>France</fullName>
                    <isActive>false</isActive>
                    <label>France</label>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <isActive>false</isActive>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>Italy</fullName>
                    <isActive>false</isActive>
                    <label>Italy</label>
                </value>
                <value>
                    <fullName>Norway</fullName>
                    <isActive>false</isActive>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>UK</fullName>
                    <isActive>false</isActive>
                    <label>UK</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LowerLimit__c</fullName>
        <inlineHelpText>Litre spend per vehicle Lower Limit</inlineHelpText>
        <label>Lower Limit</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UpperLimit__c</fullName>
        <inlineHelpText>Litre spend per vehicle Upper Limit</inlineHelpText>
        <label>Upper Limit</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VehicleType__c</fullName>
        <label>Type of Vehicle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Vehicles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>VelocityProfile__c</fullName>
        <label>Velocity Profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Velocity_Profile</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/WES_Application_Request__c.object
<CustomObject>
    <description>WES version of Application Request as need ownership of records (existing Application Request has Master Detail to Opportunity).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>WES business processes.
The related Account for this Application Request</description>
        <inlineHelpText>The related Account for this Application Request</inlineHelpText>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WES Application Requests</relationshipLabel>
        <relationshipName>WES_Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BiggestVehicle__c</fullName>
        <label>Biggest Vehicle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Vehicles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Create_Fuel_Cards__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Triggers an Apex class that creates Fuel Cards based on default values.</description>
        <inlineHelpText>Fuel Card Packs with Driver/VRN along with Card Defaults for each card type must be entered before Fuel Cards can be created.</inlineHelpText>
        <label>Create Fuel Cards</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Additional_Embossed_Line__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Default Additional Embossed Line</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Card_Type__c</fullName>
        <label>Default Card Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Esso</fullName>
                </value>
                <value>
                    <fullName>EDC</fullName>
                </value>
                <value>
                    <fullName>UK Fuels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Diesel_per_month_Litres__c</fullName>
        <label>Diesel used per month (Litres)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fuel_Card_Packs__c</fullName>
        <description>Number of Fuel card packs they need generated for Vehicles / Drivers.</description>
        <inlineHelpText>This number automatically creates new Fuel Card packs with Default Card Type and Card Holder if the number needed is greater than the current number of card packs.</inlineHelpText>
        <label>How many Fuel Card Packs to Generate?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Petrol_used_per_month_Litres__c</fullName>
        <label>Petrol used per month (Litres)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VelocityProfile__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Velocity Profile</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ofVehicles__c</fullName>
        <label># of Vehicles</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WES Application Request</label>
    <nameField>
        <displayFormat>WES-AR-{0000}</displayFormat>
        <label>WES Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Application Requests</pluralLabel>
    <recordTypes>
        <fullName>WES_Limited_Company</fullName>
        <active>true</active>
        <label>Limited Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WES_Fuel_Card__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Option_Services__c</fullName>
        <label>Purchase Option Services</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Toll_Usage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0</fullName>
                    <label>0 - None</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>1 - Special</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 - Tolls + Ferries</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 - Tolls + Ferries + Special</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 - Carwash</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 - Carwash + Special</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 - Carwash + Tolls + Ferries</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 - Carwash + Tolls + Ferries + Special</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Toll_Usage__c</fullName>
        <label>Toll Usage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WES_Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WES Application Request</label>
        <referenceTo>WES_Application_Request__c</referenceTo>
        <relationshipLabel>WES Fuel Cards</relationshipLabel>
        <relationshipName>WES_Fuel_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WES Fuel Card</label>
    <nameField>
        <displayFormat>WES-FC-{0000}</displayFormat>
        <label>WES Fuel Card #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Fuel Cards</pluralLabel>
    <recordTypes>
        <fullName>EDC</fullName>
        <active>true</active>
        <label>EDC</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WES_Fuel_Card_Default__c.object
<CustomObject>
    <fields>
        <fullName>Purchase_Option_Services__c</fullName>
        <label>Purchase Option Services</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Toll_Usage__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>0</fullName>
                    <label>0 - None</label>
                </value>
                <value>
                    <fullName>1</fullName>
                    <label>1 - Special</label>
                </value>
                <value>
                    <fullName>2</fullName>
                    <label>2 - Tolls + Ferries</label>
                </value>
                <value>
                    <fullName>3</fullName>
                    <label>3 - Tolls + Ferries + Special</label>
                </value>
                <value>
                    <fullName>4</fullName>
                    <label>4 - Carwash</label>
                </value>
                <value>
                    <fullName>5</fullName>
                    <label>5 - Carwash + Special</label>
                </value>
                <value>
                    <fullName>6</fullName>
                    <label>6 - Carwash + Tolls + Ferries</label>
                </value>
                <value>
                    <fullName>7</fullName>
                    <label>7 - Carwash + Tolls + Ferries + Special</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Toll_Usage__c</fullName>
        <label>Toll Usage</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Y</fullName>
                    <label>Yes</label>
                </value>
                <value>
                    <fullName>N</fullName>
                    <label>No</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WES_Application_Request__c</fullName>
        <label>WES Application Request</label>
        <referenceTo>WES_Application_Request__c</referenceTo>
        <relationshipLabel>WES Fuel Cards Defaults</relationshipLabel>
        <relationshipName>WES_Fuel_Card_Defaults_Defaults</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/globalValueSets/Type_of_Vehicles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cars</fullName>
    </customValue>
    <customValue>
        <fullName>Vans</fullName>
    </customValue>
    <customValue>
        <fullName>HGV</fullName>
    </customValue>
    <customValue>
        <fullName>LGV</fullName>
    </customValue>
    <customValue>
        <fullName>Coaches</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycles</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Type of Vehicles</masterLabel>
</GlobalValueSet>

WexGit/Wex_DX/force-app/main/default/globalValueSets/Velocity_Profile.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>F01</fullName>
    </customValue>
    <customValue>
        <fullName>F01L</fullName>
    </customValue>
    <customValue>
        <fullName>F02</fullName>
    </customValue>
    <customValue>
        <fullName>F02L</fullName>
    </customValue>
    <customValue>
        <fullName>F03</fullName>
    </customValue>
    <customValue>
        <fullName>F03V</fullName>
    </customValue>
    <customValue>
        <fullName>F04</fullName>
    </customValue>
    <customValue>
        <fullName>S01</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T02V</fullName>
    </customValue>
    <customValue>
        <fullName>T03V</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <isActive>false</isActive>
        <label>EX</label>
    </customValue>
    <masterLabel>Velocity Profile</masterLabel>
</GlobalValueSet>

src/classes/WESApplicationRequestTriggerHandlerTest.cls
@istest
public class WESApplicationRequestTriggerHandlerTest {
    @testsetup
    static void setupData() {
        Velocity_Profile__c prof1 = new Velocity_Profile__c();
        prof1.Country_code__c = 'GB;DE';
        prof1.LowerLimit__c = 0;
        prof1.UpperLimit__c = 15000;
        prof1.VehicleType__c = 'Coaches';
        prof1.VelocityProfile__c = 'T01';
        insert prof1;

        Velocity_Profile__c prof2 = new Velocity_Profile__c();
        prof2.Country_code__c = 'GB;DE';
        prof2.LowerLimit__c = 15000;
        prof2.UpperLimit__c = 25000;
        prof2.VehicleType__c = 'Coaches';
        prof2.VelocityProfile__c = 'T02';
        insert prof2;

        Account acc1 = new Account(name='test1');
        acc1.WES_ISO_Country_Code__c = 'GB';
        insert acc1;

        Account acc2 = new Account(name='test2');
        acc2.WES_ISO_Country_Code__c = 'DE';
        insert acc2;
    }
    static testmethod void testVelocityProfileMatchFound1() {
        Account acc1 = [SELECT Id FROM Account WHERE WES_ISO_Country_Code__c = 'GB'];
        Velocity_Profile__c prof1 = [SELECT VelocityProfile__c FROM Velocity_Profile__c WHERE VelocityProfile__c = 'T01'];

        WES_Application_Request__c req = new WES_Application_Request__c();
        req.Account__c = acc1.Id;
        req.ofVehicles__c = 10;
        req.Diesel_per_month_Litres__c = 50000;
        req.Petrol_used_per_month_Litres__c = 50000;
        req.BiggestVehicle__c = 'Coaches';

        Test.startTest();
        insert req;
        Test.stopTest();

        req = [SELECT VelocityProfile__c FROM WES_Application_Request__c WHERE Id = :req.Id];
        System.assertEquals(prof1.VelocityProfile__c,req.VelocityProfile__c);
    }

    static testmethod void testVelocityProfileMatchFound2() {
        Account acc2 = [SELECT Id FROM Account WHERE WES_ISO_Country_Code__c = 'DE'];
        Velocity_Profile__c prof2 = [SELECT VelocityProfile__c FROM Velocity_Profile__c WHERE VelocityProfile__c = 'T02'];

        WES_Application_Request__c req = new WES_Application_Request__c();
        req.Account__c = acc2.Id;
        req.ofVehicles__c = 5;
        req.Diesel_per_month_Litres__c = 40000;
        req.Petrol_used_per_month_Litres__c = 40000;
        req.BiggestVehicle__c = 'Coaches';

        Test.startTest();
        insert req;
        Test.stopTest();

        req = [SELECT VelocityProfile__c FROM WES_Application_Request__c WHERE Id = :req.Id];
        System.assertEquals(prof2.VelocityProfile__c, req.VelocityProfile__c);
    }


    static testmethod void testVelocityProfileNoMatchFound() {
        Account acc2 = [SELECT Id FROM Account WHERE WES_ISO_Country_Code__c = 'DE'];

        WES_Application_Request__c req = new WES_Application_Request__c();
        req.Account__c = acc2.Id;
        req.ofVehicles__c = 10;
        req.Diesel_per_month_Litres__c = 50000;
        req.Petrol_used_per_month_Litres__c = 50000;
        req.BiggestVehicle__c = 'Cars';

        Test.startTest();
        insert req;
        Test.stopTest();

        req = [SELECT VelocityProfile__c FROM WES_Application_Request__c WHERE Id = :req.Id];
        System.assertEquals('No Match Found', req.VelocityProfile__c);
    }

    static testmethod void testVelocityProfileMatchUpdate() {
        Account acc1 = [SELECT Id FROM Account WHERE WES_ISO_Country_Code__c = 'GB'];

        WES_Application_Request__c req = new WES_Application_Request__c();
        req.Account__c = acc1.Id;
        req.ofVehicles__c = 10;
        req.Diesel_per_month_Litres__c = 50000;
        req.Petrol_used_per_month_Litres__c = 50000;
        req.BiggestVehicle__c = 'Coaches';
        insert req;

        req.BiggestVehicle__c = 'Cars';

        Test.startTest();
        update req;
        Test.stopTest();

        req = [SELECT VelocityProfile__c FROM WES_Application_Request__c WHERE Id = :req.Id];
        System.assertEquals('No Match Found', req.VelocityProfile__c);
    }

    static testmethod void testVelocityProfileMatchMultipleRecords() {
        Account acc1 = [SELECT Id FROM Account WHERE WES_ISO_Country_Code__c = 'GB'];
        Velocity_Profile__c prof1 = [SELECT VelocityProfile__c FROM Velocity_Profile__c WHERE VelocityProfile__c = 'T01'];

        WES_Application_Request__c req1 = new WES_Application_Request__c();
        req1.Account__c = acc1.Id;
        req1.ofVehicles__c = 10;
        req1.Diesel_per_month_Litres__c = 50000;
        req1.Petrol_used_per_month_Litres__c = 50000;
        req1.BiggestVehicle__c = 'Coaches';

        WES_Application_Request__c req2 = new WES_Application_Request__c();
        req2.Account__c = acc1.Id;

        Test.startTest();
        insert new List<WES_Application_Request__c> {req1, req2};
        Test.stopTest();

        req1 = [SELECT VelocityProfile__c FROM WES_Application_Request__c WHERE Id = :req1.Id];
        System.assertEquals(prof1.VelocityProfile__c, req1.VelocityProfile__c);

        req2 = [SELECT VelocityProfile__c FROM WES_Application_Request__c WHERE Id = :req2.Id];
        System.assertEquals(null, req2.VelocityProfile__c);
    }

    static testmethod void testFuelPacksAndCards() {
        Account acc1 = [SELECT Id FROM Account WHERE WES_ISO_Country_Code__c = 'GB'];

        Id rectypeid = [SELECT Id FROM RecordType WHERE sObjectType = 'WES_Application_Request__c' AND DeveloperName = 'WES_Limited_Company' LIMIT 1].Id;

        WES_Application_Request__c req = new WES_Application_Request__c();
        req.Account__c = acc1.Id;
        req.RecordTypeId = rectypeid;
        req.ofVehicles__c = 10;
        req.Diesel_per_month_Litres__c = 50000;
        req.Petrol_used_per_month_Litres__c = 50000;
        req.BiggestVehicle__c = 'Coaches';
        req.Fuel_Card_Packs__c = 3;
        req.Default_Card_Type__c = 'EDC';
        req.Default_Additional_Embossed_Line__c = 'test';
        req.Create_Fuel_Cards__c = true;
        insert req;

        Id defRectypeId = [SELECT Id FROM RecordType WHERE sObjectType = 'WES_Fuel_Card_Default__c' AND DeveloperName = 'EDC' LIMIT 1].Id;

        WES_Fuel_Card_Default__c def = new WES_Fuel_Card_Default__c();
        def.WES_Application_Request__c = req.Id;
        def.RecordTypeId = defRectypeId;
        def.Toll_Usage__c = 'Y';
        def.Purchase_Option_Services__c = '0';
        insert def;

        Test.startTest();
        update req;
        Test.stopTest();

        List<WES_Fuel_Card__c> cards = [SELECT Id FROM WES_Fuel_Card__c WHERE WES_Application_Request__c = :req.Id];
        System.assert(cards.size()!=0);
    }
}