src/objects/Velocity_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Country_code__c</fullName>
        <label>Country Code</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>GB</fullName>
                    <default>true</default>
                    <label>GB</label>
                </value>
                <value>
                    <fullName>BE</fullName>
                </value>
                <value>
                    <fullName>CH</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FR</fullName>
                </value>
                <value>
                    <fullName>IE</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LU</fullName>
                </value>
                <value>
                    <fullName>NL</fullName>
                </value>
                <value>
                    <fullName>NO</fullName>
                </value>
                <value>
                    <fullName>Benelux</fullName>
                    <isActive>false</isActive>
                    <label>Benelux</label>
                </value>
                <value>
                    <fullName>France</fullName>
                    <isActive>false</isActive>
                    <label>France</label>
                </value>
                <value>
                    <fullName>Germany</fullName>
                    <isActive>false</isActive>
                    <label>Germany</label>
                </value>
                <value>
                    <fullName>Italy</fullName>
                    <isActive>false</isActive>
                    <label>Italy</label>
                </value>
                <value>
                    <fullName>Norway</fullName>
                    <isActive>false</isActive>
                    <label>Norway</label>
                </value>
                <value>
                    <fullName>UK</fullName>
                    <isActive>false</isActive>
                    <label>UK</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LowerLimit__c</fullName>
        <inlineHelpText>Litre spend per vehicle Lower Limit</inlineHelpText>
        <label>Lower Limit</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>UpperLimit__c</fullName>
        <inlineHelpText>Litre spend per vehicle Upper Limit</inlineHelpText>
        <label>Upper Limit</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VehicleType__c</fullName>
        <label>Type of Vehicle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Vehicles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>VelocityProfile__c</fullName>
        <label>Velocity Profile</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Velocity_Profile</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

src/objects/WES_Application_Request__c.object
<CustomObject>
    <description>WES version of Application Request as need ownership of records (existing Application Request has Master Detail to Opportunity).</description>
    <fields>
        <fullName>Account_ISO_Country_Code__c</fullName>
        <description>TEXT(Account__r.WES_ISO_Country_Code__c)</description>
        <formula>&quot;GB&quot;</formula>
        <label>Account ISO Country Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Awaiting Security Check</fullName>
                </value>
                <value>
                    <fullName>Awaiting Assignment</fullName>
                </value>
                <value>
                    <fullName>Awaiting Credit Check</fullName>
                </value>
                <value>
                    <fullName>Being Credit Checked</fullName>
                </value>
                <value>
                    <fullName>Awaiting Further Information</fullName>
                </value>
                <value>
                    <fullName>Sales to Obtain Further Information</fullName>
                </value>
                <value>
                    <fullName>Returned from Sales</fullName>
                </value>
                <value>
                    <fullName>Higher Authority</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Unable to Process</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BiggestVehicle__c</fullName>
        <label>Biggest Vehicle</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Type_of_Vehicles</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Companies_House_Check__c</fullName>
        <label>Companies House Check</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pass</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Default_Additional_Embossed_Line__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Default Additional Embossed Line</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Card_Type__c</fullName>
        <label>Default Card Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Esso</fullName>
                </value>
                <value>
                    <fullName>EDC</fullName>
                </value>
                <value>
                    <fullName>UK Fuels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Fuel_Card_Packs__c</fullName>
        <description>Number of Fuel card packs they need generated for Vehicles / Drivers.</description>
        <inlineHelpText>This number automatically creates new Fuel Card packs with Default Card Type and Card Holder if the number needed is greater than the current number of card packs.</inlineHelpText>
        <label>How many Fuel Card Packs to Generate?</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Litrespendpervehicle__c</fullName>
        <formula>(MonthlyFuelVolumeLitres__c / ofVehicles__c)</formula>
        <inlineHelpText>Monthly Fuel Volume (Litres) / # of Vehicles</inlineHelpText>
        <label>Litre spend per vehicle</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MonthlyFuelVolumeLitres__c</fullName>
        <description>Petrol used per month (Litres) + Diesel used per month (Litres)</description>
        <formula>Petrol_used_per_month_Litres__c +  Diesel_per_month_Litres__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Set Petrol &amp; Diesel used per month (Litres) to sum total here.</inlineHelpText>
        <label>Monthly Fuel Volume (Litres)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Card_Packs__c</fullName>
        <label>Total Card Packs</label>
        <summaryForeignKey>WES_Fuel_Card_Pack__c.WES_Application_Request__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>VelocityProfile__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Velocity Profile</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WES_Credit_Details__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WES Credit Details</label>
        <referenceTo>WES_Credit_Details__c</referenceTo>
        <relationshipLabel>WES Application Requests</relationshipLabel>
        <relationshipName>WES_Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ofVehicles__c</fullName>
        <label># of Vehicles</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>WES Application Request</label>
    <nameField>
        <displayFormat>WES-AR-{0000}</displayFormat>
        <label>WES Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Application Requests</pluralLabel>
    <recordTypes>
        <fullName>WES_Limited_Company</fullName>
        <active>true</active>
        <label>Limited Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WES_Credit_Details__c.object
<CustomObject>
    <description>Used to be able to attach files related to a WES Application Request that only Credit can view / edit.</description>
    <fields>
        <fullName>WES_Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WES Application Request</label>
        <referenceTo>WES_Application_Request__c</referenceTo>
        <relationshipLabel>WES Credit Details</relationshipLabel>
        <relationshipName>WES_Credit_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WES Credit Details</label>
    <nameField>
        <displayFormat>WES-CD-{0000}</displayFormat>
        <label>WES Credit Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Credit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WES_Fuel_Card__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Embossed_Line__c</fullName>
        <formula>WESFuelCardPack__r.Additional_Embossed_Line__c</formula>
        <label>Additional Embossed Line</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Esso</fullName>
                </value>
                <value>
                    <fullName>UK Fuels</fullName>
                </value>
                <value>
                    <fullName>EDC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WES_Application_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WES Application Request</label>
        <referenceTo>WES_Application_Request__c</referenceTo>
        <relationshipLabel>WES Fuel Cards</relationshipLabel>
        <relationshipName>WES_Fuel_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WES Fuel Card</label>
    <nameField>
        <displayFormat>WES-FC-{0000}</displayFormat>
        <label>WES Fuel Card #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Fuel Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WES_Fuel_Card_Default__c.object
<CustomObject>
    <fields>
        <fullName>Card_Type__c</fullName>
        <formula>RecordType.Name</formula>
        <label>Card Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WES_Application_Request__c</fullName>
        <label>WES Application Request</label>
        <referenceTo>WES_Application_Request__c</referenceTo>
        <relationshipLabel>WES Fuel Cards Defaults</relationshipLabel>
        <relationshipName>WES_Fuel_Card_Defaults_Defaults</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/WES_Fuel_Card_Pack__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Embossed_Line__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Additional Embossed Line</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Esso</fullName>
                </value>
                <value>
                    <fullName>EDC</fullName>
                </value>
                <value>
                    <fullName>UK Fuels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WES_Application_Request__c</fullName>
        <label>WES Application Request</label>
        <referenceTo>WES_Application_Request__c</referenceTo>
        <relationshipLabel>WES Fuel Card Packs</relationshipLabel>
        <relationshipName>WES_Fuel_Card_Packs1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WES Fuel Card Pack</label>
    <nameField>
        <displayFormat>WES-FCP-{000000}</displayFormat>
        <label>WES Fuel Card Pack #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Fuel Card Packs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/globalValueSets/Type_of_Vehicles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cars</fullName>
    </customValue>
    <customValue>
        <fullName>Vans</fullName>
    </customValue>
    <customValue>
        <fullName>HGV</fullName>
    </customValue>
    <customValue>
        <fullName>LGV</fullName>
    </customValue>
    <customValue>
        <fullName>Coaches</fullName>
    </customValue>
    <customValue>
        <fullName>Motorcycles</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <masterLabel>Type of Vehicles</masterLabel>
</GlobalValueSet>

WexGit/Wex_DX/force-app/main/default/globalValueSets/Velocity_Profile.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>F01</fullName>
    </customValue>
    <customValue>
        <fullName>F01L</fullName>
    </customValue>
    <customValue>
        <fullName>F02</fullName>
    </customValue>
    <customValue>
        <fullName>F02L</fullName>
    </customValue>
    <customValue>
        <fullName>F03</fullName>
    </customValue>
    <customValue>
        <fullName>F03V</fullName>
    </customValue>
    <customValue>
        <fullName>F04</fullName>
    </customValue>
    <customValue>
        <fullName>S01</fullName>
    </customValue>
    <customValue>
        <fullName>T01</fullName>
    </customValue>
    <customValue>
        <fullName>T02</fullName>
    </customValue>
    <customValue>
        <fullName>T02V</fullName>
    </customValue>
    <customValue>
        <fullName>T03V</fullName>
    </customValue>
    <customValue>
        <fullName>EX</fullName>
        <isActive>false</isActive>
        <label>EX</label>
    </customValue>
    <masterLabel>Velocity Profile</masterLabel>
</GlobalValueSet>

src/classes/WESApplicationRequestTriggerHandler.cls
public class WESApplicationRequestTriggerHandler {
    public static void matchVelocityProfile(List<WES_Application_Request__c> records, Map<Id, WES_Application_Request__c> oldMap) {
        Set<String> countryCodes = new Set<String>();
        Set<String> biggestVehicles = new Set<String>();
        for (WES_Application_Request__c req : records) {
            if (processRecordForProfileMatch(req, oldMap)) {
                countryCodes.add(req.Account_ISO_Country_Code__c);
                biggestVehicles.add(req.BiggestVehicle__c);
            }
        }

        if (!countryCodes.isEmpty() && !biggestVehicles.isEmpty()) {
            List<String> countryCodesList = new List<String>();
            for (String s : countryCodes) {
                countryCodesList.add('\'' + s + '\'');
            }
            String countries = String.join(countryCodesList, ',');

            List<Velocity_Profile__c> profList = Database.query('SELECT Country_code__c, LowerLimit__c, UpperLimit__c, VehicleType__c, VelocityProfile__c' +
                                                 ' FROM' +
                                                 ' Velocity_Profile__c' +
                                                 ' WHERE' +
                                                 ' Country_code__c INCLUDES (' + countries + ')' +
                                                 ' AND' +
                                                 ' VehicleType__c IN :biggestVehicles');

            for (WES_Application_Request__c req : records) {
                if (processRecordForProfileMatch(req, oldMap)) {
                    req.VelocityProfile__c = 'No Match Found';
                    for (Velocity_Profile__c prof : profList) {
                        if (prof.Country_code__c.split(';').contains(req.Account_ISO_Country_Code__c)
                                && prof.LowerLimit__c < req.Litrespendpervehicle__c
                                && prof.UpperLimit__c >= req.Litrespendpervehicle__c
                                && prof.VehicleType__c == req.BiggestVehicle__c) {
                            req.VelocityProfile__c = prof.VelocityProfile__c;
                            break;
                        }
                    }
                }
            }
        }
    }

    private static Boolean processRecordForProfileMatch(WES_Application_Request__c req, Map<Id, WES_Application_Request__c> oldMap) {
        Boolean isInsert = oldMap == null;
        if (req.Account_ISO_Country_Code__c!=null
                && req.ofVehicles__c!=null && req.ofVehicles__c >0
                && req.MonthlyFuelVolumeLitres__c   !=null
                && req.BiggestVehicle__c!=null
                &&  (isInsert
                     || req.Account_ISO_Country_Code__c != oldMap.get(req.Id).Account_ISO_Country_Code__c
                     || req.ofVehicles__c != oldMap.get(req.Id).ofVehicles__c
                     || req.MonthlyFuelVolumeLitres__c   != oldMap.get(req.Id).MonthlyFuelVolumeLitres__c   
                     || req.BiggestVehicle__c != oldMap.get(req.Id).BiggestVehicle__c)) {
            return true;
        } else {
            return false;
        }
    }

    public static void checkDNBIntegration(List<WES_Application_Request__c> records, Map<Id, WES_Application_Request__c> oldMap) {
        if (!System.isFuture()) {
            Set<Id> reqIds = new Set<Id> ();
            Boolean isInsert = oldMap == null;
            Id recTypeId = UtilityClass.getRecTypeByDevName('WES_Application_Request__c','WES_Limited_Company');

            for (WES_Application_Request__c req : records) {
                if ( !DNBIntegration.processedIds.contains(req.Id)
                        && req.RecordTypeId == recTypeId
                        && req.Application_Status__c == 'Being Credit Checked'
                        && req.Companies_House_Check__c == 'Pass'
                        && (
                            isInsert
                            || req.RecordTypeId != oldMap.get(req.Id).RecordTypeId
                            || req.Application_Status__c != oldMap.get(req.Id).Application_Status__c
                            || req.Companies_House_Check__c != oldMap.get(req.Id).Companies_House_Check__c
                        )) {
                    reqIds.add(req.Id);
                    DNBIntegration.processedIds.add(req.Id);
                }
            }
            if (!reqIds.isEmpty()) {
                DNBIntegration.getFailureScoreAndRisk(reqIds);
            }
        }
    }

    public static void createCreditDetails(List<WES_Application_Request__c> records, Map<Id, WES_Application_Request__c> oldMap) {
        Map<Id, WES_Credit_Details__c> reqCreditDetailsMap = new Map<Id, WES_Credit_Details__c>();
        for (WES_Application_Request__c req : records) {
            if (req.WES_Credit_Details__c==null) {
                WES_Credit_Details__c cd = new WES_Credit_Details__c();
                cd.WES_Application_Request__c = req.Id;
                reqCreditDetailsMap.put(req.Id, cd);
            }
        }

        if (!reqCreditDetailsMap.isEmpty()) {
            insert reqCreditDetailsMap.values();

            List<WES_Application_Request__c> reqList = [SELECT Id, WES_Credit_Details__c FROM WES_Application_Request__c WHERE Id IN : reqCreditDetailsMap.keySet()];
            for (WES_Application_Request__c req : reqList) {
                req.WES_Credit_Details__c = reqCreditDetailsMap.get(req.Id).Id;
            }

            update reqList;

            Set<Id> creditDetailsIds = new Set<Id>();
            for (WES_Credit_Details__c cd : reqCreditDetailsMap.values()) {
                if ( !DNBIntegration.processedIds.contains(cd.Id)) {
                    creditDetailsIds.add(cd.Id);
                    DNBIntegration.processedIds.add(cd.Id);
                }
            }
            if (!creditDetailsIds.isEmpty()) {
                DNBIntegration.getBusinessReport(creditDetailsIds);
            }
        }
    }

    public static void createFuelPacks(List<WES_Application_Request__c> records, Map<Id, WES_Application_Request__c> oldMap) {
        Boolean isInsert = oldMap == null;
        List<WES_Fuel_Card_Pack__c> cpList = new List<WES_Fuel_Card_Pack__c>();
        for (WES_Application_Request__c req: records) {
            if (req.Fuel_Card_Packs__c!=null
                    && (isInsert
                        || ((req.Fuel_Card_Packs__c != oldMap.get(req.Id).Fuel_Card_Packs__c)
                            &&  req.Fuel_Card_Packs__c > req.Total_Card_Packs__c))) {
                Integer fuelPacksToBeCreated = Integer.valueOf(isInsert ? req.Fuel_Card_Packs__c : (req.Fuel_Card_Packs__c - req.Total_Card_Packs__c));
                for (Integer i=0; i<fuelPacksToBeCreated; i++) {
                    WES_Fuel_Card_Pack__c cp = new WES_Fuel_Card_Pack__c();
                    cp.Card_Type__c = req.Default_Card_Type__c;
                    cp.Additional_Embossed_Line__c = req.Default_Additional_Embossed_Line__c;
                    cp.WES_Application_Request__c = req.Id;
                    cpList.add(cp);
                }
            }
        }

        if (!cpList.isEmpty()) {
            insert cpList;
        }
    }

    public static void createFuelCards(List<WES_Application_Request__c> records, Map<Id, WES_Application_Request__c> oldMap) {
        Boolean isInsert = oldMap == null;
        Set<Id> reqIds = new Set<Id> ();
        for (WES_Application_Request__c req: records) {
            if (req.Create_Fuel_Cards__c==true
                    && (isInsert
                        || req.Total_Fuel_Cards_Needed__c > req.Total_Fuel_Cards__c)) {
                reqIds.add(req.Id);
            }
        }

        if (!reqIds.isEmpty()) {
            Map<Id, RecordType> defaultRecTypes = new Map<Id, RecordType>([SELECT Id, Name FROM RecordType WHERE SobjectType = 'WES_Fuel_Card_Default__c']);
            Map<String, Id> cardRecTypes = new Map<String, Id>();
            for (RecordType recType : [SELECT Id, Name FROM RecordType WHERE SobjectType = 'WES_Fuel_Card__c']) {
                cardRecTypes.put(recType.Name, recType.Id);
            }

            List<WES_Fuel_Card__c> fuelCards = new List<WES_Fuel_Card__c>();

            List<WES_Application_Request__c> reqList = [SELECT Id, Create_Fuel_Cards__c,
                                             (SELECT Id, Card_Type__c FROM WES_Fuel_Card_Packs1__r WHERE Fuel_Cards_Needed__c > 0 AND Fuel_Cards_in_Pack__c = 0),
                                             (SELECT Id, RecordTypeId, Invoice_Sort_Label__c, National_International__c, Other_Networks__c, PIN__c, PIN_Creation_Method__c, PIN_Type__c, POS_Prompt__c, Purchase_Option_Fuel__c, Purchase_Option_Products__c, Purchase_Option_Services__c, Toll_Usage__c, Truck_Fleet__c, Application_Velocity_Profile__c, Card_Holder_Type__c FROM WES_Fuel_Card_Defaults_Defaults__r)
                                             FROM WES_Application_Request__c WHERE Id IN : reqIds];

            for (WES_Application_Request__c req : reqList) {
                for (WES_Fuel_Card_Pack__c cp : req.WES_Fuel_Card_Packs1__r) {
                    List<String> cardTypes = (cp.Card_Type__c!=null) ? cp.Card_Type__c.split(';') : new List<String>();
                    for (String cardType : cardTypes) {
                        for (WES_Fuel_Card_Default__c def: req.WES_Fuel_Card_Defaults_Defaults__r) {
                            if (defaultRecTypes.get(def.RecordTypeId).Name.contains(cardType)) {
                                WES_Fuel_Card__c fc = new WES_Fuel_Card__c();
                                fc.Card_Type__c = cardType;
                                fc.Invoice_Sort_Label__c = def.Invoice_Sort_Label__c;
                                fc.National_International__c = def.National_International__c;
                                fc.Other_Networks__c = def.Other_Networks__c;
                                fc.PIN__c = def.PIN__c;
                                fc.PIN_Creation_Method__c = def.PIN_Creation_Method__c;
                                fc.PIN_Type__c = def.PIN_Type__c;
                                fc.POS_Prompt__c = def.POS_Prompt__c;
                                fc.Purchase_Option_Fuel__c = def.Purchase_Option_Fuel__c;
                                fc.Purchase_Option_Products__c = def.Purchase_Option_Products__c;
                                fc.Purchase_Option_Services__c = def.Purchase_Option_Services__c;
                                fc.Toll_Usage__c = def.Toll_Usage__c;
                                fc.Truck_Fleet__c = def.Truck_Fleet__c;
                                fc.Velocity_Control_Profiler__c = def.Application_Velocity_Profile__c;
                                fc.WESFuelCardPack__c = cp.Id;
                                fc.WES_Application_Request__c = req.Id;
                                fc.RecordTypeId = cardRecTypes.get(cardType);
                                fc.CardHolderType__c = def.Card_Holder_Type__c;
                                fuelCards.add(fc);
                            }
                        }
                    }
                }

                req.Create_Fuel_Cards__c = false;
            }

            if (!fuelCards.isEmpty()) {
                insert fuelCards;
            }

            update reqList;
        }
    }

    public static void sendApplicationToIFCS(List<WES_Application_Request__c> records, Map<Id, WES_Application_Request__c> oldMap) {
        if (!System.isFuture()) {
            Set<Id> reqIds = new Set<Id> ();
            Boolean isInsert = oldMap == null;
            for (WES_Application_Request__c req : records) {
                if ( !IFCSIntegration.processedIds.contains(req.Id)
                        && req.Send_App_to_IFCS__c == true
                        && (
                            isInsert
                            || req.Send_App_to_IFCS__c != oldMap.get(req.Id).Send_App_to_IFCS__c
                        )) {
                    reqIds.add(req.Id);
                    IFCSIntegration.processedIds.add(req.Id);
                }
            }
            if (!reqIds.isEmpty()) {
                IFCSIntegration.sendApplicationToIFCS(reqIds);
            }
        }
    }
}