src/objects/WES_Application_Request__c.object
<CustomObject>
    <description>WES version of Application Request as need ownership of records (existing Application Request has Master Detail to Opportunity).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>WES business processes.
The related Account for this Application Request</description>
        <inlineHelpText>The related Account for this Application Request</inlineHelpText>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WES Application Requests</relationshipLabel>
        <relationshipName>WES_Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>bankAccountNumber__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Account Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>bankIdentifier__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Bank Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <label>WES Application Request</label>
    <nameField>
        <displayFormat>WES-AR-{0000}</displayFormat>
        <label>WES Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Application Requests</pluralLabel>
    <recordTypes>
        <fullName>WES_Limited_Company</fullName>
        <active>true</active>
        <label>Limited Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/classes/SorcodesIntegration_Test.cls
@isTest
  public class SorcodesIntegration_Test 
{
  string EndPoint='https://api.iban.com/clients/api/v4/sort/';
    public  static testmethod void testsorcodesintegration() 
     {
        Account acc1 = new Account();
        acc1.Name = 'test123';
        insert acc1;

        Id rectypeid = [SELECT Id FROM RecordType WHERE sObjectType = 'WES_Application_Request__c' AND DeveloperName = 'WES_Limited_Company' LIMIT 1].Id;

        WES_Application_Request__c obj = new WES_Application_Request__c();
        obj.Account__c = acc1.Id;
        obj.RecordTypeId = rectypeid;
        obj.bankIdentifier__c='401000';
        obj.bankAccountNumber__c='91805762';
        
        insert obj;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator1());
        test.startTest(); 
        Apexpages.StandardController sc = new Apexpages.StandardController(obj);
        SorcodesIntegration myobj=new SorcodesIntegration(sc);
        myobj.sortcode='401000';
        myobj.account='91805762';
        myobj.api_Key='54ac699cdd4680310ba9c7ca56b0053c';
        myobj.EndPoint='https://api.iban.com/clients/api/v4/sort';
        test.stopTest();
        System.assertEquals(myobj.sort_found1,'{code=002, message=Sort Code found in bank directory}');
        System.assertEquals(myobj.modulus,'{code=001, message=Modulus Success: Check digit is valid}');
        System.assertEquals(myobj.dd, 'YES');     
   }
}