src/objects/WES_Application_Request__c.object
<CustomObject>
    <description>WES version of Application Request as need ownership of records (existing Application Request has Master Detail to Opportunity).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>WES business processes.
The related Account for this Application Request</description>
        <inlineHelpText>The related Account for this Application Request</inlineHelpText>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WES Application Requests</relationshipLabel>
        <relationshipName>WES_Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Company_registration_number__c</fullName>
        <description>Populated by workflow related to Company value.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Company registration number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IFCS__c</fullName>
        <formula>Account__r.Integration_Status_Details__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Integration Status Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requestID__c</fullName>
        <externalId>true</externalId>
        <label>requestID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WES Application Request</label>
    <nameField>
        <displayFormat>WES-AR-{0000}</displayFormat>
        <label>WES Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Application Requests</pluralLabel>
    <recordTypes>
        <fullName>WES_Limited_Company</fullName>
        <active>true</active>
        <label>Limited Company</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IFCSInboundServiceTest.cls
@isTest
private class IFCSInboundServiceTest {
    @testSetup
    static void setup(){
        UtilityTestLoader.setAutomation(false);
    }

    static testmethod void testService() {
        Account acc1 = new Account();
        acc1.Name = 'test';
        acc1.WES_ISO_Country_Code__c = 'GB';
        acc1.Company_registration_number__c = '00000006';
        insert acc1;

        Id rectypeid = [SELECT Id FROM RecordType WHERE sObjectType = 'WES_Application_Request__c' AND DeveloperName = 'WES_Limited_Company' LIMIT 1].Id;

        WES_Application_Request__c req = new WES_Application_Request__c();
        req.Account__c = acc1.Id;
        req.RecordTypeId = rectypeid;
        req.requestID__c = 123456;
        insert req;

        RestRequest request = new RestRequest();
        request.httpMethod = 'POST';
        request.requestBody = Blob.valueOf('{"orderId":"123456","customerNumber":"16330004330","accessCode":"a7gpskiodw74zlrcyepw"}');
        RestContext.request = request;

        Test.setMock(HttpCalloutMock.class, new WESAppReq_MockHttpResponseGenerator());

        Test.startTest();
        IFCSInboundService.doPost();
        Test.stopTest();

        acc1 = [SELECT IFCS__c FROM Account WHERE Id = :acc1.Id];

        System.assertEquals('16330004330', acc1.IFCS__c);
    }
}