src/objects/WES_Application_Request__c.object
<CustomObject>
    <description>WES version of Application Request as need ownership of records (existing Application Request has Master Detail to Opportunity).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>WES business processes.
The related Account for this Application Request</description>
        <inlineHelpText>The related Account for this Application Request</inlineHelpText>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>WES Application Requests</relationshipLabel>
        <relationshipName>WES_Application_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IFCS__c</fullName>
        <formula>Account__r.Integration_Status_Details__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Integration Status Details</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>requestID__c</fullName>
        <externalId>true</externalId>
        <label>requestID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>WES Application Request</label>
    <nameField>
        <displayFormat>WES-AR-{0000}</displayFormat>
        <label>WES Application Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WES Application Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IFCSInboundService.cls
@RestResource(urlMapping='/customer/*')
global without sharing class IFCSInboundService {
    @HttpPost
    global static Boolean doPost() {
        RestRequest req = RestContext.request;
        Blob body = req.requestBody;
        String requestString = body.toString();
        CustomerDetails cust = (CustomerDetails) JSON.deserialize(requestString, CustomerDetails.class);
        Decimal requestId;
        try {
            requestId = Decimal.valueOf(cust.orderId);
        } catch(Exception ex) {
            return false;
        }
        List<WES_Application_Request__c> appReqList = [SELECT
                Account__c
                FROM
                WES_Application_Request__c
                WHERE
                requestID__c = :requestId
                               AND
                               Account__c != null
                               LIMIT 1];
        if (!appReqList.isEmpty()) {
            Account acc = new Account(Id = appReqList[0].Account__c);
            acc.IFCS__c = cust.customerNumber;
            update acc;
            return true;
        } else {
            return false;
        }
    }

    public class CustomerDetails {
        public String orderId;
        public String customerNumber;
        public String accessCode;
    }
}