WexGit/Wex_DX/force-app/main/default/objects/Application_History__c/Application_History__c.object-meta.xml
<CustomObject>
    <description>Designed to capture and extrapolate the total amount of time an application spent with the Credit team.</description>
    <label>Application History</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Application History Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Application Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WexGit/Wex_DX/force-app/main/default/objects/Application_History__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>The CreatedDate of the next record. Shows the total time the app sat in it&apos;s last state.</description>
    <encryptionScheme>None</encryptionScheme>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Application_History__c/fields/NA_Fleet_App__c.field-meta.xml
<CustomField>
    <fullName>NA_Fleet_App__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Application Request associated with this record.</description>
    <label>NA Fleet App</label>
    <referenceTo>Application_Request__c</referenceTo>
    <relationshipLabel>Application Histories</relationshipLabel>
    <relationshipName>Application_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/classes/AppHistoryBeforeInsertTriggerHandler.cls
/**
 * Created by lhowland on 8/31/2020.
 */

public with sharing class AppHistoryBeforeInsertTriggerHandler extends TriggerHandlerBase {

    public override void mainEntry(TriggerParameters tp) {

        appHistoryBeforeInsert((List<Application_History__c>) tp.newList);

    }

    private static void appHistoryBeforeInsert(List<Application_History__c> appHistoryList) {

        // When a new history record is created, take that CreatedDate and set it as the End Date for the most recent existing history record.
        // NOTE: if this eventually gets implemented for a different application object, this will need to be split into methods per app object
        List<Id> naFleetAppIds = new List<Id>();
        for (Application_History__c appHistory : appHistoryList) {
            naFleetAppIds.add(appHistory.NA_Fleet_App__c);
        }
        System.debug('List of NA App IDs: from App Histories: ' + naFleetAppIds);

        // For all given App IDs, find the most recent app history objects
        List<AggregateResult> existingHistories = [SELECT NA_Fleet_App__c, Max(Id) appHistoryIdAlias FROM Application_History__c WHERE NA_Fleet_App__c IN :naFleetAppIds AND End_Date__c = NULL GROUP BY NA_Fleet_App__c];

        if (existingHistories != null) {
            List<Application_History__c> updatedExistingAppHistories = new List<Application_History__c>();
            for (AggregateResult ar : existingHistories) {
                Id appHistoryId = (Id)ar.get('appHistoryIdAlias');
                Application_History__c appHistory = new Application_History__c(Id = appHistoryId, End_Date__c = Datetime.now());
                updatedExistingAppHistories.add(appHistory);
            }
            upsert updatedExistingAppHistories;
        } // if null, no need to update End Date field
    }
}