WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>The API name of the Object who&apos;s data will be inserted</description>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Designates the order in which the static resources are loaded into the database.</description>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Required_Fields_Only__c.field-meta.xml
<CustomField>
    <fullName>Required_Fields_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked this data will be inserted as a blank record  without circular  lookup fields populated</description>
    <label>Required Fields Only</label>
    <type>Checkbox</type>
</CustomField>

WexGit/Wex_DX/force-app/main/default/objects/Test_Data_Configuration__mdt/fields/Static_Resource__c.field-meta.xml
<CustomField>
    <fullName>Static_Resource__c</fullName>
    <description>The name of the Static Resource file where the object&apos;s data should be pulled from</description>
    <label>Static Resource</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/classes/CustomIterable.cls
/*
* Test Setup Framework Iterator
* Author: Jason Arbegast
* Initial Date: 5/14/2019
* Description:  creates iterable for dataloaderbatch to use
* Revision History: 
*/

global class CustomIterable implements Iterator<String>, Iterable<String>{

    List<String> records {get; set;}
    Integer i {get; set;}

    public Iterator<String> iterator() {
        return this;
    }

    public CustomIterable(Integer order){

        Test_Data_Configuration__mdt tdc = [SELECT Object__c, Required_Fields_Only__c, Static_Resource__c
        FROM Test_Data_Configuration__mdt
        WHERE Order__c =: order];

        StaticResource nextResource = [SELECT Body FROM StaticResource  WHERE Name =: tdc.Static_Resource__c];

        Blob blobby = nextResource.Body;
        String contentFile = blobby.toString();
        String[] filelines = contentFile.split('\n');

        this.records = filelines;
        i = 0;

        //tests shouldn't need more than 200 of an object. if it does you have bigger issues than test code
        if ( Test.isRunningTest() ) {
            List<String> testRecords = new List<String>();
            for ( Integer i = 0; i < 200; i++ ) {
                if ( this.records.size() > i ) {
                    testRecords.add( filelines[i] );
                }
            }
            this.records = testRecords;
        }
    }

    global boolean hasNext(){
        if(i >= records.size())
            return false;
        return true;
    }

    global String next(){
        if(i < records.size()) {
            i++;
            return records[i-1];
        }
        return null;
    }
}